### ISSUE TITLE
Can't syncronize Cal-/Carddav on iOS9.x

### ISSUE THREAD

**Issue by redhell** [owncloud/calendar#1002]
Hello,

i recently switched to php 7 as it is stable now. I noticed that i can't sync with iOS 9.x

In the log file i find:
Array to string conversion at /path/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php#62

My server logs doesn't show any error to those timestamps.

After switching back to PHP 5.6 it starts to synchronize again.

    oC 8.2.1
    Ubuntu 14.04.
    MariaDB 10
    PHP 7.0 / PHP 5.6.16
    redis cache and locking
    Calendar/Contacts/Tasks are enabled.

**Comment by d--j** [comment]
Hi,

the used version of sabre is not PHP7 compatible.

As a hotfix replace `3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php` with this version:
```php
<?php

namespace Sabre\CalDAV;

use Sabre\VObject;
use DateTime;

/**
 * CalendarQuery Validator
 *
 * This class is responsible for checking if an iCalendar object matches a set
 * of filters. The main function to do this is 'validate'.
 *
 * This is used to determine which icalendar objects should be returned for a
 * calendar-query REPORT request.
 *
 * @copyright Copyright (C) 2007-2015 fruux GmbH (https://fruux.com/).
 * @author Evert Pot (http://evertpot.com/)
 * @license http://sabre.io/license/ Modified BSD License
 */
class CalendarQueryValidator {

    /**
     * Verify if a list of filters applies to the calendar data object
     *
     * The list of filters must be formatted as parsed by \Sabre\CalDAV\CalendarQueryParser
     *
     * @param VObject\Component $vObject
     * @param array $filters
     * @return bool
     */
    function validate(VObject\Component\VCalendar $vObject, array $filters) {

        // The top level object is always a component filter.
        // We'll parse it manually, as it's pretty simple.
        if ($vObject->name !== $filters['name']) {
            return false;
        }

        return
            $this->validateCompFilters($vObject, $filters['comp-filters']) &&
            $this->validatePropFilters($vObject, $filters['prop-filters']);


    }

    /**
     * This method checks the validity of comp-filters.
     *
     * A list of comp-filters needs to be specified. Also the parent of the
     * component we're checking should be specified, not the component to check
     * itself.
     *
     * @param VObject\Component $parent
     * @param array $filters
     * @return bool
     */
    protected function validateCompFilters(VObject\Component $parent, array $filters) {

        foreach ($filters as $filter) {

            $filterName = $filter['name'];

            $isDefined = isset($parent->$filterName);

            if ($filter['is-not-defined']) {

                if ($isDefined) {
                    return false;
                } else {
                    continue;
                }

            }
            if (!$isDefined) {
                return false;
            }

            if ($filter['time-range']) {
                foreach ($parent->$filterName as $subComponent) {
                    if ($this->validateTimeRange($subComponent, $filter['time-range']['start'], $filter['time-range']['end'])) {
                        continue 2;
                    }
                }
                return false;
            }

            if (!$filter['comp-filters'] && !$filter['prop-filters']) {
                continue;
            }

            // If there are sub-filters, we need to find at least one component
            // for which the subfilters hold true.
            foreach ($parent->$filterName as $subComponent) {

                if (
                    $this->validateCompFilters($subComponent, $filter['comp-filters']) &&
                    $this->validatePropFilters($subComponent, $filter['prop-filters'])) {
                        // We had a match, so this comp-filter succeeds
                        continue 2;
                }

            }

            // If we got here it means there were sub-comp-filters or
            // sub-prop-filters and there was no match. This means this filter
            // needs to return false.
            return false;

        }

        // If we got here it means we got through all comp-filters alive so the
        // filters were all true.
        return true;

    }

    /**
     * This method checks the validity of prop-filters.
     *
     * A list of prop-filters needs to be specified. Also the parent of the
     * property we're checking should be specified, not the property to check
     * itself.
     *
     * @param VObject\Component $parent
     * @param array $filters
     * @return bool
     */
    protected function validatePropFilters(VObject\Component $parent, array $filters) {

        foreach ($filters as $filter) {

            $filterName = $filter['name'];

            $isDefined = isset($parent->$filterName);

            if ($filter['is-not-defined']) {

                if ($isDefined) {
                    return false;
                } else {
                    continue;
                }

            }
            if (!$isDefined) {
                return false;
            }

            if ($filter['time-range']) {
                foreach ($parent->$filterName as $subComponent) {
                    if ($this->validateTimeRange($subComponent, $filter['time-range']['start'], $filter['time-range']['end'])) {
                        continue 2;
                    }
                }
                return false;
            }

            if (!$filter['param-filters'] && !$filter['text-match']) {
                continue;
            }

            // If there are sub-filters, we need to find at least one property
            // for which the subfilters hold true.
            foreach ($parent->$filterName as $subComponent) {

                if (
                    $this->validateParamFilters($subComponent, $filter['param-filters']) &&
                    (!$filter['text-match'] || $this->validateTextMatch($subComponent, $filter['text-match']))
                ) {
                    // We had a match, so this prop-filter succeeds
                    continue 2;
                }

            }

            // If we got here it means there were sub-param-filters or
            // text-match filters and there was no match. This means the
            // filter needs to return false.
            return false;

        }

        // If we got here it means we got through all prop-filters alive so the
        // filters were all true.
        return true;

    }

    /**
     * This method checks the validity of param-filters.
     *
     * A list of param-filters needs to be specified. Also the parent of the
     * parameter we're checking should be specified, not the parameter to check
     * itself.
     *
     * @param VObject\Property $parent
     * @param array $filters
     * @return bool
     */
    protected function validateParamFilters(VObject\Property $parent, array $filters) {

        foreach ($filters as $filter) {

            $isDefined = isset($parent[$filter['name']]);

            if ($filter['is-not-defined']) {

                if ($isDefined) {
                    return false;
                } else {
                    continue;
                }

            }
            if (!$isDefined) {
                return false;
            }

            if (!$filter['text-match']) {
                continue;
            }

            // If there are sub-filters, we need to find at least one parameter
            // for which the subfilters hold true.
            foreach ($parent[$filter['name']]->getParts() as $paramPart) {

                if ($this->validateTextMatch($paramPart, $filter['text-match'])) {
                    // We had a match, so this param-filter succeeds
                    continue 2;
                }

            }

            // If we got here it means there was a text-match filter and there
            // were no matches. This means the filter needs to return false.
            return false;

        }

        // If we got here it means we got through all param-filters alive so the
        // filters were all true.
        return true;

    }

    /**
     * This method checks the validity of a text-match.
     *
     * A single text-match should be specified as well as the specific property
     * or parameter we need to validate.
     *
     * @param VObject\Node|string $check Value to check against.
     * @param array $textMatch
     * @return bool
     */
    protected function validateTextMatch($check, array $textMatch) {

        if ($check instanceof VObject\Node) {
            $check = $check->getValue();
        }

        $isMatching = \Sabre\DAV\StringUtil::textMatch($check, $textMatch['value'], $textMatch['collation']);

        return ($textMatch['negate-condition'] xor $isMatching);

    }

    /**
     * Validates if a component matches the given time range.
     *
     * This is all based on the rules specified in rfc4791, which are quite
     * complex.
     *
     * @param VObject\Node $component
     * @param DateTime $start
     * @param DateTime $end
     * @return bool
     */
    protected function validateTimeRange(VObject\Node $component, $start, $end) {

        if (is_null($start)) {
            $start = new DateTime('1900-01-01');
        }
        if (is_null($end)) {
            $end = new DateTime('3000-01-01');
        }

        switch ($component->name) {

            case 'VEVENT' :
            case 'VTODO' :
            case 'VJOURNAL' :

                return $component->isInTimeRange($start, $end);

            case 'VALARM' :

                // If the valarm is wrapped in a recurring event, we need to
                // expand the recursions, and validate each.
                //
                // Our datamodel doesn't easily allow us to do this straight
                // in the VALARM component code, so this is a hack, and an
                // expensive one too.
                if ($component->parent->name === 'VEVENT' && $component->parent->RRULE) {

                    // Fire up the iterator!
                    $it = new VObject\Recur\EventIterator($component->parent->parent, (string)$component->parent->UID);
                    while ($it->valid()) {
                        $expandedEvent = $it->getEventObject();

                        // We need to check from these expanded alarms, which
                        // one is the first to trigger. Based on this, we can
                        // determine if we can 'give up' expanding events.
                        $firstAlarm = null;
                        if ($expandedEvent->VALARM !== null) {
                            foreach ($expandedEvent->VALARM as $expandedAlarm) {

                                $effectiveTrigger = $expandedAlarm->getEffectiveTriggerTime();
                                if ($expandedAlarm->isInTimeRange($start, $end)) {
                                    return true;
                                }

                                if ((string)$expandedAlarm->TRIGGER['VALUE'] === 'DATE-TIME') {
                                    // This is an alarm with a non-relative trigger
                                    // time, likely created by a buggy client. The
                                    // implication is that every alarm in this
                                    // recurring event trigger at the exact same
                                    // time. It doesn't make sense to traverse
                                    // further.
                                } else {
                                    // We store the first alarm as a means to
                                    // figure out when we can stop traversing.
                                    if (!$firstAlarm || $effectiveTrigger < $firstAlarm) {
                                        $firstAlarm = $effectiveTrigger;
                                    }
                                }
                            }
                        }
                        if (is_null($firstAlarm)) {
                            // No alarm was found.
                            //
                            // Or technically: No alarm that will change for
                            // every instance of the recurrence was found,
                            // which means we can assume there was no match.
                            return false;
                        }
                        if ($firstAlarm > $end) {
                            return false;
                        }
                        $it->next();
                    }
                    return false;
                } else {
                    return $component->isInTimeRange($start, $end);
                }

            case 'VFREEBUSY' :
                throw new \Sabre\DAV\Exception\NotImplemented('time-range filters are currently not supported on ' . $component->name . ' components');

            case 'COMPLETED' :
            case 'CREATED' :
            case 'DTEND' :
            case 'DTSTAMP' :
            case 'DTSTART' :
            case 'DUE' :
            case 'LAST-MODIFIED' :
                return ($start <= $component->getDateTime() && $end >= $component->getDateTime());



            default :
                throw new \Sabre\DAV\Exception\BadRequest('You cannot create a time-range filter on a ' . $component->name . ' component');

        }

    }

}

```

**Comment by riku2015** [comment]
Thanks, this fixed issue for me! :)

**Comment by MorrisJobke** [comment]
cc @evert for the sabre dav fix for PHP 7 ;)

**Comment by evert** [comment]
It's not the only PHP7 problem. All of these are fixed in master and will be released this week. Bit more info here: https://groups.google.com/forum/#!topic/sabredav-discuss/kHWTl4dT9jo

**Comment by derkostka** [comment]
Thank you, this also fixed it for me. So will we see this fixed sabredav in the next OC8.2 cycle ? Thanks !

**Comment by DeepDiver1975** [comment]
> Thank you, this also fixed it for me. So will we see this fixed sabredav in the next OC8.2 cycle ? Thanks !

We are aiming for 9.0 with respect to this issue - 9.0 will move caldav and carddav into core with an updated sabre dav code base - which we are currently working on with respect to php7 compat.

https://github.com/fruux/sabre-dav/pull/752
https://github.com/fruux/sabre-vobject/pull/287

**Comment by LukasMa** [comment]
Sounds great :) :+1:

**Comment by crbble** [comment]
Could you please clarify when this problem will be fixed? OC9 is scheduled for march, right? Is it also possible that WebDAV is broken due to the sabre problems?

**Comment by c-o-m-m-a-n-d-e-r-d-a-t-a** [comment]
Perfect thanks, this fixed it for me too.

**Comment by adonix31** [comment]
This fix worked for me on oc 0.8.2.1.4. However, it no longer works after upgrading to oc 0.8.2.2.
Caldav clients on android, such as DAVDroid and Caldav sync, sync nothing and server gives error Array to string conversion at /3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php#62

Of course, I patched the php file again after oc upgrade since it stopped working.
How to fix this?

**Comment by myxor** [comment]
After implementing the hotfix from above i am getting the following every time caldav syncs:

`{"reqId":"xxx","remoteAddr":"xxx","app":"PHP","message":"Array to string conversion at \/usr\/share\/webapps\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php#62","level":3,"time":"2016-01-11T19:22:59+00:00"}`

**Comment by derkostka** [comment]
Hi, getting the same Error like you @myxor . I guess you have some special character in your username ? Mine is an E-Mail adress which results in the error you mentioned. This seems to be one more Bug.

**Comment by cwmke** [comment]
I just thought I would add what worked for me today.  I went to owncloud core's updated [CalendarQueryValidator.php](https://github.com/owncloud/3rdparty/blob/master/sabre/dav/lib/CalDAV/CalendarQueryValidator.php) and replaced my server's version which got everything running again for me on Android and ios.  It appears it was updated 2 days ago which is why I'm guessing pasting the above snippit no longer worked for me.

Thanks to @d--j for pointing out this file originally.

**Comment by RealRancor** [comment]
@cwmke I think you really shouldn't mix versions of files/libs.

**Comment by cwmke** [comment]
Normally I would agree with you but it's the only way I have been able to get everything with the calendar to function properly after much effort.

**Comment by RealRancor** [comment]
Hopefully you haven't broke anything else. The linked file is from SabreDAV 3.0.7 where oC is using 2.1.something

**Comment by cwmke** [comment]
So far so good.  :+1:  I was aware it was from 3.07 but needed the calendar to function since that along with news is my primary use case for owncloud.  I've added a warning to my original comment.  After updating the file, all of the problems I was having with the calendar are resolved and since it seems like the official update won't be available for awhile, I took a shot.  Thanks for your comments.

**Comment by despens** [comment]
Thanks for the quick SabreDAV fix! My BlackBerry is connected again :)

**Comment by DocLambda** [comment]
Updating 
- **sabre-dav** to **latest 2.1 branch** (commit [c6a264c46b5002319be323d7ce55f52e95d8931c] (https://github.com/fruux/sabre-dav/commits/2.1))

and
- **sabre-vobject** to **version 3.5.0**,

both containing a bunch of php7 fixes, solved the problem for me.
Would it be possible to release an owncloud 8.2.x with sabre-dav 2.1.9 (once it is out) and sabre-vobject 3.5.0? The APIs did not change to what we have now as far as I can see....

**Comment by RealRancor** [comment]
@DocLambda oC9 will bring SabreDAV 3.0 which should be compatible with PHP7 according to https://github.com/owncloud/core/issues/21476

**Comment by DocLambda** [comment]
@RealRancor I understood. However, CalDAV is broken for users NOW and oc9 is coming in March if I read the above statements correctly. Please read my comment again, I'm not voting for bumping oc8 to SabreDAV3 but instead using the upstream bugfix-branch SabreDAV **2.1.9** (as soon as it is out)!

So releasing a bugfix soon would be a nice from a user's point-of-view to bridge the time to the oc9 release...

As

**Comment by RealRancor** [comment]
@DocLambda This is the current state. As SabreDAV is shipped in Core asking to Bump SabreDAV in here is the wrong place anyway.

**Comment by DocLambda** [comment]
@RealRancor Ok. Where is the right place to ask this for? As I said the changes are straightforward and btw sabre-dav 2.1.9 is out now...

**Comment by RealRancor** [comment]
@DocLambda https://github.com/owncloud/core/issues would be the right place.

**Comment by RealRancor** [comment]
@DocLambda Created https://github.com/owncloud/core/issues/21914

**Comment by derkostka** [comment]
Any Idea if the following is related to PHP7 issues ?

--> After applying those patches, i run into this:
{"reqId":"ewiFyIAXQDbkyMTfzKZd","remoteAddr":"192.168.6.1","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps2\\\/calendar\\\/lib\\\/sabre\\\/auth.php(167): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps2\\\/calendar\\\/lib\\\/sabre\\\/auth.php(140): OCA\\\\Calendar\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OCA\\\\Calendar\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps2\\\/calendar\\\/appinfo\\\/remote.php(63): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"January 26, 2016 17:25:17","method":"REPORT","url":"\/remote.php\/caldav\/principals\/"}

**Comment by gvde** [comment]
That is normal and there is nothing to do about it. The client first tries without basic authentication, which fails with "401 No basic authentication headers were found" and then tries with basic authentication... Unless you have a way to tell your client to always use basic authentication this error is just normal...

**Comment by RealRancor** [comment]
Exactly. @derkostka thats also the reason why you shouldn't run productive instance in Debug mode (loglevel 0).

**Comment by DocLambda** [comment]
@RealRancor Thanks!

**Comment by RealRancor** [comment]
New SabreDAV release for testing in https://github.com/owncloud/3rdparty/pull/246

**Comment by perfect7gentleman** [comment]
that fix helped me too
