### ISSUE TITLE
One single calendar: exporting / syncing with Thunderbird fails

### ISSUE THREAD

**Issue by yannormanns** [owncloud/calendar#1012]
Good evening everyone.

Since a few days, one of my calendars can neither be exported nor synchronized with Thunderbird (I use Lightning 4.0.5). Paradoxically, syncing it by using the Android app "CalDAV-Sync" works flawlessly. First I thought of a client related problem, but it is also not possible to export the calendar directly from the ownCloud web interface.
Every other (also new created) calender works without problems.

When I try to export it via ownCloud, owncloud.log logs the following error:
> {"reqId":"CPSAUXffAfyGq1xJULhc","remoteAddr":"MY.IP.ADD.RESS","app":"index","message":"Exception: {\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Message\":\"End of document reached prematurely\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(168): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/export.php(68): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/export.php(43): OC_Calendar_Export::generateEvent(Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/export.php(28): OC_Calendar_Export::calendar('4')\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/export.php(20): OC_Calendar_Export::export('4', 'calendar')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 [internal function]: __lambda_func(Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(283): call_user_func('\\\\x00lambda_407', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(874): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/...')\\n#12 \\\/var\\\/www\\\/owncloud\\\/index.php(48): OC::handleRequest()\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2016-01-06T10:26:56+01:00"}

Exporting any other calendar using this method works fine.

When I try to export it via "https://OWNCLOUDURL/remote.php/caldav/calendars/MYUSERNAME/termine?export", I get
> <d:error>
> <s:sabredav-version>2.1.6</s:sabredav-version>
> <s:exception>Sabre\VObject\EofException</s:exception>
> <s:message>End of document reached prematurely</s:message>
> </d:error>`

Exporting any other calendar using this method works fine.

I use the following software:
ownCloud 8.1.5-12.1
Calendar 0.7.3 (the problem occured for the first time with 0.7.2)
PHP 5.4.45-0+deb7u2
Apache 2.2.22-13+deb7u6
MySQL 5.5.46-0+deb7u1

If you need additional information, please let me know.

Best regards,
Yann

**Comment by marcofaber** [comment]
I had the exact same problem with one of the my calenders (except the browser error message during the export of the calender was a different one). The sync in Lightning worked only for new entries in the direction Thunderbird -> Owncloud. The reason for this behavior was a damaged entry in the calender. It was stored only with half of the data:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//dmfs.org//mimedir.icalendar//EN
[...]
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20151208T160000
SUMMARY:XYZ
```
In particular, `END:VEVENT` and `END:VCALENDAR` were missing. The `PRODID` indicates that the entry was created by the Android CalDAV app. A correct entry would look, for example, like:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//dmfs.org//mimedir.icalendar//EN
BEGIN:VEVENT
DTSTART;VALUE=DATE:20130509
SUMMARY:XYZ
TRANSP:OPAQUE
DTEND;VALUE=DATE:20130510
LAST-MODIFIED:20130504T233926Z
DTSTAMP:20130504T233926Z
CREATED:20130504T233926Z
UID:6db5a71c-859a-4ded-...
END:VEVENT
END:VCALENDAR
```
**Solution:**
Within your database, you can search for such incomplete entries with the following database query:
```SQL
SELECT * FROM oc_clndr_objects WHERE calendardata NOT LIKE '%END:VCALENDAR%';
```
If there are any matches, you can either try to repair them or simply delete them (after making a backup of the database table). If you want to repair the entries, the ```UID``` can be found in the database column ```uri``` (without ".ics" at the end).

See also #861.

**Comment by dmfs** [comment]
The problem is most likely caused by MySQL, which doesn't support 4-byte characters (like Emoji) when the tables character encoding is set to [`utf8`](http://dev.mysql.com/doc/refman/5.7/en/charset-unicode-utf8.html).
What happens in that case is that MySQL chops of the remaining part of the String, storing the part before the first 4-byte character only.
The solution would be to create the table with [`utf8mb4`](https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html) encoding.
