### ISSUE TITLE
OC Calendar not supporting expanded retrieval of recurring events (i.e. date ranges)

### ISSUE THREAD

**Issue by MStrecke** [owncloud/calendar#1013]
Setup: OC 8.2.2, Ubuntu 14.04 + python webdav

When quering the OC calendar using a start **and** an end date a Sabre "End of document reached prematurely" exception is thrown (see below). If the end date is omitted, i.e. if only a start date is given, the query succeeds.

According to various posts the End of document exception is usually thrown due to malformed calendar data in the database (missing END:VCALENDAR). This seems not to be the case here, because:

 * the SQL command `SELECT * FROM oc_clndr_objects WHERE calendardata NOT LIKE '%END:VCALENDAR%';` returns an empty set
 * The error stored in the owncloud log file is different. In my case it does **not** mention "MimeDir->parse('BEGIN:VCALENDAR...', 0)".

Perhaps someone has some other ideas?

 * You find below the complete error message from owncloud.log.
 * Captures from Wireshark showing the XML exchange for a simple (start date only) and the query that does throw the exception.

```

{"reqId":"KAfHokenPp96EJ1539HC","remoteAddr":"192.168.0.115","app":"caldav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(102): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('', 0)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(548): Sabre\\\\VObject\\\\Reader::read('')\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#5 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/mike\\\/...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(710): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2016-01-09T09:42:37+00:00"}
````

Simple query
(XML pretty format by me)

````
REPORT /owncloud/remote.php/caldav/calendars/mike/testcal1/ HTTP/1.1
Host: xxxxxxxxxxx
Content-Length: 340
Accept-Encoding: gzip, deflate, compress
Accept: text/xml
User-Agent: Mozilla/5.0
Depth: 1
Content-Type: application/xml; charset="utf-8"
...

<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV">
   <ns0:prop xmlns:ns0="DAV:">
      <C:calendar-data/>
   </ns0:prop>
   <C:filter>
      <C:comp-filter name="VCALENDAR">
         <C:comp-filter name="VEVENT">
            <C:time-range start="20160102T000000Z"/>
         </C:comp-filter>
      </C:comp-filter>
   </C:filter>
</C:calendar-query>


HTTP/1.1 207 Multi-Status
...

<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/owncloud/remote.php/caldav/calendars/mike/testcal1/owncloud-f22a0cac21c534e1e1dc5c855e13e81a.ics</d:href><d:propstat><d:prop><cal:calendar-data>BEGIN:VCALENDAR
VERSION:2.0
PRODID:ownCloud Calendar
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:bdbc4b625a
DTSTAMP:20160108T225543Z
CREATED:20160108T225543Z
LAST-MODIFIED:20160108T225543Z
SUMMARY:Eintrag in testcal
DTSTART;VALUE=DATE:20160120
DTEND;VALUE=DATE:20160121
LOCATION:Ort
DESCRIPTION:Beschreibung\n2. Zeile\nund \\n mit \\m ein
CATEGORIES:cat1\, cat2
END:VEVENT
END:VCALENDAR
</cal:calendar-data></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
````

Query with error (start + end date)

````
REPORT /owncloud/remote.php/caldav/calendars/mike/testcal1/ HTTP/1.1

...

<?xml version='1.0' encoding='utf-8'?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="DAV">
   <ns0:prop xmlns:ns0="DAV:">
      <C:calendar-data>
         <C:expand start="20160102T000000Z" end="20160110T000000Z"/>
      </C:calendar-data>
   </ns0:prop>
   <C:filter>
      <C:comp-filter name="VCALENDAR">
         <C:comp-filter name="VEVENT">
            <C:time-range start="20160102T000000Z" end="20160110T000000Z"/>
         </C:comp-filter>
      </C:comp-filter>
   </C:filter>
</C:calendar-query>

HTTP/1.1 500 Internal Server Error
...

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\VObject\EofException</s:exception>
  <s:message>End of document reached prematurely</s:message>
</d:error>
````

**Comment by MStrecke** [comment]
After some testing, the issue seems to be connected with the `<C:expand start="20160102T000000Z" end="20160202T000000Z"/>` element of the XML file. This element is only present when the database is checked against a time range with start and end date. When removed, the call succeeds, presumably without the extra functionality the `expand` element is requesting..

This query as constructed by the Python webdav library looks very much like the example from RFC 4791 [section 7.8.3](https://tools.ietf.org/html/rfc4791#section-7.8.3).

What could make Sabre fail then?

**Comment by MStrecke** [comment]
In order to narrow down the bug, I've setup a fresh install of owncloud and used the web interface to insert one event. The problem still persists.

I've written a small utility for a raw communication with the server: https://gist.github.com/MStrecke/64bccbf447967da7337b

It sends a simple query (only start date) and an extended query (start + end date) to the server. For the extended query the XML from RFC 4791 is used.
The output can be found here: https://gist.github.com/MStrecke/aba362839673fec9298f

**Comment by MStrecke** [comment]
I've setup and tried several versions of OC

last version without the issue: owncloud 8.0.10  (last one int the 8.0 series that I could find)
first version with the issue: owncloud 8.1.0

**Comment by MStrecke** [comment]
Consolidated into issue https://github.com/owncloud/calendar/issues/1026
