### ISSUE TITLE
SQL errors with postgresql

### ISSUE THREAD

**Issue by bstegmaier75** [owncloud/calendar#1020]
The postgresql log contains many entries like this one
> 2016-01-23 13:51:06 CET [2372-1] owncloud@owncloud ERROR:  invalid input syntax for integer: "contact_birthdays"
> 2016-01-23 13:51:06 CET [2372-2] owncloud@owncloud STATEMENT:  SELECT * FROM "oc_clndr_objects" WHERE "calendarid" = $1 AND "uri" = $2

I did not notice any obvious malfunction due to this error (I see birthdays in both contacts and calendar).
It is also unclear for me if this is a calendar or contacts issue.

Environment:
* Debian testing (current)
* postgresql 9.5
* Owncloud 8.2.2
* Calendar 0.8.1
* Contacts 0.5.0.0

The error was also present in previous Owncloud versions and also with postgresql 9.1

**Comment by fluancefg** [comment]
I had a similar issue with calendar component. I upgraded OC from 8.2.1 to 8.2.3 and then updated the calendar from 0.8.1 to 0.8.2. Then I was not able to activate the calendar anymore due to this error message

**Comment by heiglandreas** [comment]
Similar issue here.

* WebCalendar works fine, 
* iOS-Calendar works fine, 
* Calendar.app (8.0) in MacOS doesn't display anything anymore. Error-Message in Error-log is for example:

```
09.06.16 11:58:06,374 CalendarAgent[430]: [com.apple.calendar.store.log.caldav.queue] [Operation [<CalDAVWriteEntityQueueableOperation: 0x7f9fdf0048c0; Sequence: 118>] was forbidden, server reason: [[<CoreDAVErrorItem: 0x7f9fdc5bc320>]: DAV:error]
<?xml version="1.0" encoding="UTF-8"?>
<A:error xmlns:A="DAV:">
  <D:sabredav-version xmlns:D="http://sabredav.org/ns">2.1.9</D:sabredav-version>
  <D:exception xmlns:D="http://sabredav.org/ns">Doctrine\DBAL\Exception\DriverException</D:exception>
  <D:message xmlns:D="http://sabredav.org/ns">An exception occurred while executing 'SELECT * FROM "oc_clndr_objects" WHERE "calendarid" = ? AND "uri" = ?' with params ["contact_birthdays", "local::2::785.ics"]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input syntax for integer: "contact_birthdays"</D:message>
</A:error>
]
```

ownCloud-Error:

```
Exception: {"Message":"An exception occurred while executing 'SELECT * FROM \"oc_clndr_objects\" WHERE \"calendarid\" = ? AND \"uri\" = ?' with params [\"contact_birthdays\", \"local::2::254.ics\"]:\n\nSQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: \"contact_birthdays\"","Exception":"Doctrine\\DBAL\\Exception\\DriverException","Code":0,"Trace":"#0 \/var\/www\/org.heigl.cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/org.heigl.cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Statement.php(171): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT * FROM \"...', Array)\n#2 \/var\/www\/org.heigl.cloud\/lib\/private\/db\/statementwrapper.php(73): Doctrine\\DBAL\\Statement->execute(Array)\n#3 \/var\/www\/org.heigl.cloud\/apps\/calendar\/lib\/object.php(104): OC_DB_StatementWrapper->execute(Array)\n#4 \/var\/www\/org.heigl.cloud\/apps\/calendar\/lib\/object.php(246): OC_Calendar_Object::findWhereDAVDataIs('contact_birthda...', 'local::2::254.i...')\n#5 \/var\/www\/org.heigl.cloud\/apps\/calendar\/lib\/sabre\/backend.php(415): OC_Calendar_Object::editFromDAVData('contact_birthda...', 'local::2::254.i...', 'BEGIN:VCALENDAR...')\n#6 \/var\/www\/org.heigl.cloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarObject.php(104): OCA\\Calendar\\Sabre\\Backend->updateCalendarObject('contact_birthda...', 'local::2::254.i...', 'BEGIN:VCALENDAR...')\n#7 \/var\/www\/org.heigl.cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): Sabre\\CalDAV\\CalendarObject->put('BEGIN:VCALENDAR...')\n#8 \/var\/www\/org.heigl.cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('calendars\/andre...', 'BEGIN:VCALENDAR...', NULL)\n#9 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#10 \/var\/www\/org.heigl.cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/var\/www\/org.heigl.cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#12 \/var\/www\/org.heigl.cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/var\/www\/org.heigl.cloud\/apps\/calendar\/appinfo\/remote.php(60): Sabre\\DAV\\Server->exec()\n#14 \/var\/www\/org.heigl.cloud\/remote.php(137): require_once('\/var\/www\/org.he...')\n#15 {main}","File":"\/var\/www\/org.heigl.cloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractPostgreSQLDriver.php","Line":91}
```

ownCloud-Environment:

* ownCloud 8.2.5
* Calendar-Plugin: 0.8.2
* Contacts-Plugin: 0.5.0.0
* PHP 7.0.6
* Nginx
* PostgreSQL 9.3
