### ISSUE TITLE
Query from Sabre results in empty timezone info and crashes it

### ISSUE THREAD

**Issue by MStrecke** [owncloud/calendar#1026]
(Info template, see below)

I've raised this issue at the Sabre bug tracker. [There](https://github.com/fruux/sabre-dav/issues/770) it is believed to be a bug at the OC end. A developers from OC:Core [suggested](https://github.com/owncloud/core/issues/22026) that it should be opened here.

The snippet shown below is used by a client application to query an OC server for all calender events that fall within a *date range* (queries with only a start date but without an end date work fine). It is similar to the example code shown in RFC 4791 ***and*** it does work with OC versions prior to 8.1.0. (I've installed an tried them).

The query results in the Sabre exception `End of document reached prematurely`.
Unlike other issues resulting in this exception, it happens with freshly installed OC servers with events entered via the OC web interface.

I've tracked it down to the function `calendarQueryReport` in `/3rdparty/sabre/dav/lib/CalDAV/Plugin.php`. There it seems to query OC for the timezone of the calendar but comes up empty. This unexpected empty string leads to the exception in Sabre (see remark below describing the stack trace).

````
...
        $calendarTimeZone = null;
        if ($parser->expand) {
            // We're expanding, and for that we need to figure out the
            // calendar's timezone.

            $tzProp = '{' . self::NS_CALDAV . '}calendar-timezone';
            $tzResult = $this->server->getProperties($path, [$tzProp]);
            if (isset($tzResult[$tzProp])) {
                // This property contains a VCALENDAR with a single
                // VTIMEZONE.
...
````
Printing `json_encode($tzResult)` returns `{"{urn:ietf:params:xml:ns:caldav}calendar-timezone":""}`. Meaning `isset($tzResult[$tzProp]))` is True while its contents is empty.

My quick fix

````
if (isset($tzResult[$tzProp]) && strlen($tzResult[$tzProp])>0 ) {
````
does avoid the exception and produced nearly the result I've expected, which does however contain not re-decoded CR characters:

````
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:response><d:href>/owncloud/remote.php/caldav/calendars/mike/testcal1/owncloud-b38b7ed4fc69881cf4daa21afaa3afbd.ics</d:href><d:propstat><d:prop><cal:calendar-data>BEGIN:VCALENDAR&#13;
VERSION:2.0&#13;
PRODID:ownCloud Calendar&#13;
CALSCALE:GREGORIAN&#13;
BEGIN:VEVENT&#13;
UID:5684d8902d&#13;
...
````

As the developer evert in the sabre [issue](https://github.com/fruux/sabre-dav/issues/770) put it:

> The real question here is, why does that property return a 0-length string? I think that's the true source of this bug...

That however *I* can not answer because I lack the knowledge how these components work together.

A stripped down client to query OC can be found [here](https://gist.github.com/MStrecke/64bccbf447967da7337b).

 * It sends two queries. The first one uses a only a start date and works fine even in current versions of OC.
 * The second is the XML query shown below, which fails with OC versions >= 8.1.0

#### XML query
see also [RFC 4791 section 7.8.3](https://tools.ietf.org/html/rfc4791#section-7.8.3)

````
REPORT /owncloud/remote.php/caldav/calendars/mike/testcal1/ HTTP/1.1
...

<?xml version="1.0" encoding="utf-8"?>
<C:calendar-query xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:D="urn:DAV">
  <D:prop>
    <C:calendar-data>
      <C:expand start="20160101T000000Z" end="20160130T000000Z"/>
    </C:calendar-data>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="20160101T000000Z" end="20160130T000000Z"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>
````

### Steps to reproduce
1. Create a new OC instance from a ZIP file.
2. Complete the installation
3. Activate the calendar app
4. Create a new calendar
5. Enter an event via the web interface into that calendar
6. Query that event using the XML snippet above

### Expected behaviour
OC should return an XML file which contains the data for that event.

### Actual behaviour
Sabre throws an "End of document reached prematurely".

### Server configuration
Linux (Ubuntu, Rasbian Jessie):

**Web server:**
Apache
Ubuntu: Apache/2.4.16 (Ubuntu)
Raspberry: Apache/2.4.10 (Raspbian)

**Database:**
Ubuntu: MariaDB 5.5.47-MariaDB-1~precise-log
Raspbian: MySQL 5.5.44-0+deb8u1 (Raspbian)

**PHP version:**
Ubuntu: 5.5.31-2+deb.sury.org~precise+1
Raspberry:  5.6.17-0+deb8u1

**ownCloud version:** (see ownCloud admin page)
Tested various version from 7.0 to 8.2.2.

**Updated from an older ownCloud or fresh install:**
fresh install

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Page is redirected to apps/files

**List of activated apps:**

Enabled:
  - activity: 2.1.3
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
  - updater: 0.6
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
````
<?php
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'hermitest',
  ),
  'datadirectory' => '/usr/share/owncloud/data',
  'overwrite.cli.url' => 'http://hermitest/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.2.2.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
);
````

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
not applicable - direct server access via XML

#### Web server error log
```
192.168.0.115 - mike [30/Jan/2016:11:38:04 +0100] "REPORT /owncloud/remote.php/caldav/calendars/mike/testcal1/ HTTP/1.1" 500 3091 "-" "Mozilla/5.0"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"XXXXXXX","remoteAddr":"192.168.0.115","app":"caldav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(102): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/usr\\\/share\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/usr\\\/share\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('', 0)\\n#3 \\\/usr\\\/share\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(558): Sabre\\\\VObject\\\\Reader::read('')\\n#4 \\\/usr\\\/share\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#5 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/mike\\\/...')\\n#6 \\:
```

#### Browser log
not applicable

#### Returned data from OC
(with debug variable in sabre enabled)
````
HTTP/1.1 500 Internal Server Error
Date: Sat, 30 Jan 2016 10:38:04 GMT
Server: Apache/2.4.10 (Raspbian)
Set-Cookie: XXXXX; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=XXXXXXX; path=/owncloud; httponly
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
X-Robots-Tag: none
Set-Cookie: oc2jxv15ck00=XXXXXXXX; path=/owncloud; HttpOnly
X-Sabre-Version: 2.1.7
Content-Length: 2067
Connection: close
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\VObject\EofException</s:exception>
  <s:message>End of document reached prematurely</s:message>
  <s:file>/usr/share/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php</s:file>
  <s:line>250</s:line>
  <s:code>0</s:code>
  <s:stacktrace>#0 /usr/share/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(102): Sabre\VObject\Parser\MimeDir-&gt;readLine()
#1 /usr/share/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(63): Sabre\VObject\Parser\MimeDir-&gt;parseDocument()
#2 /usr/share/owncloud/3rdparty/sabre/vobject/lib/Reader.php(44): Sabre\VObject\Parser\MimeDir-&gt;parse('', 0)
#3 /usr/share/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(561): Sabre\VObject\Reader::read('')
#4 /usr/share/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(232): Sabre\CalDAV\Plugin-&gt;calendarQueryReport(Object(DOMDocument))
#5 [internal function]: Sabre\CalDAV\Plugin-&gt;report('{urn:ietf:param...', Object(DOMDocument), 'calendars/mike/...')
#6 /usr/share/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#7 /usr/share/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(710): Sabre\Event\EventEmitter-&gt;emit('report', Array)
#8 [internal function]: Sabre\DAV\CorePlugin-&gt;httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#9 /usr/share/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
#10 /usr/share/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(478): Sabre\Event\EventEmitter-&gt;emit('method:REPORT', Array)
#11 /usr/share/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(263): Sabre\DAV\Server-&gt;invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#12 /usr/share/owncloud/apps/calendar/appinfo/remote.php(60): Sabre\DAV\Server-&gt;exec()
#13 /usr/share/owncloud/remote.php(137): require_once('/usr/share/ownc...')
#14 {main}</s:stacktrace>
</d:error>
````
Please note line #2 and #3 - there you can see the empty string

#### Releated issues
 * https://github.com/owncloud/calendar/issues/1013
 * https://github.com/fruux/sabre-dav/issues/770
 * https://github.com/owncloud/core/issues/22026

#### Related Gists
 * stripped down client - https://gist.github.com/MStrecke/64bccbf447967da7337b
 * output - https://gist.github.com/MStrecke/aba362839673fec9298

**Comment by pigulla** [comment]
I just ran into this as well, would be awesome if somebody could take a look at it.
