### ISSUE TITLE
CalDav Sync Throws 405 - Method Not Allowed

### ISSUE THREAD

**Issue by nerdoc** [owncloud/calendar#1029]
I have problems using owncloud with Android/DavDroid. I first stumbled upon #915 and hence #489, but this here is *not* the same. I have no user/group restrictions on calendar.

But when I try to enter the URL and credentials at the davdroid interface, I get a "Es wurden keine Addressbücher oder Kalender gefunden" (No address books or calendars found). 

### Steps to reproduce
1. open davdroid, add an account, use URL & username
2. fill in the server and credentials (server just hostname, without "remote.php/caldav/...")
3. tap on ->

### Expected behaviour
davdroid should find calendars/address book

### Actual behaviour
I get a 405 error and davdoid does not find cal/addr.book.
Funnily, if I provide davdoid with the full calendar URL (any of my three ones), owncloud returns all calendars AND address books for my user. So it works.
But only the base URL does not work.

If you need I coult provide you with a fresh user/calendar on my server for testing.

### Server configuration
(uberspace.de)
**Operating system**: CentOS 6.0
**Web server:** apache
**Database:** MySql 5.5
**PHP version:** 5.6
**ownCloud version:** 8.1.1
**Updated from an older ownCloud or fresh install:** Update
**Signing status (ownCloud 9.0 and above):** -

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

not possible, redirected to /index.php/apps/files/ ???
```

**List of activated apps:**

```
Enabled:
 - calendar: 0.7.3
 - contacts: 0.4.0.0
 - documents: 0.8.2
 - encryption: 1.0.0
 - files: 1.1.10
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - notes: 1.1.0
 - updater: 0.6```

**The content of config/config.php:**

```
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/home/nerdocs/xxx',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'theme' => '',
  'maintenance' => false,
  'default_language' => 'de',
  'trusted_domains' => 
  array (
    0 => 'nerdocs.at',
    1 => 'owncloud.nerdocs.at',
  ),
  'secret' => 'xxx',
  'loglevel' => 0,
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\OC\Memcache\Redis',
  'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
        'host'      => '/home/nerdocs/.redis/sock',
        'port'      => 0,
        'timeout'   => 0.0 
    ),
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** -

**Operating system:** Android 5.1.1 (Cyanogenmod 12.1)

### Logs
#### Web server error log
```
ATM no access possible. will provide one if needed and I can get it.
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"FbqzrSKLQZoZKJ0i80Vv","remoteAddr":"81.189.18.167","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-02-01T15:23:58+00:00","method":"POST","url":"\/index.php\/apps\/documents\/ajax\/mimes.php"}
{"reqId":"NbUemUK7UyOuNFiaJdZ1","remoteAddr":"81.189.18.167","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2016-02-01T15:24:40+00:00","method":"POST","url":"\/index.php\/apps\/documents\/ajax\/mimes.php"}
{"reqId":"lvBD+s8CosGxdmWEfPpk","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/virtual\/nerdocs\/owncloud.nerdocs.at\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2016-02-01T15:25:16+00:00","method":"--","url":"--"}
{"reqId":"0kR4FNvx5jqr\/lLR8EOq","remoteAddr":"81.189.18.167","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:43+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/christian\/gemeinsam\/"}
{"reqId":"MKMGkpLQvaO6DFVyzeoz","remoteAddr":"81.189.18.167","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:43+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/christian\/defaultcalendar\/"}
{"reqId":"xMONypaVwhpu4Y7i36XE","remoteAddr":"81.189.18.167","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:43+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/christian\/defaultcalendar_shared_by_sandra\/"}
{"reqId":"eKxMtwS\/3n6Y\/VzuOClw","remoteAddr":"81.189.18.167","app":"carddav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/contacts\\\/appinfo\\\/remote.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:43+00:00","method":"PROPFIND","url":"\/remote.php\/carddav\/addressbooks\/christian\/contacts\/"}
{"reqId":"WH1Fj+DdVQMiIF1kOfUf","remoteAddr":"81.189.18.167","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:46+00:00","method":"OPTIONS","url":"\/remote.php\/caldav\/calendars\/christian\/"}
{"reqId":"1lIEzzH5eYXUoQ8V\/bPn","remoteAddr":"81.189.18.167","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:46+00:00","method":"OPTIONS","url":"\/remote.php\/caldav\/calendars\/christian\/"}
{"reqId":"ySQLeBUrRYuE2Fb6nmUi","remoteAddr":"81.189.18.167","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/remote.php(132): require_once('\\\/var\\\/www\\\/virtua...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/nerdocs\\\/owncloud.nerdocs.at\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-02-01T15:28:46+00:00","method":"OPTIONS","url":"\/remote.php\/caldav\/calendars\/christian\/"}

```

**Comment by RealRancor** [comment]
Have a look at:

https://forum.owncloud.org/viewtopic.php?f=17&t=7536

Might be possible that your webserver is blocking some WebDAV methods (405 Method not allowed)

**Comment by nerdoc** [comment]
No, all problems addressed there are not the same. 
I even d'loaded & compiled litmus and did the check for my server (the WevDAV part) - without bigger (but non-related) problems:
```
-> running `basic':
 0. init.................. pass
 1. begin................. pass
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
 3. put_get............... pass
 4. put_get_utf8_segment.. pass
 5. put_no_parent......... pass
 6. mkcol_over_plain...... pass
 7. delete................ pass
 8. delete_null........... pass
 9. delete_fragment....... pass
10. mkcol................. pass
11. mkcol_again........... pass
12. delete_coll........... pass
13. mkcol_no_parent....... pass
14. mkcol_with_body....... pass
15. finish................ pass
<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':
 0. init.................. pass
 1. begin................. pass
 2. copy_init............. pass
 3. copy_simple........... pass
 4. copy_overwrite........ pass
 5. copy_nodestcoll....... pass
 6. copy_cleanup.......... pass
 7. copy_coll............. pass
 8. copy_shallow.......... pass
 9. move.................. pass
10. move_coll............. pass
11. move_cleanup.......... pass
12. finish................ pass
<- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
-> running `props':
 0. init.................. pass
 1. begin................. pass
 2. propfind_invalid...... pass
 3. propfind_invalid2..... pass
 4. propfind_d0........... pass
 5. propinit.............. pass
 6. propset............... pass
 7. propget............... pass
 8. propextended.......... pass
 9. propmove.............. pass
10. propget............... pass
11. propdeletes........... pass
12. propget............... pass
13. propreplace........... pass
14. propget............... pass
15. propnullns............ pass
16. propget............... pass
17. prophighunicode....... pass
18. propget............... FAIL (Property {http://example.com/neon/litmus/}high-unicode had value , expected 𐀀)
19. propremoveset......... pass
20. propget............... pass
21. propsetremove......... pass
22. propget............... pass
23. propvalnspace......... pass
24. propwformed........... pass
25. propinit.............. pass
26. propmanyns............ pass
27. propget............... pass
28. propcleanup........... pass
29. finish................ pass
<- summary for `props': of 30 tests run: 29 passed, 1 failed. 96.7%
```

I couldn't run the [CalDavTester](http://trac.calendarserver.org/wiki/CalDAVTester) suite againstmy production server as it needs some users + admin pw configured for the test. Too risky for me.

mod_rewrite is enabled on the server.

mod_fcgid is not enabled, but uberspace uses mod_fastcgi. Therefore php runs via mod_fastcgi with user rights.

`RewriteBase /` is in my owncloud's .htaccess as it is running on a subdomain.

I don't know any more what to do else. Syncing calendar with GNOME 3.18 works perfectly. Entering server & credentials and forget.
You are welcome to test on my server:

Server: https://owncloud.nerdocs.at
User: tester
PW: lkjsdfgnbwcuhas

I begin to think that this could be a DavDroid issue instead of ownCloud's.

**Comment by nerdoc** [comment]
I just saw that if I enter the full URL into the DavDroid URL field `https://owncloud.nerdocs.at/remote.php/caldav/calendars/tester/pers%C3%B6nlich`, but use the wrong credentials, I get another error message (401, unathorized). If I enter the right ones, everything works.

It just seems that the automatical finding of the addressbook and calendars does not work even **before** authentication happens. But again: I have no user/group restrictions on my OC apps.

**Comment by RealRancor** [comment]
litmus looks good. Have you checked: https://doc.owncloud.org/server/8.2/admin_manual/issues/index.html#service-discovery as it seems the auto discovery of davdroid is the issue here.

**Comment by nerdoc** [comment]
Yes. As you can see, my owlcoud server lives in owncloud.nerdocs.at; so no subfolder, just a subdomain.
**Well-known:** go to https://owncloud.nerdocs.at/remote.php/caldav, just see what you get there.
I don't know it this is wanted or an error. It seems to be a response from a DAV server, but it tells me that it is an error: `Sabre\DAV\Exception\NotImplemented` - but IIRC it only should be 301ed to /remote.php/carddav - which it does.

**Comment by RealRancor** [comment]
That complete setup looks fine to me. The ``There was no handler found for this "GET" method/Sabre\DAV\Exception\NotImplemented``  is expected when using a browser.

Maybe try to contact the guys of DAVdroid at https://forums.bitfire.at/category/4/davdroid

They probably knows their App better how to debug this.

**Comment by arr0n** [comment]
i have the same issue, and i see davdroid people are saying "your server isn't configured correctly"  which isn't that helpful

**Comment by arr0n** [comment]
I've just quickly tested CaldDav Sync, which worked without problem and CalDav Sync Adapter too

**Comment by gvde** [comment]
1. Update. 8.1.1 and 0.4.0.0 is outdated. There a fixes for these versions like the REQUEST_URI message. Thus, update.

2. Post all logs. Post related logs. Post all the log message which appear when it doesn't work. And also post all the log messages, when you use a calendar URL instead. Without the apache logs it's impossible to tell what is accessed...
