### ISSUE TITLE
[QA] cannot build a signed release

### ISSUE THREAD

**Issue by jnweiger** [owncloud/calendar#1260]
Seen while attemting a release candidate for https://github.com/owncloud/calendar/issues/1259

gitea/appsigning/releasescripts/buildApp calendar v2.0.0-rc.1
fails:
```
...
/usr/bin/yarn run build
yarn run v1.22.5
$ yarn
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > fullcalendar@3.10.5" has unmet peer dependency "jquery@2 - 3".
warning " > fullcalendar@3.10.5" has unmet peer dependency "moment@^2.20.1".
[5/5] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.5".
info To upgrade, run the following command:
$ sudo apt-get update && sudo apt-get install yarn
$ node node_modules/gulp-cli/bin/gulp.js
fs.js:45
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/var/www/owncloud/repo/calendar/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/var/www/owncloud/repo/calendar/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/var/www/owncloud/repo/calendar/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make[2]: *** [Makefile:99: yarn] Error 1
make[2]: Leaving directory '/var/www/owncloud/repo/calendar'
make[1]: *** [Makefile:94: build] Error 2
make[1]: Leaving directory '/var/www/owncloud/repo/calendar'
make: *** [Makefile:120: dist] Error 2
```

**Comment by phil-davis** [comment]
Locally `make appstore` works for me:
```
phil@phil-Inspiron-5468:~/git/owncloud/core/apps-external/calendar$ make clean
rm -rf ./build
rm -rf css/public
rm -rf js/public
phil@phil-Inspiron-5468:~/git/owncloud/core/apps-external/calendar$ make appstore
make yarn
make[1]: Entering directory '/home/phil/git/owncloud/core/apps-external/calendar'
/home/phil/.yarn/bin/yarn run build
yarn run v1.22.18
$ yarn
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ node node_modules/gulp-cli/bin/gulp.js
[10:06:18] Using gulpfile ~/git/owncloud/core/apps-external/calendar/gulpfile.js
[10:06:18] Starting 'jslint'...
[10:06:18] Starting 'sync group0:0'...
[10:06:18] Starting '_buildCSSSources'...
[10:06:18] Starting 'sync group1:0'...
[10:06:18] Starting '_buildJavaScriptSources'...
[10:06:18] Starting 'sync group2:0'...
[10:06:18] Starting '_buildCSSVendor'...
[10:06:18] Starting 'sync group3:0'...
[10:06:18] Starting '_buildJavaScriptVendor'...
[10:06:18] Starting 'sync group4:0'...
[10:06:18] Starting '_buildIEJavaScriptVendor'...
[10:06:18] Finished '_buildCSSVendor' after 519 ms
[10:06:18] Finished 'sync group2:0' after 519 ms
[10:06:18] Starting 'sync group2:1'...
[10:06:18] Starting '_minifyCSSVendor'...
[10:06:19] Finished '_buildCSSSources' after 792 ms
[10:06:19] Finished 'sync group0:0' after 792 ms
[10:06:19] Starting 'sync group0:1'...
[10:06:19] Starting '_minifyCSSSources'...
[10:06:19] Finished '_minifyCSSVendor' after 295 ms
[10:06:19] Finished 'sync group2:1' after 296 ms
[10:06:19] Starting '_buildAndMinifyCSSVendor'...
[10:06:19] Finished '_buildAndMinifyCSSVendor' after 43 μs
[10:06:19] Finished '_minifyCSSSources' after 184 ms
[10:06:19] Finished 'sync group0:1' after 184 ms
[10:06:19] Starting '_buildAndMinifyCSSSources'...
[10:06:19] Finished '_buildAndMinifyCSSSources' after 2.96 μs
[10:06:20] Finished '_buildJavaScriptSources' after 2.16 s
[10:06:20] Finished 'sync group1:0' after 2.16 s
[10:06:20] Starting 'sync group1:1'...
[10:06:20] Starting '_minifyJavaScriptSources'...
[10:06:22] Finished '_minifyJavaScriptSources' after 2.26 s
[10:06:22] Finished 'sync group1:1' after 2.26 s
[10:06:22] Starting '_buildAndMinifyJavaScriptSources'...
[10:06:22] Finished '_buildAndMinifyJavaScriptSources' after 1.86 μs
[10:06:22] Starting '_buildSource'...
[10:06:22] Finished '_buildSource' after 1.73 μs
[10:06:23] Finished '_buildJavaScriptVendor' after 4.72 s
[10:06:23] Finished 'sync group3:0' after 4.72 s
[10:06:23] Starting 'sync group3:1'...
[10:06:23] Starting '_minifyJavaScriptVendor'...
[10:06:23] Finished 'jslint' after 4.79 s
[10:06:23] Starting 'lint'...
[10:06:23] Finished 'lint' after 3.82 μs
[10:06:23] Finished '_buildIEJavaScriptVendor' after 4.79 s
[10:06:23] Finished 'sync group4:0' after 4.8 s
[10:06:23] Starting 'sync group4:1'...
[10:06:23] Starting '_minifyIEJavaScriptVendor'...
[10:06:34] Finished '_minifyJavaScriptVendor' after 11 s
[10:06:34] Finished 'sync group3:1' after 11 s
[10:06:34] Starting '_buildAndMinifyJavaScriptVendor'...
[10:06:34] Finished '_buildAndMinifyJavaScriptVendor' after 2.73 μs
[10:06:46] Finished '_minifyIEJavaScriptVendor' after 24 s
[10:06:46] Finished 'sync group4:1' after 24 s
[10:06:46] Starting '_buildAndMinifyIEJavaScriptVendor'...
[10:06:46] Finished '_buildAndMinifyIEJavaScriptVendor' after 2.55 μs
[10:06:46] Starting '_buildVendor'...
[10:06:46] Finished '_buildVendor' after 1.09 μs
[10:06:46] Starting 'default'...
[10:06:46] Finished 'default' after 1.04 μs
Done in 30.56s.
make[1]: Leaving directory '/home/phil/git/owncloud/core/apps-external/calendar'
rm -rf /home/phil/git/owncloud/core/apps-external/calendar/build/appstore/calendar /home/phil/git/owncloud/core/apps-external/calendar/build/artifacts/appstore
mkdir -p /home/phil/git/owncloud/core/apps-external/calendar/build/appstore/calendar /home/phil/git/owncloud/core/apps-external/calendar/build/artifacts/appstore
cp --parents -r \
"appinfo" \
"controller" \
"http" \
"img" \
"l10n" \
"templates" \
"css/public" \
"js/public" \
"COPYING" \
"CHANGELOG.md" \
/home/phil/git/owncloud/core/apps-external/calendar/build/appstore/calendar
Skipping signing, either no key and certificate found in /home/phil/.owncloud/certificates/calendar.key and /home/phil/.owncloud/certificates/calendar.crt or occ can not be found at /home/phil/git/owncloud/core/apps-external/calendar/../../occ
tar -czf /home/phil/git/owncloud/core/apps-external/calendar/build/artifacts/appstore/calendar.tar.gz -C /home/phil/git/owncloud/core/apps-external/calendar/build/appstore/calendar/../ calendar
```

And `make source` also works, and `make dist` does:
```
# Builds the source and appstore package
.PHONY: dist
dist:
	make source
	make appstore
```

I don't know if the problem is related to yarn 1.22.5 on that signing system, or some other difference??

And I don't know which of the Makefile targets is really supposed to be used - `Makefile` has various "make" targets in it, and I guess there is some history of evolution of this app.

@jnweiger I am not sure what I can do to help.

**Comment by jnweiger** [comment]
Will try the appstore target. thanks.I believe the buildApp script uses make dist by default.

**Comment by jnweiger** [comment]
New node and old gulp seems to be a problem:
https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node-js#55926692

This workaround suggested there works for me:
Add to package.json
```
  "resolutions": { "graceful-fs": "^4.2.9" }
```
