### ISSUE TITLE
[nightly] Javascript tests pipeline is failing

### ISSUE THREAD

**Issue by saw-jan** [owncloud/calendar#1333]
Build: https://drone.owncloud.com/owncloud/calendar/1983/8/4

```bash
+ make test-js
yarn install
yarn install v1.22.22
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Error: https://codeload.github.com/kayellpeee/hsl_rgb_converter/tar.gz/3936a3896dd2f45a5c66317aab6f9175c9fde9fb: Request failed "404 Not Found"
    at ResponseError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:696:66)
    at new ResponseError (/usr/lib/node_modules/yarn/lib/cli.js:802:124)
    at Request.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:66750:16)
    at Request.emit (events.js:400:28)
    at Request.module.exports.Request.onRequestResponse (/usr/lib/node_modules/yarn/lib/cli.js:142287:10)
    at ClientRequest.emit (events.js:400:28)
    at HTTPParser.parserOnIncomingClient (_http_client.js:647:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
    at TLSSocket.socketOnData (_http_client.js:515:22)
    at TLSSocket.emit (events.js:400:28)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make: *** [Makefile:175: node_modules] Error 1
```

**Comment by S-Panta** [comment]
The package `hsl_rgb_converter` is removed from yarn package list. Also, the repository that has this dependency was created two days ago and there's error in json file too.

**Comment by DeepDiver1975** [comment]
Horra. 💪

**Comment by phil-davis** [comment]
> Horra. 💪

@DeepDiver1975 Is that "hooray", or "horror" or?

Do you have any suggestion for what we should do?

**Comment by DeepDiver1975** [comment]
Both 🙈

We need to find another fork of the repo.
If none exists we need to add the logic to this repo.

**Comment by S-Panta** [comment]
I tried forking the main repo and correcting its json. CI shows `hslToRgb() doesn't exist`.
