### ISSUE TITLE
Can't create calendar events + calendar doesn't show up after refresh

### ISSUE THREAD

**Issue by bildlich** [owncloud/calendar#559]
### Steps to reproduce
1. Open calendar app
2. Click New Calendar and create new calendar 'Test'
3. New calendar 'Test' shows up in calendar list
4. Click on a date and create date 'Test date' in calendar 'Test'
5. No visual feedback. JS console says:
   
   >  undefined:1 Uncaught (in promise) INVALID_EVENT
6. Reload page
7. Green dot next to 'Test' calendar doesn't show up, instead the spinning wheel persists. JS console says _(I have redacted all URLs pointing to my owncloud isntance for security reasons)_:
   
   > client.js?v=423e2c2…:183 REPORT https://myowncloudinstallation.com/remote.php/dav/calendars/MyUserName/test/ 500 (Internal Server Error)dav.Client.request @ client.js?v=423e2c2…:183getAll @ app.js?v=423e2c2…:4780(anonymous function) @ app.js?v=423e2c2…:2207
   > app.js?v=423e2c2…:2209 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined(…)(anonymous function) @ app.js?v=423e2c2…:2209

There is also an error logged in the admin panel:

> Exception: {"Message":"This parser only supports VCARD and VCALENDAR files","Exception":"Sabre\VObject\ParseException","Code":0,"Trace":"#0 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\VObject\Parser\MimeDir->parseDocument()\n#1 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\VObject\Parser\MimeDir->parse(Resource id #46, 0)\n#2 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(142): Sabre\VObject\Reader::read(Resource id #46)\n#3 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/apps\/dav\/lib\/caldav\/caldavbackend.php(789): Sabre\CalDAV\Backend\AbstractBackend->validateFilterForObject(Array, Array)\n#4 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): OCA\DAV\CalDAV\CalDavBackend->calendarQuery(6, Array)\n#5 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(596): Sabre\CalDAV\Calendar->calendarQuery(Array)\n#6 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(236): Sabre\CalDAV\Plugin->calendarQueryReport(Object(Sabre\CalDAV\Xml\Request\CalendarQueryReport))\n#7 [internal function]: Sabre\CalDAV\Plugin->report('{urn:ietf:param...', Object(Sabre\CalDAV\Xml\Request\CalendarQueryReport), 'calendars\/Matth...')\n#8 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(716): Sabre\Event\EventEmitter->emit('report', Array)\n#10 [internal function]: Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#11 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\Event\EventEmitter->emit('method:REPORT', Array)\n#13 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#14 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/apps\/dav\/lib\/server.php(142): Sabre\DAV\Server->exec()\n#15 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/apps\/dav\/appinfo\/v2\/remote.php(29): OCA\DAV\Server->exec()\n#16 \/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/remote.php(138): require_once('\/var\/www\/virtua...')\n#17 {main}","File":"\/var\/www\/virtual\/bildlich\/html\/myowncloudinstallation.com\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":125,"User":"MyUserName"}  
### Expected behaviour

Newly created event should have shown up. After page reload, the newly created calendar should load, including the newly created event.
### Actual behaviour

Newly created event doesn't show up. After page reload, the newly created calendar doesn't load.
### Server configuration

**Operating system**:
CentOS

**Web server:**
Apache/2.2.15

**Database:**
Postgres

**PHP version:**
PHP 5.5.10

**ownCloud version:** (see ownCloud admin page)
ownCloud 9.0.1 (stable)

**Calendar version:** (see ownCloud apps page)
1.2.2

**Updated from an older ownCloud or fresh install:**
fresh install

**Signing status (ownCloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:**

```
Activity  2.2.1
Collaborative tags  0.2
Comments  0.2
Deleted files  0.8.0
Federation  0.0.4
First Run Wizard  1.1
Gallery  14.5.0
Mail Template Editor  0.1
Notifications  0.2.3
PDF Viewer  0.8
Share Files  0.9.1
Provisioning API  0.4.1
Text Editor  2.1
Update notification  0.1.0
Versions  1.2.0
Video player  0.9.8
Bookmarks  0.7
Calendar  1.2.2
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'oc6k77ka7s45',
  'trusted_domains' => 
  array (
    0 => 'myowncloudinstallation.com',
  ),
  'datadirectory' => '/var/www/virtual/bildlich/html/myowncloudinstallation.com/data',
  'overwrite.cli.url' => 'https://myowncloudinstallation.com',
  'dbtype' => 'pgsql',
  'version' => '9.0.1.3',
  'dbname' => 'owncloud',
  'dbhost' => '/home/bildlich/tmp/',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration

**Browser:**
Google Chrome   50.0.2661.102

**Operating system:**
OS X 10.11.4

**CalDAV-clients:**
?
#### Web server error log

```
[Sun May 29 23:09:30 2016] [error] [client 40.77.167.52] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:10:56 2016] [error] [client 164.132.161.45] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:11:35 2016] [error] [client 40.77.167.52] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:12:24 2016] [error] [client 207.46.13.6] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:12:33 2016] [error] [client 157.55.39.210] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:14:23 2016] [error] [client 40.77.167.52] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:14:28 2016] [error] [client 40.77.167.52] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:14:47 2016] [crit] [client 31.17.44.138] (13)Permission denied: /var/www/virtual/bildlich/myowncloudinstallation.com/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
[Sun May 29 23:17:32 2016] [error] [client 157.55.39.210] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:19:02 2016] [error] [client 157.55.39.185] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:20:09 2016] [error] [client 40.77.167.52] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:24:02 2016] [error] [client 164.132.161.39] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Sun May 29 23:26:58 2016] [error] [client 31.17.44.138] File does not exist: /var/www/virtual/bildlich/myowncloudinstallation.com/favicon.ico, referer: https://myowncloudinstallation.com/index.php/settings/integrity/failed
[Sun May 29 23:34:04 2016] [error] [client 2a01:488:66:1000:5bfa:7642:0:1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"mO\/dv5e1m3fFlQQgt97Z","remoteAddr":"31.17.44.138","app":"webdav","message":"Exception: {\"Message\":\"This parser only supports VCARD and VCALENDAR files\",\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#1 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse(Resource id #46, 0)\\n#2 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read(Resource id #46)\\n#3 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/lib\\\/caldav\\\/caldavbackend.php(789): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#4 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->calendarQuery(6, Array)\\n#5 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(596): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#6 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(236): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport))\\n#7 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport), 'calendars\\\/Matth...')\\n#8 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#9 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(716): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#13 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/lib\\\/server.php(142): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/remote.php(138): require_once('\\\/var\\\/www\\\/virtua...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":125,\"User\":\"MyUserName\"}","level":4,"time":"2016-05-29T21:10:28+00:00","method":"REPORT","url":"\/remote.php\/dav\/calendars\/MyUserName\/test\/","user":"MyUserName"}
{"reqId":"r1IxhU3G96WAFNKYQFQH","remoteAddr":"31.17.44.138","app":"core","message":"Error while running background job (class: OCA\\DAV\\CardDAV\\SyncJob, arguments: ): {\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Message\":\"This parser only supports VCARD and VCALENDAR files\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#1 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('x424547494e3a56...', 0)\\n#2 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/lib\\\/carddav\\\/syncservice.php(227): Sabre\\\\VObject\\\\Reader::read('x424547494e3a56...')\\n#3 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/lib\\\/carddav\\\/syncservice.php(265): OCA\\\\DAV\\\\CardDAV\\\\SyncService->updateUser(Object(OC\\\\User\\\\User))\\n#4 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/lib\\\/private\\\/user\\\/manager.php(339): OCA\\\\DAV\\\\CardDAV\\\\SyncService->OCA\\\\DAV\\\\CardDAV\\\\{closure}(Object(OC\\\\User\\\\User))\\n#5 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/lib\\\/carddav\\\/syncservice.php(269): OC\\\\User\\\\Manager->callForAllUsers(Object(Closure))\\n#6 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/apps\\\/dav\\\/lib\\\/carddav\\\/syncjob.php(38): OCA\\\\DAV\\\\CardDAV\\\\SyncService->syncInstance()\\n#7 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\DAV\\\\CardDAV\\\\SyncJob->run(NULL)\\n#8 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/lib\\\/private\\\/backgroundjob\\\/timedjob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#9 \\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/cron.php(163): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/bildlich\\\/html\\\/myowncloudinstallation.com\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":125}","level":3,"time":"2016-05-29T21:14:47+00:00","method":"GET","url":"\/cron.php","user":"--"}
```
#### Browser log

```
See above (steps to reproduce)
```

**Comment by bildlich** [comment]
Since the server log lists a lot of redirects and suggests that there may be a configuration error, I am pasting the contents of the .htaccess in the owncloud installation folder below. Only the first few lines were added by me, the rest was created by owncloud.

```
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteCond %{ENV:HTTPS} !=on
RewriteRule .* https://%{SERVER_NAME}%{REQUEST_URI} [R=301,L]

<IfModule mod_headers.c>
  <IfModule mod_setenvif.c>
    <IfModule mod_fcgid.c>
       SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
       RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
    </IfModule>
    <IfModule mod_proxy_fcgi.c>
       SetEnvIfNoCase Authorization "(.+)" HTTP_AUTHORIZATION=$1
    </IfModule>
  </IfModule>

  <IfModule mod_env.c>
    # Add security and privacy related headers
    Header set X-Content-Type-Options "nosniff"
    Header set X-XSS-Protection "1; mode=block"
    Header set X-Robots-Tag "none"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-Download-Options "noopen"
    Header set X-Permitted-Cross-Domain-Policies "none"
    SetEnv modHeadersAvailable true
  </IfModule>

  # Add cache control for CSS and JS files
  <FilesMatch "\.(css|js)$">
    Header set Cache-Control "max-age=7200, public"
  </FilesMatch>
</IfModule>
<IfModule mod_php5.c>
  php_value upload_max_filesize 513M
  php_value post_max_size 513M
  php_value memory_limit 512M
  php_value mbstring.func_overload 0
  php_value always_populate_raw_post_data -1
  php_value default_charset 'UTF-8'
  php_value output_buffering 0
  <IfModule mod_env.c>
    SetEnv htaccessWorking true
  </IfModule>
</IfModule>
<IfModule mod_php7.c>
  php_value upload_max_filesize 513M
  php_value post_max_size 513M
  php_value memory_limit 512M
  php_value mbstring.func_overload 0
  php_value default_charset 'UTF-8'
  php_value output_buffering 0
  <IfModule mod_env.c>
    SetEnv htaccessWorking true
  </IfModule>
</IfModule>
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
  RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
  RewriteRule ^remote/(.*) remote.php [QSA,L]
  RewriteRule ^(build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
  RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
  RewriteRule ^(\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]

  # Rewrite rules for `front_controller_active`
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$
  RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
  RewriteCond %{REQUEST_FILENAME} !/remote.php
  RewriteCond %{REQUEST_FILENAME} !/public.php
  RewriteCond %{REQUEST_FILENAME} !/cron.php
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
  RewriteCond %{REQUEST_FILENAME} !/status.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
  RewriteCond %{REQUEST_FILENAME} !/updater/
  RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
  RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
</IfModule>
<IfModule mod_mime.c>
  AddType image/svg+xml svg svgz
  AddEncoding gzip svgz
</IfModule>
<IfModule mod_dir.c>
  DirectoryIndex index.php index.html
</IfModule>
AddDefaultCharset utf-8
Options -Indexes
<IfModule pagespeed_module>
  ModPagespeed Off
</IfModule>
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

ErrorDocument 403 /core/templates/403.php
ErrorDocument 404 /core/templates/404.php
<IfModule mod_rewrite.c>
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>

```

**Comment by bildlich** [comment]
This may or may not be related: When I open the admin panel, the JS console says:

> https://myowncloudinstallation.com/data/.ocdata Failed to load resource: the server responded with a status of 403 (Forbidden)

The permissions for the file in question are **644** which means, if I am not mistaken, that it should be publicly readable.

**Comment by georgehrke** [comment]
Can't reproduce,
- [ ] what language do you use?

**Comment by georgehrke** [comment]
> This may or may not be related: When I open the admin panel, the JS console says:
> 
> > https://myowncloudinstallation.com/data/.ocdata Failed to load resource: the server responded with a status of 403 (Forbidden)

That's the intended behavior. It checks whether the directory with all your data is accessible from the web. Your web server seems to be configured correctly in this regard.

**Comment by georgehrke** [comment]
(can't reproduce neither with formal nor informal german)

**Comment by bildlich** [comment]
@georgehrke Formal german.

**Comment by georgehrke** [comment]
As said above, can't reproduce with neither german translation.

> undefined:1 Uncaught (in promise) INVALID_EVENT

Does the JS console display any file name and line number?

**Comment by bildlich** [comment]
@georgehrke 

> Does the JS console display any file name and line number?

Not in Chrome.

Firefox console says, on pageload:

> TypeError: events is undefined app.js:2209:24

The line in question is

```
VEventService.getAll(self, start, end).then(function(events) {
    var vevents = [];
    for (var i = 0; i < events.length; i++) { // <--- Line 2209 
```

**Comment by georgehrke** [comment]
WTF? events is empty?
(Besides that this error should properly be caught and displayed to the user) this looks like a server configuration issue to me.

**Comment by bildlich** [comment]
> this looks like a server configuration issue to me.

It almost certainly is. Where should I start looking for the root of the problem? I have included the .htaccess of the main installation folder in my second comment.

**Comment by georgehrke** [comment]
Please ask on the user-mailing list or the forum.

**Comment by bildlich** [comment]
I contacted my host who looked at the problem. He bumped the PHP version from 5.5 to 5.6. Now it works.

If someone with PHP 5.5 can reproduce the issue this may be a bug. If not this issue can be closed.

**Comment by georgehrke** [comment]
Okay, I think we can close this issue in that case.
