### ISSUE TITLE
Weird (shared) calendar issue(s)

### ISSUE THREAD

**Issue by disy-mk** [owncloud/calendar#680]
Hi,

currently I'm running OC 7.0.3 and am still waiting to resolve that issue before upgrading to 7.0.4.

I have 9 clients (c1-c9), and an account set up for each of them. These clients only use the calendar functionality of OC. 
There is also another calendar (n1), which all users share among and that is shared to the master account.

Each client account only contains 1 single calendar. This cal is also shared with a master account.
So I have a master account (m), which contains every of the 9 mentioned shared calendars (c1-c9) and the cal that all clients share (n1) - all are readonly shares.

I configured my iMac's calendar app to use the master account, which only is for planning purpose (readonly); now, my problem is, that only events for 8 of the 9 clients show up incalendar app (OSX): c1-c8. c9 only shows up in the webinterface, both, in c9's account and the master account.

Contrary to that, the events of the calendar n1 do show up in the OSX calendar app, but don't in OC's webinterface; neither in the master account, nor in the account of n1.

So i logged into the master account and saw, that all other 8 accounts are listed without the share icon, whereas the calendars cp and n1, had the share icon. I then checked the account of c9 to make sure it is only shared, but has no permission to be reshared (hope you know, what I mean).

However, the master account also shows the events of the problematic calendar.

I then tried to unshare that calendar within it's account. But the Calendar does not disappear in the master account. Only thing that changed: the share button (to reshare the cal) disappeared in the master account.

I checked my logs and found messages like:
```
Error	PHP	Call to a member function getAsString() on a non-object at /srv/www/cloud.inuvet.com/htdocs/apps/calendar/lib/object.php#542	2015-01-22T10:43:18+00:00
Error	vobject	Invalid VObject. Document ended prematurely.	2015-01-22T10:43:18+00:00
```
I then found this issue: owncloud/apps#687 (https://github.com/owncloud/apps/issues/687)

I enabled debug log level and that:

```
{"reqId":"54c0de4e42cf7","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:06+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de4e42cf7","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:06+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de5a52573","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-22T11:26:18+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54c0de6a74f6d","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:34+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de6a74f6d","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:34+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de6b9b982","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-22T11:26:35+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"54c0de775451d","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:47+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de775451d","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:47+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de827f83e","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:26:58+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de827f83e","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:26:58+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de8cb897b","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:08+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de8cb897b","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:27:08+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de97d2755","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:19+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0de97d2755","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:27:19+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0dea2babb6","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:30+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0dea2babb6","app":"PHP","message":"Call to a member function getAsString() on a non-object at \/srv\/www\/cloud.DOMAIN.com\/htdocs\/apps\/calendar\/lib\/object.php#542","level":3,"time":"2015-01-22T11:27:30+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
{"reqId":"54c0df0104804","app":"webdav","message":"Sabre\\DAV\\Exception\\NotAuthenticated: No basic authentication headers were found","level":0,"time":"2015-01-22T11:29:05+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
```
Unfortunately I still don't see the ID of the corresponding vobject.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.github.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
Hi,

can you please test the following patch (for ownCloud 7):
```
diff --git a/lib/object.php b/lib/object.php
index 4f63b7e..23771bb 100644
--- a/lib/object.php
+++ b/lib/object.php
@@ -539,6 +539,10 @@ class OC_Calendar_Object{
 	public static function getAccessClassPermissions($vobject) {
 		$velement = self::getElement($vobject);
 
+		if (!$velement) {
+			return 0;
+		}
+
 		$accessclass = $velement->getAsString('CLASS');
 
 		return OC_Calendar_App::getAccessClassPermissions($accessclass);
```

**Comment by georgehrke** [comment]
```
{"reqId":"54c0dea2babb6","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:30+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
``` 
just says, that some events are corrupted. But this should not break the interface nor caldav.

```
{"reqId":"54c0dea2babb6","app":"vobject","message":"Invalid VObject. Document ended prematurely.","level":3,"time":"2015-01-22T11:27:30+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/app\/EMPLOYEENAME(COMPANYNAME)_shared_by_mg\/"}
```
This one could actually break caldav, but should be fixed with the patch above.

**Comment by disy-mk** [comment]
OK, will test the patch tonight.
Any chance to the the exact id of the event causing this behavior?
I'd like to investigate the content of the corresponding event(s).

**Comment by georgehrke** [comment]
> Any chance to the the exact id of the event causing this behavior?
I'd like to investigate the content of the corresponding event(s).

Yes, I'll provide a patch that will generate more debug logs soon

**Comment by disy-mk** [comment]
>Yes, I'll provide a patch that will generate more debug logs soon
Great. I'd appreciate that. Really need to find out about the events, because my setup is used in a productive environment.

**Comment by georgehrke** [comment]
The following patch should log the id of the broken object when accessing it over caldav:
```
diff --git a/lib/sabre/backend.php b/lib/sabre/backend.php
index 98e27ad..e213d28 100644
--- a/lib/sabre/backend.php
+++ b/lib/sabre/backend.php
@@ -363,6 +363,7 @@ class OC_Connector_Sabre_CalDAV extends \Sabre\CalDAV\Backend\AbstractBackend {
 			$data = $this->OCAddETag($data);
 			$object = OC_VObject::parse($data['calendardata']);
 			if(!$object) {
+				\OCP\Util::writeLog('calendar-caldav', 'Could not parse event: ' . $calendarId . '::' . $objectUri, \OCP\Util::INFO);
 				return false;
 			}
 			$object = OC_Calendar_Object::cleanByAccessClass($data['id'], $object);
```

It outputs smth like: `Could not parse event: 1::bla.ics`
Now you have to take a look into the database. 
Go to the oc_clndr_objects table and search for the row with calendarid=1 and uri=bla.ics

**Comment by disy-mk** [comment]
>The following patch should log the id of the broken object when accessing it over caldav:

Thank you very much!
I'll be back :-)

**Comment by disy-mk** [comment]
I applied your patch but it does not change anything (no added output in logs). To circumvent confusion:
```
+               \OCP\Util::writeLog('calendar-caldav', 'Could not parse event: ' . $calendarId . '::' . $objectUri, \OCP\Util::INFO);
```
is what I'm talking about.
Is the patch you proposed prior to that mandatory for this one to add  additional info to the logs?

**Comment by georgehrke** [comment]
```
+               \OCP\Util::writeLog('calendar-caldav', 'Could not parse event: ' . $calendarId . '::' . $objectUri, \OCP\Util::INFO);
```
Is only for additional information. The other one was the actual fix.
What's the log level you set in the admin settings?

**Comment by disy-mk** [comment]
Ok, things are getting better :-)

Both patches applied.
Your first patch made the events of one of the both calendar to appear.

So, I'll recap the scenario again quickly:
2 problematic calendars we are talking about, ***c1*** and ***c2***.
(1)  both have separate accounts and are shared to the master account
(2)  ***c1***'s events do not show up in the webinterface, but do show up in OSX's calendar app
(3)  ***c2***'s events do show up in the webinterface, but do not show up in OSX's calendar app
(4)  I tried to unshare ***c2***, but it does not disappear in the master account (did not try with ***c1*** yet to have a reference. However, ***c1***'s options are set to disallow resharing. In the master account this specific cal has the share icon

You first patch did fix (3).
Your second patch also adds additional info. Apparently neither accessing the month view of of the webinterface, nor enabling/disabling the cal in OSX's cal app did trigger the log. When I went back by a month I got some useful info.
I do not access logs via webinterface; I watch owncloud.log and changed the config.php to:
```
[...]
  'loglevel' => '0',
[...]
```
I will now investigate the malicious vobject.
Thank you very much for your assistance!

**Comment by disy-mk** [comment]
Little update:
Your patch does not change anything in the webserver's behavior (which is fine, as all events except for the malicious one show up)
Another thing I just observed while using the search bar to search for the name, which is part of the title of the event, triggers following output for every letter I add to complete the name:
```
{"reqId":"54c175e235207","app":"PHP","message":"Trying to get property of non-object at \/srv\/www\/cloud.inuvet.com\/htdocs\/apps\/calendar\/lib\/search.php#25","level":3,"time":"2015-01-22T22:12:50+00:00","method":"GET","url":"\/index.php\/search\/ajax\/search.php?query=rei"}
{"reqId":"54c175e235207","app":"PHP","message":"Trying to get property of non-object at \/srv\/www\/cloud.inuvet.com\/htdocs\/apps\/calendar\/lib\/search.php#26","level":3,"time":"2015-01-22T22:12:50+00:00","method":"GET","url":"\/index.php\/search\/ajax\/search.php?query=rei"}
{"reqId":"54c175e235207","app":"PHP","message":"Trying to get property of non-object at \/srv\/www\/cloud.inuvet.com\/htdocs\/apps\/calendar\/lib\/object.php#444","level":3,"time":"2015-01-22T22:12:50+00:00","method":"GET","url":"\/index.php\/search\/ajax\/search.php?query=rei"}
{"reqId":"54c175e235207","app":"PHP","message":"Trying to get property of non-object at \/srv\/www\/cloud.inuvet.com\/htdocs\/apps\/calendar\/lib\/object.php#447","level":3,"time":"2015-01-22T22:12:50+00:00","method":"GET","url":"\/index.php\/search\/ajax\/search.php?query=rei"}
{"reqId":"54c175e235207","app":"PHP","message":"__clone method called on non-object at \/srv\/www\/cloud.inuvet.com\/htdocs\/apps\/calendar\/lib\/object.php#447","level":3,"time":"2015-01-22T22:12:50+00:00","method":"GET","url":"\/index.php\/search\/ajax\/search.php?query=rei"}
```
At a first glance I did not see anything weird about that event. I will add another little patch which also gives me the output of a working event for a specific id. I guess spotting "something strange" is going to be easier this way. If I end up with no success I will anonymize and post the event data.

**Comment by disy-mk** [comment]
OK, took another event and compared both.

The malicious event seems to be missing some data.

E.g:

good event:
```
(1439,	36,	'VEVENT',	'2014-12-05 08:23:00',	'2014-12-05 08:23:00',	0,	'TITLE\nSUBTITLE',	
'BEGIN:VCALENDAR\r\nCALSCALE:GREGORIAN\r\nPRODID:-//Apple Inc.//iOS 8.1.1//EN\r\nVERSION:2.0\r\nX-CALENDARSERVER-ACCESS:PUBLIC\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Berlin\r\nBEGIN:DAYLIGHT\r\nDTSTART:19810329T020000\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nTZNAME:MESZ\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nDTSTART:19961027T030000\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nTZNAME:MEZ\r\nTZOFFSETFROM:+0200\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nCREATED:20141205T082315Z\r\nDESCRIPTION:Bla blee blee blee\r\nDTEND;TZID=Europe/Berlin:20141205T092312\r\nDTSTAMP:20141205T082339Z\r\nDTSTART;TZID=Europe/Berlin:20141205T092312\r\nLAST-MODIFIED:20141205T082338Z\r\nLOCATION:STREET. 99\\n-9999 CITY\r\nSEQUENCE:0\r\nSUMMARY:TITLE\\nSUBTITLE\r\nTRANSP:OPAQUE\r\nUID:2B29B167-3D57-4C99-BBD9-682A8F3AF4E1\r\nURL;VALUE=URI:10712\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n',	'2B29B167-3D57-4C99-BBD9-682A8F3AF4E1.ics',	1417767841),
```
and the bad event:
```
(1440,	36,	'VEVENT',	'2014-12-09 08:10:00',	'2014-12-09 08:40:00',	0,	'ANOTHERTITLE\nANOTHERSUBTITLE',	
'BEGIN:VCALENDAR\r\nCALSCALE:GREGORIAN\r\nPRODID:-//Apple Inc.//iOS 8.1.1//EN\r\nVERSION:2.0\r\nX-CALENDARSERVER-ACCESS:PUBLIC\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Berlin\r\nBEGIN:DAYLIGHT\r\nDTSTART:19810329T020000\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nTZNAME:MESZ\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nDTSTART:19961027T030000\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nTZNAME:MEZ\r\nTZOFFSETFROM:+0200\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nCREATED:20141205T082530Z\r\nDESCRIPTION:Ble bla bla bla ',	'B77A9A39-F272-447A-956E-7F945D27CEEE.ics',	1418123486);
```

So the malicious event lacks everything after DESCRIPTION (i.e. location etc.).
I will no try to find out how that could have happened.

**Comment by disy-mk** [comment]
**Latest hint:**

Just got a screenshot from the customer whose event was malicious.
There was this (weary face emoji)[http://www.emojibase.com/emoji/1f629/wearyface] 
![weary emoji](http://pix.iemoji.com/sbemojix2/0772.png)
at that that position in the string where the rest was cut off.

The whole event's note shows up in the customers iOS calendar app, as well as in my CRM app on that iPad.
So the problem occurs in the process of syncing to OC.

**Comment by disy-mk** [comment]
Long story short: MySQL actually IS capable of handling emojis; the only problem is that MySQL's utf8 is noch really a proper implementation of utf8. But there also is utf8mb4 which, used for the collation, solves the issue. Migration instructions can be found [here](https://mathiasbynens.be/notes/mysql-utf8mb4). Spotted the howto [here](http://pjambet.github.io/blog/emojis-and-mysql/)

**Comment by jugantner** [comment]
To find all the broken calendar items you can issue the following command in the (mysql) database:

SELECT * FROM `oc_clndr_objects` WHERE `calendardata` NOT LIKE '%END:VCALENDAR%';

I had the problem that sync with iOS devices and Lightning calendar plugin does not work anymore

**Comment by ctgcwiqc** [comment]
To expand on jugantner's comment

Back up the database so no harm if you destroy the file as you can recover the DB (which contains the error) from backup so that not all is lost.  I use sudo mysqldump --lock-tables -h localhost -u root -pPassword > /media/goflex/owncloud-sqlbkp_`date +"%Y%m%d"`.bak but you will need to change /media/goflex/ to a directory of your choice

jugantner said : 
SELECT * FROM oc_clndr_objects WHERE calendardata NOT LIKE '%END:VCALENDAR%';

I issued a command like this after aquiring the id of the offending entry:
DELETE from oc_clndr_objects where id=166;

Find the id as seen in my attached screenshot.  If you can't see if via web interface owncloud calendar then you can remove ofender from DB manually as shown above.

The offender, a smiley face emoticon that I converted from an email to a task.  The offender does not show up in my web interface calender (probably because it is a task and not an event).  

Hopefully this helps a novice find an answer that they can act on.  I did not know any of this until I found it on google.


![capture](https://cloud.githubusercontent.com/assets/7608993/8380052/5b61d806-1be9-11e5-8c84-9a6de6ef60b4.PNG)

**Comment by fnolting** [comment]
This thread just saved my life! I was wondering why my calendars wouldn't sync anymore and did some research. It turned out that I had an offending calendar event in my calendar (id=3) that prevented all calendars with id >=3 from syncing and all I saw in the logs was an "error 500" plus I couldn't export the calendar (threw some strange sabre exception). I was searching for hours and luckily stumbled upon this thread. I deleted the event manually via phpmyadmin and now everything's working like a charm. THANKS!

**Comment by hyteraph** [comment]
Thank you jugantner for solving this issue! You saved me A LOT OF TROUBLE! Luckily I found this topic...

**Comment by pvassalli** [comment]
Hi guys, I have a problem similar to yours but when I try the select I get the answer that no calendar event is broken:
```javascript
mysql> SELECT * FROM oc_clndr_objects WHERE calendardata NOT LIKE '%END:VCALENDAR%';
Empty set (0.43 sec)
```
So now, my interface is roundcube and when I try to invite someone to an event I get this error:
```javascript
==> /data/owncloud.log <==
{"reqId":"G6\/wqzoXyoFjquhvG1dl","remoteAddr":"x.x.x.x","app":"caldav","message":"Exception:{\"Message\":\"End of document reached prematurely\",\"Code\":0,\"Trace\":\"#0 /var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(102): Sabre\VObject\Parser\MimeDir->readLine()\\n#1 /var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php(63): Sabre\VObject\Parser\MimeDir->parseDocument()\\n#2 /var/www/owncloud/3rdparty/sabre/vobject/lib/Reader.php(44): Sabre\VObject\Parser\MimeDir->parse('', 0)\\n#3 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(723): Sabre\VObject\Reader::read('')\\n#4 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(236): Sabre\CalDAV\Plugin->freeBusyQueryReport(Object(DOMDocument))\\n#5 [internal function]: Sabre\CalDAV\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars/a.bec...')\\n#6 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(705): Sabre\Event\EventEmitter->emit('report', Array)\\n#8 [internal function]: Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#9 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:REPORT', Array)\\n#11 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#12 /var/www/owncloud/apps/calendar/appinfo/remote.php(57): Sabre\DAV\Server->exec()\\n#13 /var/www/owncloud/remote.php(132): require_once('/var/www/ownclo...')\\n#14 {main}\",\"File\":\"/var/www/owncloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-09-17T15:58:38+00:00"}
```
How can I solve that?
Does anybody can provide me a fix?
calendar version is 0.4.0.0 and oc version is 8.1.1

**Comment by pvassalli** [comment]
Note that after increasing my log level to debug, I've found out that:

```javascript
{"reqId":"Ey5sMz7ZNPlRemCuCe\/Z","remoteAddr":"x.x.x.x","app":"caldav","message":"Exception: {\"Message\":\"HTTP/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 /var/www/owncloud/lib/private/connector/sabre/auth.php(149): Sabre\DAV\Auth\Backend\AbstractBasic->authenticate(Object(Sabre\DAV\Server), 'ownCloud')\\n#1 /var/www/owncloud/lib/private/connector/sabre/auth.php(122): OC\Connector\Sabre\Auth->auth(Object(Sabre\DAV\Server), 'ownCloud')\\n#2 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php(118): OC\Connector\Sabre\Auth->authenticate(Object(Sabre\DAV\Server), 'ownCloud')\\n#3 [internal function]: Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#4 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(456): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\\n#6 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\\n#7 /var/www/owncloud/apps/calendar/appinfo/remote.php(57): Sabre\DAV\Server->exec()\\n#8 /var/www/owncloud/remote.php(132): require_once('/var/www/ownclo...')\\n#9 {main}\",\"File\":\"/var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-09-17T16:50:55+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/a.b%40mydomain.com\/personale"}
```
And so the main problem is "HTTP/1.1 401 No basic authentication headers were found"
I have tried out some solutions to issues related to that but no luck...
I've tried #18194 and #841 but no chance for me...

**Comment by gvde** [comment]
The "401 No basic authentication headers were found" is normal: the client first tries to connect without authentication, then receives the 401 and then tries with authentication.

If you check your web server access logs you'll see that the requests with 401 codes are immediately followed by another request for the same URI but with an authenticated user. So that's just how HTTP works... With a browser the 401 would indicate the browser to show that pop-up asking for username/password.

**Comment by pvassalli** [comment]
gvde: I've not found the request in the browser log regarding the authenticated user but I've followed once again the two hints and especially https://github.com/owncloud/core/pull/18194 resolved my issue.
I don't know why but it didn't apply.
Probably the cause of my problem is related to the fact that roundcube and owncloud are on different servers, so the solution is, once again, modify the apache conf, adding inthe virtualhost the following line:
```javascript
SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1
```
and it :tada: automagically :tada: solves the problem...

**Comment by stevleibelt** [comment]
@jugantner 

big thanks also from my side. This solves a lot of trouble on my side :).

**Comment by lingfish** [comment]
I'm confused. The workaround supplied here works, but this isn't a fix; it's a workaround.  I have to do this, on average, two times a week.  Do we not have an actual fix forthcoming?

Or is this down to @disy-mk comment about UTF-8 and MySQL?
