### ISSUE TITLE
Lost one out of 3 calendars for a user over upgrading to OC8

### ISSUE THREAD

**Issue by ometol** [owncloud/calendar#740]
Hi there,

See below what I initially wrote to user@owncloud.  First off, here's the filled out template I received from a Chris from Germany:

-----
### Steps to reproduce
1. Install owncloud 7.0.4
2. Let a user have a couple of calendars, 3 in my case
3. Upgrade to owncloud 8.0.0
4. Enable both Calendars and Contacts app
(This is what I did, I have not tested reproducibility)
(Also, this installation started at a lower owncloud version.  I forgot which, but I have upgraded a couple of major versions)

### Expected behaviour
All calendars re-appear for all users after the upgrade

### Actual behaviour
One of the calendars for the user got lost

### Server configuration
**Operating system**: FreeBSD 10.1-RELEASE
**Web server**: apache24-2.4.12
**Database**: mysql55-server-5.5.41
**PHP version**: (Also got upgraded in the same procedure)
+ before upgrade: 5.4.35
+ after upgrade: 5.6.6
**ownCloud version**: (see ownCloud admin page)
+ before upgrade: 7.0.4
+ after upgrade: 8.0.0

**List of activated apps**:
+ Calendar
+ Contacts

**The content of config/config.php**:
```
$CONFIG = array (
  'datadirectory' => '/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.0.7',
  'installedat' => '1337811607.9756',
  'lastupdatedat' => '1338413281.9114',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '<hidden>',
  'installed' => true,
  'instanceid' => '50ec873a26cb6',
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => '<my-hostname>',
  ),
  'secret' => '<hidden>',
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
Same for every client.  caldav or web.  Actually grepping for known entries gives results in a backup of the database from before the upgrade but not in a backup from the current version.

#### ownCloud log (data/owncloud.log)
```
Logs that have arrived during and since the upgrade:
{"reqId":"1f9d70585ee77f10606aedeaf0bf3772","remoteAddr":"2001:67c:2e8:110:5576:9796:3590:f2a7","app":"index","message":"Exception: {\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php(77): OC_App::loadApp('files_sharing')\\n#1 \\\/www\\\/owncloud\\\/lib\\\/private\\\/util.php(75): OC_App::loadApps(Array)\\n#2 \\\/www\\\/owncloud\\\/lib\\\/base.php(762): OC_Util::setupFS()\\n#3 \\\/www\\\/owncloud\\\/index.php(36): OC::handleRequest()\\n#4 {main}\",\"File\":\"\\\/www\\\/owncloud\\\/lib\\\/private\\\/app.php\",\"Line\":96}","level":4,"time":"2015-02-27T09:35:49+00:00"}
{"reqId":"0f46dc690c3dba852152af86672d10f2","remoteAddr":"2001:67c:2e8:110:5576:9796:3590:f2a7","app":"PHP","message":"require_once(\/appinfo\/remote.php): failed to open stream: No such file or directory at \/www\/owncloud\/remote.php#54","level":3,"time":"2015-02-27T09:38:33+00:00"}
{"reqId":"0f46dc690c3dba852152af86672d10f2","remoteAddr":"2001:67c:2e8:110:5576:9796:3590:f2a7","app":"PHP","message":"require_once(): Failed opening required '\/appinfo\/remote.php' (include_path='\/www\/owncloud\/3rdparty\/phpseclib\/phpseclib\/phpseclib:\/www\/owncloud\/3rdparty\/pear\/pear_exception:\/www\/owncloud\/3rdparty\/pear\/archive_tar:\/www\/owncloud\/lib\/private:\/www\/owncloud\/config:\/www\/owncloud\/3rdparty:\/www\/owncloud\/apps:\/www\/owncloud\/lib:.:\/usr\/local\/share\/pear:\/www\/owncloud') at \/www\/owncloud\/remote.php#54","level":3,"time":"2015-02-27T09:38:33+00:00"}
```
-----

This is what I wrote before to user@owncloud.org:
-----
Hi there,

Yesterday (27/02/2015) I upgraded my owncloud installation from version
7.0.4 to 8.0.0.  This all looked like it was completely successful until
I noticed one of the three calendars I have under my user account went
missing.

Grepping for the entries I know the calendar has do appear in the
backup from the database from before the upgrade but not in the backup
from todays version.

Can you tell me:
- what information you would like to know
- How I can restore "1 of the 3 calendars" for an existing user from a
 backup of the mysql database where the backup is an old version of
 owncloud.  I don't mind a bit of handwork to get this done and know
 my way around computers/databases.

Thanks in advance!
------

**Comment by georgehrke** [comment]
Can you see the lost calendar in the oc_clndr_calendars table?

**Comment by ometol** [comment]
Hi, thanks for your question.  So when I issue the following SQL statement both in a backup from the old version and the current version I get the results shown.  The lost calendar is "menm" from user "menm":

Database backup result:
mysql> select userid,displayname from oc_clndr_calendars where userid = 'menm';
+--------+-------------+
| userid | displayname |
+--------+-------------+
| menm   | Marco       |
| menm   | Monique     |
| menm   | menm        |
+--------+-------------+
3 rows in set (0.00 sec)

Current database result:
mysql> select userid,displayname from oc_clndr_calendars where userid = 'menm';
+--------+-------------+
| userid | displayname |
+--------+-------------+
| menm   | Marco       |
| menm   | Monique     |
+--------+-------------+
2 rows in set (0.00 sec)

**Comment by georgehrke** [comment]
Ok, so it was actually deleted for some reason. Was there something special for the calendar menm? Like was it shared and the other's don't?

To restore it:
- insert the missing row into oc_clndr_calendars (current database).
- query for all objects in oc_clndr_objects (backup) where calendarid equals the id of the calendar row.
- insert those objects into  oc_clndr_objects (current database).
- If the restored calendar has a new id in the current database, replace the old calendarids in the oc_clndr_object table with the new one (current database)

**Comment by ometol** [comment]
Hi, unfortunately I do not know off the top of my head if there was anything special with the "menm" calendar except that it is identical to the userid.   It's been around for a long time.  The way I currently "share" it is that both my wife and myself login with userid menm when using caldav clients.  Long story. :)

I actually did a restore of the backup database into another database so I can query it for whatever you would like to know.

Thank you very much for providing the restore instructions.  Much appreciated!
I will try them and close the issue after being successful.  Unless you would like to keep it open.

**Comment by ometol** [comment]
I have been successful and will wait until tomorrow until closing the issue.  If you need any information to try and find out what happened please do let me know.  Thank you very much!
