### ISSUE TITLE
Unusable calendar after update to oC 10

### ISSUE THREAD

**Issue by cangeeq** [owncloud/calendar#799]
### Steps to reproduce
1. Unclear; suspect there is something bad in the calendar that the new version doesn't like

### Expected behaviour
Normal use of a calendar that was working in oC 9

### Actual behaviour
After upgrade to oC 10, one of my calendars never displays. Attempting to download it causes an error, so unfortunately I am unable to narrow down the cause:

```
ownCloud

Internal Server Error

Technical details

Remote Address: 192.168.2.2
Request ID: rtwm5OuhiM1T2UpUispg
ownCloud – web services under your control
```
### Server configuration
**Operating system**: FreeBSD 10

**Web server:** Apache 2.4

**Database:** SQLite

**PHP version:** 5.6.30

**Server version:** 10.0.1.5

**Calendar version:** 1.4.2

**Updated from an older installed version or fresh install:** Updated

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- bookmarks
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.
- notes
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [bookmarks] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

    [notes] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.4
  - bookmarks: 0.9.0
  - calendar: 1.4.2
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.2
  - dav: 0.2.9
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.7.0
  - files_pdfviewer: 0.8.2
  - files_sharing: 0.10.0
  - files_texteditor: 2.2
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 16.0.2
  - market: 0.1.0
  - notes: 2.0.2
  - notifications: 0.3.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - theme-example
  - user_external
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "5149063f4f2c5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/usr\/local\/www\/owncloud\/data",
        "dbtype": "sqlite3",
        "version": "10.0.1.5",
        "installed": true,
        "loglevel": 0,
        "log_authfailip": true,
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "trusted_domains": [
            "web.weirdways.com"
        ],
        "mail_domain": "weirdways.com",
        "mail_smtpmode": "php",
        "mail_from_address": "webmaster",
        "overwritewebroot": "\/cloud",
        "overwrite.cli.url": "\/cloud",
        "preview_libreoffice_path": "\/usr\/local\/bin\/openoffice-4.1.1",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/cloud",
        "appstore.experimental.enabled": true
    }
}
```

**Are you using external storage, if yes which one:** N/A

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

#### LDAP configuration (delete this part if not used)
N/A

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:** Windows 7, Ubuntu 16.04

**CalDAV-clients:**

#### Web server error log
```
192.168.2.2 - - [26/May/2017:15:10:11 -0400] "GET /cloud/index.php/apps/calendar
/ HTTP/1.1" 200 56681
192.168.2.2 - - [26/May/2017:15:10:12 -0400] "GET /cloud/index.php/core/js/oc.js
?v=d84bebc7673d9577313d91bb5b8a4be6 HTTP/1.1" 200 3156
192.168.2.2 - - [26/May/2017:15:10:12 -0400] "GET /cloud/index.php/avatar/john/3
2 HTTP/1.1" 200 1031
192.168.2.2 - - [26/May/2017:15:10:12 -0400] "GET /cloud/ocs/v2.php/apps/notific
ations/api/v1/notifications?format=json HTTP/1.1" 200 74
192.168.2.2 - - [26/May/2017:15:10:13 -0400] "PROPFIND /cloud/remote.php/dav HTT
P/1.1" 207 518
192.168.2.2 - - [26/May/2017:15:10:13 -0400] "GET /cloud/index.php/apps/calendar
/v1/timezones/AMERICA/NEW_YORK.ics HTTP/1.1" 200 359
192.168.2.2 - - [26/May/2017:15:10:13 -0400] "POST /cloud/index.php/apps/calenda
r/v1/config HTTP/1.1" 200 2
192.168.2.2 - - [26/May/2017:15:10:13 -0400] "PROPFIND /cloud/remote.php/dav/pri
ncipals/users/john/ HTTP/1.1" 207 527
192.168.2.2 - - [26/May/2017:15:10:14 -0400] "PROPFIND /cloud/remote.php/dav/calendars/john/ HTTP/1.1" 207 14311
192.168.2.2 - - [26/May/2017:15:10:14 -0400] "REPORT /cloud/remote.php/dav/calendars/john/birthdaysetc/ HTTP/1.1" 207 3049
192.168.2.2 - - [26/May/2017:15:10:14 -0400] "REPORT /cloud/remote.php/dav/calendars/john/defaultcalendar/ HTTP/1.1" 207 3580
192.168.2.2 - - [26/May/2017:15:10:14 -0400] "REPORT /cloud/remote.php/dav/calendars/john/contact_birthdays/ HTTP/1.1" 207 247
192.168.2.2 - - [26/May/2017:15:10:14 -0400] "REPORT /cloud/remote.php/dav/calendars/john/archive/ HTTP/1.1" 207 7326
192.168.2.1 - - [26/May/2017:15:10:25 -0400] "POST /mail/?_task=mail&_action=refresh HTTP/1.1" 200 109
192.168.2.2 - - [26/May/2017:15:10:41 -0400] "POST /news/backend.php HTTP/1.1" 200 156
192.168.2.2 - - [26/May/2017:15:10:42 -0400] "GET /cloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
192.168.2.2 - - [26/May/2017:15:10:52 -0400] "POST /mail/?_task=mail&_action=refresh HTTP/1.1" 200 109
192.168.2.2 - - [26/May/2017:15:11:11 -0400] "GET /cloud/remote.php/dav/calendars/john/joint?export HTTP/1.1" 500 8078
192.168.2.2 - - [26/May/2017:15:11:12 -0400] "GET /cloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
```

#### Log file (data/owncloud.log)
```
{"reqId":"rtwm5OuhiM1T2UpUispg","level":4,"time":"2017-05-26T19:11:12+00:00","remoteAddr":"192.168.2.2","user":"john","app":"webdav","method":"GET","url":"\/cloud\/remote.php\/dav\/calendars\/john\/joint?export","message":"Exception: {\"Message\":\"Unsupported VALUE parameter for DTEND property. You supplied \\\"\\\"\",\"Exception\":\"Sabre\\\\VObject\\\\InvalidDataException\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(453): Sabre\\\\VObject\\\\Document->createProperty('DTEND', NULL, Array)\\n#1 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('DTEND;VALUE=:20...')\\n#2 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(217): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;VALUE=:20...')\\n#3 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#4 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#5 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#6 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/ICSExportPlugin.php(307): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#7 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/ICSExportPlugin.php(225): Sabre\\\\CalDAV\\\\ICSExportPlugin->mergeObjects(Array, Array)\\n#8 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/ICSExportPlugin.php(151): Sabre\\\\CalDAV\\\\ICSExportPlugin->generateResponse('calendars\\\/john\\\/...', NULL, NULL, false, false, 'text\\\/calendar', Array, Object(Sabre\\\\HTTP\\\\Response))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\ICSExportPlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#12 \\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/usr\\\/local\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(229): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/usr\\\/local\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(31): OCA\\\\DAV\\\\Server->exec()\\n#15 \\\/usr\\\/local\\\/www\\\/owncloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#16 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/owncloud\\\/lib\\\/composer\\\/sabre\\\/vobject\\\/lib\\\/Document.php\",\"Line\":220,\"User\":\"john\"}"}
```

#### Browser log
No errors in the Console log

**Comment by DeepDiver1975** [comment]
Looks like there is invalid data in that specific calendar. Let me think about this if there is a way to heal the data.

**Comment by cangeeq** [comment]
I'm not a SQL expert but if you have suggestions about what to look for in the database I can poke around.

**Comment by ghost** [comment]
> Unsupported VALUE parameter for DTEND property. You supplied \"\"

Similar reported here as well: https://github.com/owncloud/core/issues/28114

**Comment by PeterPablo** [comment]
This issue affects me as well. I just upgraded to owncloud-files (10.0.3-1.1) from (9.1.6-1.1).

**Comment by ghost** [comment]
Closing as a duplicate of https://github.com/owncloud/calendar/issues/805

The issue here is older but #805 has quite more info and instructions how to fix the broken events in the database: https://github.com/owncloud/calendar/issues/805#issuecomment-331745533

*Edit* There is https://github.com/owncloud/core/issues/28114 as well which seems to handle the issue itself.
