### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by TrapperPhD** [owncloud/calendar#834]
### Steps to reproduce
1. update of calendar app to v1.5.4
2. logout owncloud, restart apache2, login to owncloud
3. click on "Calendar" in the Apps menu

### Expected behaviour
Owncloud calendar view opens.

### Actual behaviour
Broswer shows server error message ...
```
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
```

### Server configuration

**Operating system**: Ubuntu 14.04.1

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.6

**ownCloud version:** 9.1.4

**Calendar version:** 1.5.4

**Updated from an older installed version or fresh install:** calendar app recently updated from inside owncloud webinterface

**List of activated apps:**
  - calendar: 1.5.4
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.3
  - dav: 0.2.7
  - encryption: 1.3.0
  - external: 1.2
  - federatedfilesharing: 0.3.0
  - files: 1.5.1
  - files_antivirus: 0.9.0.0
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - templateeditor: 0.1
  - user_external: 0.4

**ownCloud configuration:**
> {
>     "system": {
>         "instanceid": "oc3a41047555",
>         "passwordsalt": "***REMOVED SENSITIVE VALUE***",
>         "trusted_domains": [
>             "***REMOVED SENSITIVE VALUE***",
>             "localhost",
>             "***REMOVED SENSITIVE VALUE***"
>         ],
>         "datadirectory": "\/var\/www\/owncloud\/data",
>         "dbtype": "mysql",
>         "dbname": "owncloud",
>         "version": "9.1.4.2",
>         "installed": true,
>         "has_internet_connection": true,
>         "forcessl": true,
>         "memcache.local": "\\OC\\Memcache\\APCu",
>         "filelocking.enabled": true,
>         "memcache.locking": "\\OC\\Memcache\\Redis",
>         "redis": {
>             "host": "\/var\/run\/redis\/redis.sock",
>             "port": 0,
>             "timeout": 0,
>             "password": "***REMOVED SENSITIVE VALUE***"
>         },
>         "maintenance": false,
>         "updatechecker": false,
>         "upgrade.disable-web": false,
>         "mail_from_address": "postmaster",
>         "mail_smtpmode": "smtp",
>         "mail_smtphost": "localhost",
>         "mail_domain": "***REMOVED SENSITIVE VALUE***",
>         "loglevel": 0,
>         "secret": "***REMOVED SENSITIVE VALUE***",
>         "forceSSLforSubdomains": true,
>         "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
>         "xframe_restriction": false,
>         "defaultapp": "files",
>         "default_language": "de",
>         "appstoreenabled": true,
>         "appstoreurl": "https:\/\/marketplace.owncloud.com\/api\/v0",
>         "appstore.experimental.enabled": true,
>         "appcodechecker": false,
>         "check_for_working_webdav": true,
>         "check_for_working_htaccess": true,
>         "cache_path": "",
>         "quota_include_external_storage": false,
>         "filesystem_check_changes": 1,
>         "enable_avatars": true,
>         "theme": "",
>         "dbhost": "127.0.0.1",
>         "dbuser": "***REMOVED SENSITIVE VALUE***",
>         "dbpassword": "***REMOVED SENSITIVE VALUE***",
>         "asset-pipeline.enabled": true,
>         "trashbin_retention_obligation": "auto",
>         "integrity.check.disabled": false,
>         "enable_previews": true,
>         "debug": false,
>         "knowledgebaseenabled": true,
>         "preview_libreoffice_path": "\/usr\/bin\/libreoffice"
>     }
> }

**Are you using external storage, if yes which one:** Local & Samba

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome v62.0.3202.94 64bit

**Operating system:** Windows 8

**CalDAV-clients:** Thunderbird Lightning app, Android CalDav Sync (0.4.32)app

#### Web server error log
```[Mon Dec 04 08:00:24.031941 2017] [mpm_prefork:notice] [pid 3233] AH00163: Apache/2.4.20 (Ubuntu) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Dec 04 08:00:24.031986 2017] [core:notice] [pid 3233] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 04 09:24:11.497568 2017] [mpm_prefork:notice] [pid 3233] AH00169: caught SIGTERM, shutting down
[Mon Dec 04 09:24:13.203528 2017] [mpm_prefork:notice] [pid 308] AH00163: Apache/2.4.20 (Ubuntu) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Dec 04 09:24:13.203603 2017] [core:notice] [pid 308] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 04 09:24:38.483450 2017] [mpm_prefork:notice] [pid 308] AH00169: caught SIGTERM, shutting down
[Mon Dec 04 09:27:11.335859 2017] [mpm_prefork:notice] [pid 3287] AH00163: Apache/2.4.20 (Ubuntu) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Dec 04 09:27:11.380033 2017] [core:notice] [pid 3287] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 04 11:37:35.123566 2017] [mpm_prefork:notice] [pid 3287] AH00169: caught SIGTERM, shutting down
[Mon Dec 04 11:37:36.224041 2017] [mpm_prefork:notice] [pid 8438] AH00163: Apache/2.4.20 (Ubuntu) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Dec 04 11:37:36.224137 2017] [core:notice] [pid 8438] AH00094: Command line: '/usr/sbin/apache2'
[Mon Dec 04 11:49:34.445687 2017] [access_compat:error] [pid 8441] [client 212.27.185.253:14308] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Mon Dec 04 12:24:51.231505 2017] [access_compat:error] [pid 8831] [client 212.27.185.253:11594] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
[Mon Dec 04 12:42:49.904242 2017] [:error] [pid 9958] [client 149.172.47.132:41405] script '/var/www/groupdav.php' not found or unable to stat
[Mon Dec 04 12:42:49.982251 2017] [:error] [pid 9958] [client 149.172.47.132:41405] script '/var/www/remote.php' not found or unable to stat
```

### Log file (data/owncloud.log)
```{"reqId":"B+umUX1YLHfI9e0NWhXp","remoteAddr":"212.27.185.253","app":"core","message":"Generating preview for \"\/Akademie\/10 Steps to Happiness.jpeg\" with \"OC\\Preview\\JPEG\"","level":0,"time":"2017-12-04T10:38:35+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2FAkademie%2F10+Steps+to+Happiness.jpeg&c=73bd4e4cad6d51a3c17c127400847787&x=32&y=32&forceIcon=0","user":"cve"}
{"reqId":"B+umUX1YLHfI9e0NWhXp","remoteAddr":"212.27.185.253","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-12-04T10:38:35+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2FAkademie%2F10+Steps+to+Happiness.jpeg&c=73bd4e4cad6d51a3c17c127400847787&x=32&y=32&forceIcon=0","user":"cve"}
{"reqId":"Ar2+K5YGH8j4D+0B+iKm","remoteAddr":"212.27.185.253","app":"no app in context","message":"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.","level":3,"time":"2017-12-04T10:38:47+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/Akademie\/Fotografie\/Naturaufnahmen%20im%20Nebel.CHIP%2011-2015.pdf","user":"cve"}
{"reqId":"Ar2+K5YGH8j4D+0B+iKm","remoteAddr":"212.27.185.253","app":"webdav","message":"Exception: {\"Message\":\"Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you.\",\"Exception\":\"OC\\\\Encryption\\\\Exceptions\\\\DecryptionFailedException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('kAKKQdnELMv0jnB...', 0)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#2 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #78, 8192)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#5 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #81, Resource id #85, '666248')\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php\",\"Line\":360,\"User\":\"cve\"}","level":4,"time":"2017-12-04T10:38:47+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/Akademie\/Fotografie\/Naturaufnahmen%20im%20Nebel.CHIP%2011-2015.pdf","user":"cve"}
{"reqId":"vlvtYjJLtiiLJ93o3HCe","remoteAddr":"212.27.185.253","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/vendor\/autosize\/dist\/autosize.js\"","level":3,"time":"2017-12-04T10:39:16+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"cve"}
{"reqId":"vlvtYjJLtiiLJ93o3HCe","remoteAddr":"212.27.185.253","app":"index","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/js\\\/vendor\\\/autosize\\\/dist\\\/autosize.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(232): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(143): OC\\\\TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\TemplateLayout->__construct('user', 'calendar')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Calendar\\\\Controller\\\\ViewController), 'index')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/')\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":3,"time":"2017-12-04T10:39:33+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"cve"}
{"reqId":"vlvtYjJLtiiLJ93o3HCe","remoteAddr":"212.27.185.253","app":"calendar","message":"Could not find resource file \"\/owncloud\/apps\/calendar\/js\/vendor\/autosize\/dist\/autosize.js\"","level":3,"time":"2017-12-04T10:39:33+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"cve"}
{"reqId":"vlvtYjJLtiiLJ93o3HCe","remoteAddr":"212.27.185.253","app":"core","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/js\\\/vendor\\\/autosize\\\/dist\\\/autosize.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(232): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(143): OC\\\\TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\TemplateLayout->__construct('user', 'calendar')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(156): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(112): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(99): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Calendar\\\\Controller\\\\ViewController), 'index')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#10 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(280): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(891): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/')\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":3,"time":"2017-12-04T10:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"cve"}
{"reqId":"vlvtYjJLtiiLJ93o3HCe","remoteAddr":"212.27.185.253","app":"core","message":"Exception: {\"Exception\":\"RuntimeException\",\"Message\":\"The source file \\\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/js\\\/vendor\\\/autosize\\\/dist\\\/autosize.js\\\" does not exist.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/BaseAsset.php(103): Assetic\\\\Asset\\\\FileAsset->load()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/AssetCollection.php(151): Assetic\\\\Asset\\\\BaseAsset->dump(NULL)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/AssetWriter.php(68): Assetic\\\\Asset\\\\AssetCollection->dump()\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(232): Assetic\\\\AssetWriter->writeAsset(Object(Assetic\\\\Asset\\\\AssetCollection))\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/TemplateLayout.php(143): OC\\\\TemplateLayout->generateAssets()\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(229): OC\\\\TemplateLayout->__construct('error', '')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Template\\\/Base.php(129): OC_Template->fetchPage()\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(361): OC\\\\Template\\\\Base->printPage()\\n#8 \\\/var\\\/www\\\/owncloud\\\/index.php(73): OC_Template::printExceptionErrorPage(Object(RuntimeException))\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/kriswallsmith\\\/assetic\\\/src\\\/Assetic\\\/Asset\\\/FileAsset.php\",\"Line\":62}","level":3,"time":"2017-12-04T10:39:51+00:00","method":"GET","url":"\/owncloud\/index.php\/apps\/calendar\/","user":"cve"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","level":1,"time":"2017-12-04T10:45:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","level":1,"time":"2017-12-04T10:45:02+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\ScanFiles job with ID 3202","level":0,"time":"2017-12-04T10:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\ScanFiles job with ID 3202","level":0,"time":"2017-12-04T10:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2860","level":0,"time":"2017-12-04T10:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2860","level":0,"time":"2017-12-04T10:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2861","level":0,"time":"2017-12-04T10:45:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2861","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3180","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3180","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3181","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3181","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 2","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3183","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\BackgroundJob\\Legacy\\RegularJob job with ID 3183","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 3203","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 3203","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 3204","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 3204","level":0,"time":"2017-12-04T10:45:04+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 3206","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash job with ID 3206","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 3207","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OCA\\Files_Versions\\BackgroundJob\\ExpireVersions job with ID 3207","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 3208","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"no app in context","message":"Invalidating tokens older than 2017-12-03T10:45:05+00:00","level":1,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 3208","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Run OCA\\DAV\\CardDAV\\SyncJob job with ID 3200","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"WZ7+cOQe7xNwG9rL5NrV","remoteAddr":"","app":"cron","message":"Finished OCA\\DAV\\CardDAV\\SyncJob job with ID 3200","level":0,"time":"2017-12-04T10:45:05+00:00","method":"--","url":"--","user":"--"}
{"reqId":"SyGL8XNUAuNP8lGqJQGa","remoteAddr":"212.27.185.253","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-12-04T10:45:44+00:00","method":"POST","url":"\/owncloud\/index.php\/login","user":"--"}
{"reqId":"j6UUc9Cvq2pb0r7yEyIj","remoteAddr":"212.27.185.253","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-12-04T10:46:14+00:00","method":"POST","url":"\/owncloud\/index.php\/login","user":"--"}
{"reqId":"VvGyrFbS7JdDQOluxcnv","remoteAddr":"212.27.185.253","app":"core","message":"Generating preview for \"\/largecover.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2017-12-04T10:47:08+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Flargecover.png&c=d747784f645d9e93a2f9d5e515d8136a&x=32&y=32&forceIcon=0","user":"Administrator"}
{"reqId":"VvGyrFbS7JdDQOluxcnv","remoteAddr":"212.27.185.253","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2017-12-04T10:47:08+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Flargecover.png&c=d747784f645d9e93a2f9d5e515d8136a&x=32&y=32&forceIcon=0","user":"Administrator"}
{"reqId":"VvGyrFbS7JdDQOluxcnv","remoteAddr":"212.27.185.253","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2017-12-04T10:47:08+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Flargecover.png&c=d747784f645d9e93a2f9d5e515d8136a&x=32&y=32&forceIcon=0","user":"Administrator"}
{"reqId":"5YKsON+vjsIYJ+0kCXrh","remoteAddr":"212.27.185.253","app":"core","message":"Generating preview for \"\/largecover.png\" with \"OC\\Preview\\PNG\"","level":0,"time":"2017-12-04T10:49:04+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Flargecover.png&c=d747784f645d9e93a2f9d5e515d8136a&x=32&y=32&forceIcon=0","user":"Administrator"}
{"reqId":"5YKsON+vjsIYJ+0kCXrh","remoteAddr":"212.27.185.253","app":"core","message":"OC_Image->fixOrientation() Image is not a JPEG.","level":0,"time":"2017-12-04T10:49:04+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Flargecover.png&c=d747784f645d9e93a2f9d5e515d8136a&x=32&y=32&forceIcon=0","user":"Administrator"}
{"reqId":"5YKsON+vjsIYJ+0kCXrh","remoteAddr":"212.27.185.253","app":"core","message":"OC_Image->fixOrientation() Orientation: -1","level":0,"time":"2017-12-04T10:49:04+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2Flargecover.png&c=d747784f645d9e93a2f9d5e515d8136a&x=32&y=32&forceIcon=0","user":"Administrator"}
```

**Comment by TrapperPhD** [comment]
Just to be complete ... "sudo -u www-data php occ maintenance:repair" had fixed classification fir calendar objects, ...

but issue is still there.

BR
CV

**Comment by TrapperPhD** [comment]
After deactivating apps, upgrade to oc 10.0.3, and install calendar app from market place, everything seems to work fine.

Closing issue.

Best
CV
