### ISSUE TITLE
Can't activate Calendar properly

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/calendar#848]
### Steps to reproduce
1. Upgrade from 8.0 to 8.1
2. Notice that the Calendar app is missing
3. Install the Calendar app by downloading it from the AppStore and copying it in the `apps` directory (that was the only solution I knew at the time)
4. See that it's experimental and that is weird...
5. Find out that the app is already in the Productivity section
6. Remove the `calendar` directory in the `apps` directory
7. Activate the official (i.e. green) Calendar app in the Productivity section  
![capture d ecran de 2015-07-11 17-27-39](https://cloud.githubusercontent.com/assets/6382548/8635489/6b39b2ac-27f2-11e5-8cf8-dcbc8086c387.png)
8. In the Activated section, see that it is still flagged experimental (isn't it official? I guess that if it's official it shouldn't be experimental)  
![capture d ecran de 2015-07-11 17-30-10](https://cloud.githubusercontent.com/assets/6382548/8635498/d5e93a82-27f2-11e5-8f6f-e964c533e57e.png)
9. In the Productivity section, see that you can still activate the app (same screenshot as for the first bullet).

### Expected behaviour
If the Calendar app is flagged "Official", I assume it's not experimental. So it should still have the green "Official" flag once you activated it.

### Actual behaviour
The Calendar app is flagged "Experimental".

### Server configuration
**Operating system**: Debian 8.1

**Web server:** nginx 1.6.2

**Database:** mysql 5.5.43

**PHP version:** 5.6.7

**ownCloud version:** 8.1.0

**Updated from an older ownCloud or fresh install:** From and older ownCloud (8.0)

**List of activated apps:**

```
Enabled:
 - activity: 2.0.1
 - calendar: 0.7.2
 - contacts: 0.4.0.0
 - documents: 0.10.0
 - files: 1.1.9
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - tasks: 0.7.1
 - templateeditor: 0.1
Disabled:
 - encryption
 - external
 - files_external
 - files_locking
 - music
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
sudo -u www-data php occ config:list system --public
                                                            
  [InvalidArgumentException]                                
  There are no commands defined in the "config" namespace.  

```

???

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 38.0.5

**Operating system:** Fedora 22

#### Web server error log
Nothing interesting regarding calendar. The errors are from previous tests I was doing.

```
2015/07/11 22:20:54 [error] 21985#0: *68 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.222.172.139, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/settings/apps"
2015/07/11 22:22:13 [error] 21985#0: *89 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.222.172.139, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/apps/files/"
2015/07/11 22:31:44 [error] 22291#0: *220 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 216.98.56.20, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/apps/files/?dir=~~private~~"
2015/07/11 22:32:54 [error] 22291#0: *228 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.222.172.139, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/settings/apps"
2015/07/11 22:34:13 [error] 22291#0: *252 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.222.172.139, server: cloud.foolstep.com, request: "POST /index.php/heartbeat HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.owncloud.sock:", host: "cloud.foolstep.com", referrer: "https://cloud.foolstep.com/index.php/apps/files/"
2015/07/11 23:04:15 [error] 24153#0: *678 directory index of "/var/www/owncloud/core/doc/user/pim/" is forbidden, client: 192.222.172.139, server: cloud.foolstep.com, request: "GET /core/doc/user/pim/ HTTP/1.1", host: "cloud.foolstep.com"
2015/07/11 23:04:28 [error] 24153#0: *678 directory index of "/var/www/owncloud/core/doc/" is forbidden, client: 192.222.172.139, server: cloud.foolstep.com, request: "GET /core/doc/ HTTP/1.1", host: "cloud.foolstep.com"
2015/07/11 23:04:36 [error] 24153#0: *678 directory index of "/var/www/owncloud/core/doc/" is forbidden, client: 192.222.172.139, server: cloud.foolstep.com, request: "GET /core/doc/ HTTP/1.1", host: "cloud.foolstep.com"
2015/07/11 23:04:43 [error] 24151#0: *709 directory index of "/var/www/owncloud/core/doc/" is forbidden, client: 192.222.172.139, server: cloud.foolstep.com, request: "GET /core/doc/ HTTP/1.1", host: "cloud.foolstep.com"
2015/07/11 23:40:50 [error] 24152#0: *1786 access forbidden by rule, client: 37.187.121.53, server: cloud.foolstep.com, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "cloud.foolstep.com"
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"e9VwZQK2psmeMwqsQndq","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":0,"time":"2015-07-11T21:41:54+00:00","method":"--","url":"--"}
{"reqId":"e9VwZQK2psmeMwqsQndq","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/documents\/appinfo\/app.php#49","level":0,"time":"2015-07-11T21:41:55+00:00","method":"--","url":"--"}
{"reqId":"J8FlOrwNl573rYlIR+ra","remoteAddr":"192.222.172.139","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-07-11T21:41:57+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"9dj3XtrpPHKNpXbzzl8J","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-11T21:42:20+00:00","method":"--","url":"--"}
{"reqId":"9dj3XtrpPHKNpXbzzl8J","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/documents\/appinfo\/app.php#49","level":3,"time":"2015-07-11T21:42:20+00:00","method":"--","url":"--"}
{"reqId":"gCYKiluSnjmYc74xTZIT","remoteAddr":"192.222.172.139","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(83): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-07-11T21:42:45+00:00","method":"PROPFIND","url":"\/remote.php\/webdav"}
{"reqId":"Skvs\/Aml+wWCoEghnRBX","remoteAddr":"216.98.56.20","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2015-07-11T21:43:44+00:00","method":"POST","url":"\/index.php\/heartbeat"}
{"reqId":"MXLAzcvCLBOF0ZtQc+YS","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/contacts\/appinfo\/app.php#35","level":3,"time":"2015-07-11T21:45:02+00:00","method":"--","url":"--"}
{"reqId":"MXLAzcvCLBOF0ZtQc+YS","remoteAddr":"","app":"PHP","message":"Undefined index: REQUEST_URI at \/var\/www\/owncloud\/apps\/documents\/appinfo\/app.php#49","level":3,"time":"2015-07-11T21:45:02+00:00","method":"--","url":"--"}
{"reqId":"MXLAzcvCLBOF0ZtQc+YS","remoteAddr":"","app":"core","message":"Sent mail to \"Array\n(\n    [~~private~~] => ~~private~~\n)\n\" with subject \"Activity notification\"","level":0,"time":"2015-07-11T21:45:02+00:00","method":"--","url":"--"}
```

**Comment by georgehrke** [comment]
That's because you downloaded it manually and didn't install it directly over the app store. => expected behavior

**Comment by MightyCreak** [comment]
Well... That's the first step... Right after I removed it and installed from the app store and it still doesn't work. That's why I opened an issue.

**Comment by MightyCreak** [comment]
@georgehrke I don't think this is the expected behavior considering I installed it from the appstore afterwards.

**Comment by georgehrke** [comment]
It's the expected behavior, that it's flagged as experimental, if you install it manually and not over the app store. That's the issue you described. Do you actually want to report something else?

**Comment by MightyCreak** [comment]
I understand that if I install it manually, it's flagged experimental, and I completely agree with this choice.

However, if I uninstall the app and reinstall it, but **using the app store** I don't think it's normal that the brand new, app store installed app is still flagged experimental. Is it?
