### ISSUE TITLE
Event sync broken after update to OC 8.1.0

### ISSUE THREAD

**Issue by Guite** [owncloud/calendar#855]
A user reported that he can not synchronise his shared calendars anymore. Using an iPhone the events are not displayed at all. Desktop clients report either that no events are available or the location is invalid.

The OC log shows the following:

```
Exception: {"Message":"This recurrence rule does not generate any valid instances","Code":0,"Trace":"
#0 \/...\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Component\/VEvent.php(33): Sabre\\VObject\\Recur\\EventIterator->__construct(Object(Sabre\\VObject\\Component\\VEvent))\n
#1 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(291): Sabre\\VObject\\Component\\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))\n
#2 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(79): Sabre\\CalDAV\\CalendarQueryValidator->validateTimeRange(Object(Sabre\\VObject\\Component\\VEvent), Object(DateTime), NULL)\n
#3 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(41): Sabre\\CalDAV\\CalendarQueryValidator->validateCompFilters(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n
#4 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(145): Sabre\\CalDAV\\CalendarQueryValidator->validate(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n
#5 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n
#6 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery('78', Array)\n
#7 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(621): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n
#8 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(231): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n
#9 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/joerg...')\n
#10 \/...\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#11 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n
#12 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#13 \/...\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
#14 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n
#15 \/...\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
#16 \/...\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n
#17 \/...\/owncloud\/remote.php(132): require_once('\/...\/...')\n
#18 {main}","File":"\/...\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Recur\/EventIterator.php","Line":199}
```

**Comment by RealRancor** [comment]
To make sure, are you running the latest version 0.7.2 of the calendar app?

**Comment by Guite** [comment]
Apps overview shows it is 0.7.0. Can I update it using the apps UI?

**Comment by RealRancor** [comment]
Normally you should get an "update to 0.7.2" button in the apps ui. At least i got one.

If not you could also download the oC 8.1 version from the appstore and put it manually into your apps folder.

**Comment by Guite** [comment]
Thanks, updated to 0.7.2 now. Going to report back after the user has tested again.

**Comment by RealRancor** [comment]
Hopefully that works for you as 0.7.2 provided an fix for shared calendars as well as for the principal-uris used by iOS:

https://github.com/owncloud/calendar/compare/v0.7.0...v0.7.2

**Comment by matt407** [comment]
I experienced this issue also. After update to 0.7.2 the sharing of calendars and tasks is working fine again.

**Comment by Guite** [comment]
Works here, too!

Thanks again.
