### ISSUE TITLE
Sync between Apple Devices not working

### ISSUE THREAD

**Issue by mehlkopf** [owncloud/calendar#857]
Hi,
I'm using Owncloud 8.1 with Calendar 0.7.1. Since the update (at least I assume this), it's not possible to properly sync the calendars. For example, I can add calendar entries in Apple Calendar on OS X 10.10, which are synced correctly to the server and appear in the web interface, but will never be synced to my iOS device. What's even more strange, when I unsync Apple Calendar and resync from Owncloud, the actual calendars all appear, but some of them are completely empty, although the entries are displayed correctly in the web interface. To be honest, that's a total mess!

The server throws these errors:
Exception: {"Message":"This recurrence rule does not generate any valid instances","Code":0,"Trace":"#0 \/var\/www\/oc\/3rdparty\/sabre\/vobject\/lib\/Component\/VEvent.php(33): Sabre\\VObject\\Recur\\EventIterator->__construct(Object(Sabre\\VObject\\Component\\VEvent))\n#1 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(291): Sabre\\VObject\\Component\\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))\n#2 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(79): Sabre\\CalDAV\\CalendarQueryValidator->validateTimeRange(Object(Sabre\\VObject\\Component\\VEvent), Object(DateTime), NULL)\n#3 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarQueryValidator.php(41): Sabre\\CalDAV\\CalendarQueryValidator->validateCompFilters(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n#4 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(145): Sabre\\CalDAV\\CalendarQueryValidator->validate(Object(Sabre\\VObject\\Component\\VCalendar), Array)\n#5 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n#6 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery('14', Array)\n#7 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(621): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n#8 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(231): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n#9 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/andre...')\n#10 \/var\/www\/oc\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n#12 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/var\/www\/oc\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#15 \/var\/www\/oc\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#16 \/var\/www\/oc\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#17 \/var\/www\/oc\/remote.php(132): require_once('\/var\/www\/oc\/app...')\n#18 {main}","File":"\/var\/www\/oc\/3rdparty\/sabre\/vobject\/lib\/Recur\/EventIterator.php","Line":199}

Thank you very much for your help!

**Comment by t-schmitz** [comment]
Seeing exactly the same behavior and log entries with OC 8.1.0 and Calendar 0.7.2 when syncing my iOS 8.4 devices.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

**Comment by mehlkopf** [comment]
Thank you for the information, I updated my original post!

**Comment by mehlkopf** [comment]
I updated the Calendar app to 0.7.2, problem remains.
Actually, after reading through the forums, it seems as though simply CalDAV does not work anymore with Owncloud 8.1. Is anybody working on this?! Owncloud without CalDAV sync is absolutely worthless to me!

**Comment by capnjb** [comment]
Same-o/Same-o
iOS8.4 was syncing perfectly with 6 clients prior to ownCloud update to 8.1...  now 4 of the clients/users get the positive "checks" that the device connected OK to the ownCloud box but does not update either post to or get from the calendar.  NOW for the weird part 1 user/client with 2 devices works.  What is unique about that user it is me and that login is an admin.  I plan to experiment with that tonight BUT all users can not  be admins.

Unlikely it is related but I also have the SMB share problem after the upgrade as well.  core #17499

Hope there are solutions soon because these items are key to the value of using ownCloud.

**Comment by HarrySTrueman** [comment]
Hi there,

maybe this problem is resolved by using the calendar plus app.
Has someone tested this behaviour with calendar plus, actual version 1.0.2?
https://apps.owncloud.com/content/show.php/Calendar+Plus?content=170560

**Comment by mehlkopf** [comment]
Yes, I gave it a try, it didn't change anything ...

**Comment by georgehrke** [comment]
How did you update from 8.0.4? What source do you use?

I can't reproduce this. works just fine for me

**Comment by georgehrke** [comment]
please post your nginx config

**Comment by migrax** [comment]
This pull request fixed the issue for me https://github.com/owncloud/3rdparty/pull/189

**Comment by arno1979** [comment]
@migrax Thanks for your effort and the link to the workaround. I tried it myself but I can't get the sync to work properly on my girlfriend's iPhone 5 and iPad mini.
In our case the affected calender is a calendar that belongs to me and is shared with her by me via my Owncloud installation (version 8.1.0-17.1).
Is it possible that a shared calendar might be affected differently than normal calendars?

**Comment by gvde** [comment]
@arno1979 Are you sure you have upgraded to calendar 0.7.2?

**Comment by arno1979** [comment]
@gvde Thanks for pointing that out! I just checked and: no, I didn't. Probably because I maintain my Owncloud installation using the packet manager yum on a Fedora box. As far as I know any update of the calendar plug-in would have to come from the repository, right?
Do you think I can just manually update the calendar plug-in to see if that would help?

**Comment by gvde** [comment]
@arno1979 If I am not mistaken the calendar app is not part of any rpm but only installed and upgraded from the owncloud app store...

**Comment by arno1979** [comment]
@gvde I never updated any apps manually in the past and I was on Calendar 0.7.1 so I guess the current version was simply not included in the rpm so far. I manually updated the app to 0.7.2 and sync seems to be working fine even without the workaround...

**Comment by nixnuex** [comment]
I confirm this issue. Calendar syncing seems to work with OS X 10.10.4 but with iOS 8.4 I have some problems (some calendars only synced from the device to the server but not the other way around). And the OC log shows the fatal error from the original post.

OC 8.1.0, Calendar App 0.7.2

**Comment by nixnuex** [comment]
Me back again. I now applied [migrax' patch](https://github.com/fruux/sabre-vobject/pull/249) to VEvent.php, that solved all my problems! No more sync issues, no more log messages! Thank you very much!

**Comment by mk-conn** [comment]
So, when does the PR make it into the calendar app?

**Comment by smat88** [comment]
Thank you nixnuex!
But why is the new, fixed sabre/dav not included in the latest owncloud 8.2 ? I still had to patch this manually in Owncloud 8.2
The fix dates back to august, Owncloud 8.2 was released before a few days, and now is almost end of october already...

**Comment by gerardbos** [comment]
I had the same problem on OwnCloud 8.2 with calendar 0.8.1. Applied [migrax' patch](https://github.com/fruux/sabre-vobject/pull/249) patch. Seems to be fixed.

**Comment by ulfstabe** [comment]
Hello all,

I am still having the same problem on OC 8.2.1 with Calendar 0.8.1.
I have the latest stable install and checked that the fix mentioned above (Event.php) is included.
Same picture. 
- Events added in OwnCloud or eg MacOSX Calendar sync back and forth
- no events are synced down to any iOS (iPad 8.4.1, iPhone 7.1)
- events created on iOS are synced up

Anyone else with this problem?

Only thing special is my OC cronjobs are not enabled.
No entries in owncloud.log.
No entries in Apache error.log
In my Apache access.log I can see the devices doing PROPFIND/PROPPATCH/REPORT request, although for requests from iOS a maximum of 4 calendars.

Can you give me a hint how to enable a debug output of requests and OC responses, maybe this will give some info.

**Comment by gvde** [comment]
> Can you give me a hint how to enable a debug output of requests and OC responses, maybe this will give some info.

Did you check the owncloud documentation? Chapter on "Issues and Troubleshooting"?

**Comment by ulfstabe** [comment]
@gvde yes, already on level ALL. Only the occasional "401 No basic authentication headers were found" which I think is normal for initial part of every new request. The following requests all get their 200 or 207 HTTP response code. what I was looking for is a way to log the XML request/response part.

**Comment by ulfstabe** [comment]
I found the root cause of my problems and it is not related to a problem in OC.
The events I tried to sync were created by our application and the summary of the events, by mistake, contained an invisible character (HEX 1C, field separator). This causes the sync process on iOS to crash, not only omitting the corrupt event iCalendar but also everything coming after it.

For me sync is now working on iOS also!
