### ISSUE TITLE
CalDav Fatal Error

### ISSUE THREAD

**Issue by danc911** [owncloud/calendar#880]
Hi, Can anyone help me? I'm getting an error/lack of permissions when trying to get CalDav:

Fresh owncloud 8.1 installation.

system: CentOS 7.1.1503 (core)

MariaDB: 5.5.41-MariaDB

Error:

Fatal	caldav	Exception: {"Message":"HTTP\/1.1 403 User did not have the required privileges ({DAV:}read) for path \"calendars\/daniel\/pessoal\"","Code":0,"Trace":"#0 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/Plugin.php(769): Sabre\\DAVACL\\Plugin->checkPrivileges('calendars\/danie...', '{DAV:}read')\n#1 [internal function]: Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#4 \/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/html\/owncloud\/remote.php(132): require_once('\/var\/www\/html\/o...')\n#7 {main}","File":"\/var\/www\/html\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAVACL\/Plugin.php","Line":223}

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...
