### ISSUE TITLE
CalDav syncing on iOS 8.4 stopps working on OwnCloud 8.0.5

### ISSUE THREAD

**Issue by danielkoch** [owncloud/calendar#888]
### Steps to reproduce
1. Create event in web interface or iOS device
2. The event is correct placed in OwnCloud – it it available on the webinterface
3. Try to sync to the iOS device on which the device was NOT created – the event is not available

### Expected behaviour
Events should be visible on every device with has the correct user credentials and permissions

### Actual behaviour
iOS device could not sync events which are located "under" the user but NOT created on this device. Shared events are sync correct. So to summarize: A user can see his own events except they created it itself on the device.

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**
5.5.15

**ownCloud version:** (see ownCloud admin page)
8.0.5

**Updated from an older ownCloud or fresh install:**
updated from 8.0.4 but problems was already there – problem arise without recognizable reason

**List of activated apps:**

Activity 1.2.1

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
n/a

**Operating system:**
Cents OS

#### Web server error log
No error entries

#### ownCloud log (data/owncloud.log)
mod_fcgid: stderr: PHP Fatal error: require_once(): Failed opening required '/<domain>/owncloud/apps/calendar/appinfo/remote.php' (include_path='/<domain>/owncloud/3rdparty/phpseclib/phpseclib/phpseclib:/<domain>/owncloud/3rdparty/pear/pear_exception:/<domain>/owncloud/3rdparty/pear/archive_tar:/<domain>/owncloud/lib/private:/<domain>/owncloud/config:/<domain>/owncloud/3rdparty:/<domain>/owncloud/apps:/<domain>/owncloud/lib:.:/usr/local/php-5.5.15-custom/lib/php:/<domain>/owncloud') in /<domain>/owncloud/remote.php on line 54 

File does not exist: /<domain>/owncloud/data

**Comment by RealRancor** [comment]
Hi,

are you still using the "old" CalDAV endpoint:

https://example.com/owncloud/apps/calendar/appinfo/remote.php

for the CalDAV URL? This is long deprecated and shouldn't be used since ages.

**Comment by danielkoch** [comment]
No. I use this url pattern: ADDRESS/remote.php/caldav/principals/username (https://doc.owncloud.org/server/8.0/user_manual/pim/sync_ios.html)

**Comment by danielkoch** [comment]
Any other idea?

**Comment by danielkoch** [comment]
Same behavior with OC 8.1.1 and the last version (master) of the calendar app (commit hash: 8b6216561f1e304e3b3d4dec1fefca4db800adc6)

**Comment by sudoer** [comment]
I am seeing the same issue.  One server running ownCloud 8.1.1 and Calendar 0.7.3.  Several clients: thunderbird is OK, iCal on Mac is OK, iOS 7.1 calendar is OK, iOS 8.4 calendar does not sync SOME items.  I have not found a pattern to it yet.

**Comment by sudoer** [comment]
I think I might be on to something... I found that if I went into the iOS settings / mail & calendars screen and changed the "sync" setting from "6 months" to "all events", my missing calendar events showed up again.

Here's what I think is going on.  I have two different calendar apps in ownCloud : the traditional "Calendar" 0.7.3 by Georg Ehrke, Bart Visscher, Jakob Sack; and the new "Calendar Plus" 1.0.7
by Döll Sebastian, Georg Ehrke, Bart Visscher, Jakob Sack.  Both calendars are showing symptoms, but they are slightly different.  The older Calendar app will show SOME events from a particular calendar, but not ALL events.  The newer Calendar Plus app will show some ENTIRE CALENDARS, but not others.  I notice that they both share the same 3rdparty (Sabre) code for reading the vCal items.

I also noticed a lot of backtraces in my log file.  They look like this:

    #0 /var/www/owncloud/3rdparty/sabre/vobject/lib/Component/VEvent.php(33): Sabre\VObject\Recur\EventIterator->__construct(Object(Sabre\VObject\Component\VEvent))
    #1 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php(291): Sabre\VObject\Component\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))
    #2 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php(79): Sabre\CalDAV\CalendarQueryValidator->validateTimeRange(Object(Sabre\VObject\Component\VEvent), Object(DateTime), NULL)
    #3 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php(41): Sabre\CalDAV\CalendarQueryValidator->validateCompFilters(Object(Sabre\VObject\Component\VCalendar), Array)
    #4 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Backend/AbstractBackend.php(145): Sabre\CalDAV\CalendarQueryValidator->validate(Object(Sabre\VObject\Component\VCalendar), Array)
    #5 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Backend/AbstractBackend.php(115): Sabre\CalDAV\Backend\AbstractBackend->validateFilterForObject(Array, Array)
    #6 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Calendar.php(427): Sabre\CalDAV\Backend\AbstractBackend->calendarQuery('16', Array)
    #7 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(635): Sabre\CalDAV\Calendar->calendarQuery(Array)
    #8 /var/www/owncloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php(232): Sabre\CalDAV\Plugin->calendarQueryReport(Object(DOMDocument))
    #9 [internal function]: Sabre\CalDAV\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars/alan/...')
    #10 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
    #11 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(705): Sabre\Event\EventEmitter->emit('report', Array)
    #12 [internal function]: Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    #13 /var/www/owncloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)
    #14 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(469): Sabre\Event\EventEmitter->emit('method:REPORT', Array)
    #15 /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    #16 /var/www/owncloud/apps/calendarplus/appinfo/remote.php(84): Sabre\DAV\Server->exec()
    #17 /var/www/owncloud/remote.php(132): require_once('/var/www/ownclo...')
    #18 {main}


I think when the iPhone is asking for an update to the calendar data, it asks for a time range of data.  And somewhere in the process, it runs across an event that spans from (8 months ago) to (7 months ago).  It applies this filter of "last 6 months" and it results in an iterator that goes over an empty set of dates.  So it throws this exception.

The Calendar app catches this exception, or maybe it fails one operation, at the stage where some events have been processed and some others have not.  So you end up seeing SOME events and not others.  Note that you always see events that you entered on that particular iPhone because it is already locally stored in that device's calendar database.

The CalendarPlus app does something similar, but it fails in a way where all of the events of the calendar that contain this way-back-when span item are rejected, so it looks like there is nothing in that calendar.

At least... that is my suspicion.  I'd like to tinker with it a little and see if I can narrow down where the exception is being thrown, and try to catch it.

But the immediate good news is that there is a work-around.  Set your sync timespan to "all events" and the bug is not encountered (it's still there... it just not manifest itself for you).

Alan

**Comment by sudoer** [comment]
I *think* I might have a fix for this... I added a try/catch block to catch that NoInstancesException, and it seems to work OK for me.  I can import previously-problematic ICS files even when my date filter is set to "past 6 months".

I have not filled out the Contributor Agreement, so instead of posting a patch or a pull request, I'll just describe what I did and let someone who knows better than me actually implement it.

In VEvent.php, inside the isInTimeRange() function, I think the three lines (EventIterator, fastForward and return) need to be enclosed in a try/catch block, looking to catch NoInstancesException.  If that Exception is caught, it should do nothing and fall down to the rest of the function.

For this to work, I had to "use Sabre\VObject\Recur\NoInstancesException;" at the beginning.

Alan

**Comment by gvde** [comment]
I doubt that's the correct fix. If it was, it's all in sabredav, i.e. it would be a sabredav bug.

You never posted the calendar/event object which you have in your calendar. It looks like there is something wrong with the object. It must have a recurrence rule which generates no instances. So please post the vevent object from the database...

**Comment by 1337sup3rh4x0r** [comment]
I am seeing the same error in my owncloud logfile when I try to connect to the caldav calendar from my android phone using the app DAVdroid. 
My phone tells me that it can't find any caldav calendars in the url I provided.

The interesting part is, that syncing did work just fine with this setup until I deleted the account from the phone and now tried to readd it.

I am using:
OwnCloud 8.1.1
Calendar 0.73
DavDroid 0.8.4

**Comment by benedikt-d** [comment]
Any news on this issue?
