### ISSUE TITLE
Sync problem with umlauts?

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/calendar#894]
Copied from @cat25451 at https://github.com/owncloud/core/issues/14510#issuecomment-130412981

 > Hi
I am using owncloud 8.1 and Kalendar from debian jessie and see this error in owncloud.log too.
Maybe this is a hint that helps:
As I use german language the name of my private calendar is wirtten "persönlich" and in the URL this is written as "https://.../pers%C3%B6nlich"
If I use another calender like "Schulferien" synchronisation takes place.

**Comment by georgehrke** [comment]
@cat25451 please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by cat25451** [comment]
Since owncloud 8.1 dates and tasks in owncloud are not synced to my local Kalender.
I do not know why and tried several hints. So I found that a new build calender syncs as expected. Maybe a reason of the missfunction lies in the fact  of Umlaute in the name of the calendar.

Hint:
Test with evolution: evolution syncs the tasks but not the dates.


### Steps to reproduce

Sorry I did not succeed reproducing. 
I created a new calender with the Umlaute in its name and then tryed to sync with kde kalender and evolution. It syncs.

### Expected behaviour
All new or modified dates in owncloud made by the web interface or android shall be synced to my local Kalender.

### Actual behaviour

After upgrading owncloud to 8.1 my KDE kalender does not get new tasks or date from owncloud.
Dates made local are synced to owncloud.

### Server configuration
**Operating system**: 
debian wheezy

**Web server:** 
apache

**Database:** 
mysql

**PHP version:**

**ownCloud version:** 
8.1

**Updated from an older ownCloud or fresh install:**
automatic updated since version 7.0

**List of activated apps:**
sh-4.2$ pwd
/var/www/owncloud                                                                                                                                                                                        
sh-4.2$ php occ app:list                                                                                                                                                                                 
Enabled:                                                                                                                                                                                                 
 - activity: 2.0.1                                                                                                                                                                                       
 - calendar: 0.7.2                                                                                                                                                                                       
 - contacts: 0.4.0.0                                                                                                                                                                                     
 - delete_confirmation: 1.0.1                                                                                                                                                                            
 - documents: 0.10.1                                                                                                                                                                                     
 - files: 1.1.10                                                                                                                                                                                         
 - files_external: 0.2.3                                                                                                                                                                                 
 - files_locking:                                                                                                                                                                                        
 - files_pdfviewer: 0.7                                                                                                                                                                                  
 - files_sharing: 0.6.2                                                                                                                                                                                  
 - files_texteditor: 0.4                                                                                                                                                                                 
 - files_trashbin: 0.6.3                                                                                                                                                                                 
 - files_versions: 1.0.6                                                                                                                                                                                 
 - files_videoviewer: 0.1.3                                                                                                                                                                              
 - firstrunwizard: 1.1                                                                                                                                                                                   
 - gallery: 0.6.0                                                                                                                                                                                        
 - mail: 0.1.3                                                                                                                                                                                           
 - provisioning_api: 0.2                                                                                                                                                                                 
 - tasks: 0.7.1
 - templateeditor: 0.1
Disabled:
 - bookmarks
 - encryption
 - external
 - files_antivirus
 - imprint
 - search_lucene
 - user_external
 - user_ldap
 - user_webdavauth


**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xx',
  'passwordsalt' => 'xx',
  'secret' => 'xx',
  'trusted_domains' => 
  array (
    0 => '2944.vhost.myvirtualserver.de',
    1 => 'owncloud.greif-kettmann.de',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://2944.vhost.myvirtualserver.de/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'installed' => true,
  'loglevel' => 0,
  'theme' => '',
  'maintenance' => false,
  'minimum.supported.desktop.version' => '1.6.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xx',
);


**Are you using external storage, if yes which one:** 
no
**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:**
no
### Client configuration
**Browser:**
iceweasel
KDE 4.14.2
**Operating system:**
debian jessie

### Logs
#### Web server log

gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:34 +0200] "REPORT /owncloud/remote.php/caldav/calendars/christian/pers%C3%B6nlich/ HTTP/1.1" 401 2996 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.34 (Kurce_11/4.14.2 Safari/534.34"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:34 +0200] "REPORT /owncloud/remote.php/caldav/calendars/christian/pers%C3%B6nlich/ HTTP/1.1" 401 2996 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.34 (Kurce_11/4.14.2 Safari/534.34"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:34 +0200] "REPORT /owncloud/remote.php/caldav/calendars/christian/pers%C3%B6nlich/ HTTP/1.1" 401 2996 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/534.34 (Kurce_11/4.14.2 Safari/534.34"
gk46.de:443 46.59.186.26 - christian [13/Aug/2015:12:46:35 +0200] "REPORT /owncloud/remote.php/caldav/calendars/christian/pers%C3%B6nlich/ HTTP/1.1" 500 3057 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/5are_resource_11/4.14.2 Safari/534.34"
gk46.de:443 46.59.186.26 - christian [13/Aug/2015:12:46:38 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 6137 "-" "Mozilla/5.0 (Linux) mirall/1.6.4"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:40 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=6&start=1439416800&end=1439503200 HTTP/1.1" 200 1276 "https://owncloud.greif-kett"Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:40 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=1&start=1439416800&end=1439503200 HTTP/1.1" 200 902 "https://owncloud.greif-kettmMozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:40 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=14&start=1439416800&end=1439503200 HTTP/1.1" 200 899 "https://owncloud.greif-kett"Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:40 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=7&start=1439416800&end=1439503200 HTTP/1.1" 200 900 "https://owncloud.greif-kettmMozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:40 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=15&start=1439416800&end=1439503200 HTTP/1.1" 200 899 "https://owncloud.greif-kett"Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:40 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=16&start=1439416800&end=1439503200 HTTP/1.1" 200 1227 "https://owncloud.greif-ket "Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:43 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=birthday_local_1&start=1439416800&end=1439503200 HTTP/1.1" 200 743 "https://ownclps/calendar/" "Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - christian [13/Aug/2015:12:46:35 +0200] "REPORT /owncloud/remote.php/caldav/calendars/christian/pers%C3%B6nlich/ HTTP/1.1" 207 14275 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/ware_resource_11/4.14.2 Safari/534.34"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:42 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=shared_events&start=1439416800&end=1439503200&_=1439460153584 HTTP/1.1" 200 743 "/index.php/apps/calendar/" "Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - christian [13/Aug/2015:12:46:35 +0200] "REPORT /owncloud/remote.php/caldav/calendars/christian/pers%C3%B6nlich/ HTTP/1.1" 207 22439 "-" "Mozilla/5.0 (X11; Linux i686) AppleWebKit/ware_resource_11/4.14.2 Safari/534.34"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:41 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=17&start=1439416800&end=1439503200 HTTP/1.1" 200 1299 "https://owncloud.greif-ket "Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - - [13/Aug/2015:12:46:44 +0200] "GET /owncloud/index.php/apps/calendar/ajax/events.php?calendar_id=birthday_local_4&start=1439416800&end=1439503200 HTTP/1.1" 200 743 "https://ownclps/calendar/" "Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.8.0"
gk46.de:443 46.59.186.26 - christian [13/Aug/2015:12:46:50 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 3045 "-" "Mozilla/5.0 (Linux) mirall/1.6.4"


#### ownCloud log (data/owncloud.log)

{"reqId":"HRHMAfRQKGT6AUmWSbY3","remoteAddr":"46.59.186.26","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-08-13T10:49:00+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/christian\/pers%C3%B6nlich\/"}
{"reqId":"B8YOOUJQlKuNRGPPddR7","remoteAddr":"46.59.186.26","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-08-13T10:49:00+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/christian\/pers%C3%B6nlich\/"}
{"reqId":"\/EY8qxPObg6TKcO68ngJ","remoteAddr":"46.59.186.26","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(149): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(122): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-08-13T10:49:00+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/christian\/pers%C3%B6nlich\/"}
{"reqId":"iyD5zYpamrnAN66lcxaF","remoteAddr":"46.59.186.26","app":"caldav","message":"Exception: {\"Message\":\"This recurrence rule does not generate any valid instances\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Component\\\/VEvent.php(33): Sabre\\\\VObject\\\\Recur\\\\EventIterator->__construct(Object(Sabre\\\\VObject\\\\Component\\\\VEvent))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarQueryValidator.php(291): Sabre\\\\VObject\\\\Component\\\\VEvent->isInTimeRange(Object(DateTime), Object(DateTime))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarQueryValidator.php(79): Sabre\\\\CalDAV\\\\CalendarQueryValidator->validateTimeRange(Object(Sabre\\\\VObject\\\\Component\\\\VEvent), Object(DateTime), NULL)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarQueryValidator.php(41): Sabre\\\\CalDAV\\\\CalendarQueryValidator->validateCompFilters(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar), Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(145): Sabre\\\\CalDAV\\\\CalendarQueryValidator->validate(Object(Sabre\\\\VObject\\\\Component\\\\VCalendar), Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('1', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(635): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/chris...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Recur\\\/EventIterator.php\",\"Line\":199}","level":4,"time":"2015-08-13T10:49:03+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/christian\/pers%C3%B6nlich\/"}

```
