### ISSUE TITLE
  Synchronising Calendars with CalDAV / CalendarSync

### ISSUE THREAD

**Issue by Gasmann0815** [owncloud/calendar#903]
Steps to reproduce:
Upgrade to 7.0.4 -> 8.0.3/8.1.1 #16737

Android Calendar syncing is not possible

Server configuration
HP Proliant Mircoserver - AMD Turion(tm) II Neo N54L Dual-Core Processor
Freenas Jail
https://forums.freenas.org/index.php?threads/drkks-definitive-guide-to-installing-owncloud-in-freenas-or-freebsd.19605/

Operating system:
FreeNAS-9.3-STABLE-201505040117

Web server:
lighttpd-1.4.35_5

Database:
3.8.10.2 2015-05-20 18:17:19

PHP version:
PHP Version 5.6.11

ownCloud version:
ownCloud 8.1.1 (stable)

List of activated apps:
Only Core Apps

The content of config/config.php:
$CONFIG = array (
'instanceid' => 'ocyzlawmg3e3',
'passwordsalt' => 'xxxx',
'secret' => 'xxx',
'trusted_domains' =>
array (
0 => '192.168.2.10',
),
'datadirectory' => '/usr/local/www/owncloud/data',
'overwrite.cli.url' => 'http://192.168.2.10',
'dbtype' => 'sqlite3',
'version' => '8.1.1.3',
'installed' => true,
'loglevel' => 1,
'theme' => '',
'maintenance' => false,
);

No external storage, no encyprytion
external user-bachend: webfrontend, android: caldav calendar-sync carddav-sync

ownCloud log (data/owncloud.log)
Fatal caldav Exception: {"Message":"HTTP\/1.1 403 This calendar only supports 0. We found a VEVENT","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(832): Sabre\CalDAV\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\/rolf\/...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), true)\n#1 [internal function]: Sabre\CalDAV\Plugin->beforeCreateFile('calendars\/rolf\/...', 'BEGIN:VCALENDAR...', Object(OC_Connector_Sabre_CalDAV_Calendar), false)\n#2 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1051): Sabre\Event\EventEmitter->emit('beforeCreateFil...', Array)\n#4 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\DAV\Server->createFile('calendars\/rolf\/...', Resource id #319, NULL)\n#5 [internal function]: Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#6 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\Event\EventEmitter->emit('method:PUT', Array)\n#8 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#9 \/usr\/local\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\DAV\Server->exec()\n#10 \/usr\/local\/www\/owncloud\/remote.php(132): require_once('\/usr\/local\/www\/...')\n#11 {main}","File":"\/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php","Line":912}

**Comment by georgehrke** [comment]
> Only Core Apps

please be more specific. Calendar ain't even a core app

**Comment by georgehrke** [comment]
> This calendar only supports 0

Additionally, please provide an anonymized dump of the oc_ clndr_calendars table

**Comment by Gasmann0815** [comment]
Installed apps:
"Calendar 0.7.3" 
"Contacts 0.4.0.0" 
"OwnNote 1.05"
oc_ clndr_calendars table
"id","userid","displayname","uri","active","ctag","calendarorder","calendarcolor","timezone","components"
"1","xxx","Default calendar","default calendar","1","2405","","#ffff00","5445","0"
"5","xxx","KlinikumWz","klinikumwz","1","691","","#ff0000","882","0"
"8","xxx","Muell","muell","1","#b3dc6c","","VEVENT,VTODO,VJOURNAL","399","0"
"9","xxx","Motorsport2013","motorsport2013","1","266","","#b3dc6c","3336","0"

**Comment by georgehrke** [comment]
Did you change oc_clndr_calendars by hand recently?

**Comment by Gasmann0815** [comment]
It is possible, i tried all sorts of things.....

**Comment by gseilheimer** [comment]
in mac os x 10.11 beta 7 is the same problem!
After the upgrade from 8.0.5 => 8.1.1 the calender app from mac os x won't work correctly.
Problem:
"account name and password could not be checked..."
I tried all the posible links from owncloud for the calender function.

**Comment by georgehrke** [comment]
@gseilheimer Your issue does not seem to be related. Please create a new bug report __using the issue template__

**Comment by georgehrke** [comment]
@Gasmann0815 Can you please replace the 0s in the last row with `VEVENT,VTODO,VJOURNAL`

**Comment by Gasmann0815** [comment]
Replacing with VEVENT,VTODO,VJOURNAL , syncing works for id 5,8,9
but when sycing default_calendar i got this:

Fatal 	caldav 	Exception: {"Message":"This parser only supports VCARD and VCALENDAR files","Code":0,"Trace":"#0 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php(63): Sabre\\VObject\\Parser\\MimeDir->parseDocument()\n#1 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Reader.php(44): Sabre\\VObject\\Parser\\MimeDir->parse('2012-02-03 23:0...', 0)\n#2 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(142): Sabre\\VObject\\Reader::read('2012-02-03 23:0...')\n#3 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Backend\/AbstractBackend.php(115): Sabre\\CalDAV\\Backend\\AbstractBackend->validateFilterForObject(Array, Array)\n#4 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Calendar.php(427): Sabre\\CalDAV\\Backend\\AbstractBackend->calendarQuery('1', Array)\n#5 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(635): Sabre\\CalDAV\\Calendar->calendarQuery(Array)\n#6 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/Plugin.php(232): Sabre\\CalDAV\\Plugin->calendarQueryReport(Object(DOMDocument))\n#7 [internal function]: Sabre\\CalDAV\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\/rolf\/...')\n#8 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#9 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(705): Sabre\\Event\\EventEmitter->emit('report', Array)\n#10 [internal function]: Sabre\\DAV\\CorePlugin->httpReport(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#11 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#12 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:REPORT', Array)\n#13 \/usr\/local\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#14 \/usr\/local\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#15 \/usr\/local\/www\/owncloud\/remote.php(132): require_once('\/usr\/local\/www\/...')\n#16 {main}","File":"\/usr\/local\/www\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Parser\/MimeDir.php","Line":125}

**Comment by georgehrke** [comment]
> This parser only supports VCARD and VCALENDAR 

Looks like the client you use tries to insert something that ain't a calendar.

**Comment by Gasmann0815** [comment]
A new event in default_calendar was synchroniezed....

**Comment by Gasmann0815** [comment]
same error... " This parser only supports VCARD and VCALENDAR"

**Comment by Gasmann0815** [comment]
Array to string conversion at /usr/local/www/owncloud/lib/private/template/functions.php#36

**Comment by Gasmann0815** [comment]
???

 Debug 	calendar 	OC_Calendar_App::generateEventOutput Object contains not event: Array ( [id] => 0 [vevent] => Sabre\VObject\Component\VCalendar Object ( [name] => VCALENDAR [children] => Array ( [0] => Sabre\VObject\Property\FlatText Object ( [delimiter] => , [structuredValues:protected] => Array ( [0] => N [1] => ADR [2] => ORG [3] => GENDER [4] => REQUEST-STATUS ) [minimumPropertyValues:protected] => Array ( [N] => 5 [ADR] => 7 ) [name] => VERSION [group] => [parameters] => Array ( ) [value:protected] => 2.0 [parent] => Sabre\VObject\Component\VCalendar Object *RECURSION* [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) [1] => Sabre\VObject\Property\FlatText Object ( [delimiter] => , [structuredValues:protected] => Array ( [0] => N [1] => ADR [2] => ORG [3] => GENDER [4] => REQUEST-STATUS ) [minimumPropertyValues:protected] => Array ( [N] => 5 [ADR] => 7 ) [name] => PRODID [group] => [parameters] => Array ( ) [value:protected] => -//ownCloud//NONSGML Contacts 0.4.0.0//EN [parent] => Sabre\VObject\Component\VCalendar Object *RECURSION* [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) [2] => Sabre\VObject\Property\FlatText Object ( [delimiter] => , [structuredValues:protected] => Array ( [0] => N [1] => ADR [2] => ORG [3] => GENDER [4] => REQUEST-STATUS ) [minimumPropertyValues:protected] => Array ( [N] => 5 [ADR] => 7 ) [name] => CALSCALE [group] => [parameters] => Array ( ) [value:protected] => GREGORIAN [parent] => Sabre\VObject\Component\VCalendar Object *RECURSION* [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) ) [parent] => [iterator:protected] => [root:protected] => Sabre\VObject\Component\VCalendar Object *RECURSION* ) [repeating] => 1 [summary] => [calendardata] => BEGIN:VCALENDAR VERSION:2.0 PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN CALSCALE:GREGORIAN END:VCALENDAR )

**Comment by IwkP** [comment]
Same here.

Since I have updated from 8.0.4 to 8.1.2 syncronisation between my Android Calendar, Carddav and Tasks isn't possible anymore. On my Android Devices I am using CalDAV, CardDAV and Tasks App.

I hope there will be a fix as soon as possible!?!

**Comment by marlemion** [comment]
Same here, still with 8.1.3.

**Comment by gseilheimer** [comment]
Workaround for me:
- remove the rights for groups from the apps (calender, contacts etc.)

**Comment by PurpleGab** [comment]
I use two Owncloud instances one on a Windows Server 2003 some where in the cloud of unknown version another on my local synology DS 215.
To both I used to have a connection from 
1 Android 5.0 Business Calender + Caldav Sync
2 Windows 7 Outlook 2013 +  cFOS Outlook DAV

Both versions  worked (with some hard startup on the cFOS) until I changed the NAS ownCloud to 8.1.1. (the latest available via DSM Update).

After that only the Android path works. The Windows/ Outlook path fails, a Thunderbird/Lightning pair works without flaw.

I used to be able to open the calender in a standard webbrowser (Firefox, Opera 12). This is no longer possible. Using the provided CALDAV Link Opera returns:
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:sabredav-version>
2.1.6
</s:sabredav-version>
<s:exception>
Sabre\DAVACL\Exception\NeedPrivileges
</s:exception>
<s:message>
User did not have the required privileges ({DAV:}read) for path "calendars/Gabiadmin/nas"
</s:message>
<d:need-privileges>
<d:resource>
<d:href>
/owncloud/remote.php/caldav/calendars/Gabiadmin/nas
</d:href>
<d:privilege>
<d:read/>
</d:privilege>
</d:resource>
</d:need-privileges>
</d:error>

Firefox prompts for a user /pw but then fails with
Mit dieser XML-Datei sind anscheinend keine Style-Informationen verknüpft. Nachfolgend wird die Baum-Ansicht des Dokuments angezeigt.
      <d:error><s:sabredav-version>2.1.6</s:sabredav-version><s:exception>Sabre\DAV\Exception\NotImplemented</s:exception><s:message>There was no handler found for this "GET" method</s:message></d:error>

So far from this side

**Comment by georgehrke** [comment]
@PurpleGab please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

> I used to be able to open the calender in a standard webbrowser (Firefox, Opera 12). This is no longer possible

This is the intended behavior.

**Comment by PurpleGab** [comment]
Good to know.
The people from cFOS used to say "try it on a webbrowser" if you ran into problems to make sure your URL was correct.
I suspect the cFOS Outlook Plugin needs some rework....
Gabi

**Comment by Karl52** [comment]
I have installed OC 8.1.3 for a while - everything seems to work but the following errors related to carddav/sabre  are in my log - they may be related to each other 

-------------------------------------------------------------------------------------
Error   PHP	
Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:70) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#63
-------------------------------------------------------------------------------------
Fatal	carddav	
  Exception: {"Message":"HTTP\/1.1 415 This resource only supports valid vcard data. Parse error: This parser only supports VCARD and VCALENDAR files","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(384): OCA\\Contacts\\CardDAV\\Plugin->validateVCard('BEGIN:VLIST??PR...', false)\n#1 [internal function]: Sabre\\CardDAV\\Plugin->beforeCreateFile('addressbooks\/Al...', 'BEGIN:VLIST??PR...', Object(OCA\\Contacts\\CardDAV\\AddressBook), false)\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1051): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(513): Sabre\\DAV\\Server->createFile('addressbooks\/Al...', Resource id #29, NULL)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/var\/www\/owncloud\/apps\/contacts\/appinfo\/remote.php(84): Sabre\\DAV\\Server->exec()\n#10 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#11 {main}","File":"\/var\/www\/owncloud\/apps\/contacts\/lib\/carddav\/plugin.php","Line":58}
--------------------------------------------------------------------------------------
Fatal	webdav	
Exception: {"Message":"HTTP\/1.1 501 There was no handler found for this \"LOCK\" method","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#2 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#3 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","Line":472}
---------------------------------------------------------------------------------------
Fatal	webdav	Exception: {"Message":"An exception occurred while executing 'UPDATE `oc_properties` SET `propertyvalue` = ? WHERE `userid` = ? AND `propertypath` = ? AND `propertyname` = ?' with params [\"Thu, 06 Aug 2009 11:12:09 GMT\", \"Alfred\", \"\\\/music\\\/Meine H\\u00f6rb\\u00fccher\\\/DIR3.MP3\\\/FIL8.MP3.d20090806-u111209.s63315968.$syncovery\", \"{urn:schemas-microsoft-com:}Win32LastModifiedTime\"]:\n\nSQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE `oc_prop...', Array)\n#2 \/var\/www\/owncloud\/lib\/private\/db\/connection.php(151): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE `oc_prop...', Array, Array)\n#3 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(294): OC\\DB\\Connection->executeUpdate('UPDATE `*PREFIX...', Array)\n#4 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(159): OC\\Connector\\Sabre\\CustomPropertiesBackend->updateProperties(Object(OC\\Connector\\Sabre\\File), Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropPatch.php(288): OC\\Connector\\Sabre\\CustomPropertiesBackend->OC\\Connector\\Sabre\\{closure}(Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropPatch.php(216): Sabre\\DAV\\PropPatch->doCallBackMultiProp(Array, Object(Closure))\n#7 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1249): Sabre\\DAV\\PropPatch->commit()\n#8 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(373): Sabre\\DAV\\Server->updateProperties('music\/Meine H??...', Array)\n#9 [internal function]: Sabre\\DAV\\CorePlugin->httpPropPatch(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#10 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPPATC...', Array)\n#12 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#13 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#14 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#15 {main}","File":"\/var\/www\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115}
