### ISSUE TITLE
SimpleCalDAV - Invalid Mimedir file

### ISSUE THREAD

**Issue by myzinsky** [owncloud/calendar#911]
Hello,
I updated today to OC 8.1.1 with Calendar 0.7.3, since this time I have a problem:

In Combination with SimpleCalDAV (https://github.com/wvrzel/simpleCalDAV) I run into following Issue:

    Invalid Mimedir file. Line starting at 132 did not follow iCalendar/vCard conventions

(@wvrzel)

Here is the detailed Debug output from SimpleCalDav:

```
Exception: Recieved unknown HTTP status



If you think there is a bug in SimpleCalDAV, please report the following information on github or send it at palm.michael@gmx.de.


For debugging purposes:

last request:

REPORT /remote.php/caldav/calendars/myzinsky/arbeit/ HTTP/1.1
Authorization: Basic XXX
User-Agent: cURL based CalDAV client
Host: owncloud.jung.ms
Accept: */*
Content-type: text/xml
Depth: 1
Content-Length: 361

<?xml version="1.0" encoding="utf-8"?>
<C:calendar-query xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <D:prop>
    <C:calendar-data/>
    <D:getetag/>
  </D:prop>
  <C:filter>
    <C:comp-filter name="VCALENDAR">
      <C:comp-filter name="VEVENT">
        <C:time-range start="20150101T000000Z" end="20151231T235959Z"/>
      </C:comp-filter>
    </C:comp-filter>
  </C:filter>
</C:calendar-query>

last response:

HTTP/1.1 500 Internal Server Error
Date: Tue, 25 Aug 2015 19:30:24 GMT
Server: Apache/2.2.22 (Debian) DAV/2 PHP/5.4.41-0+deb7u1 mod_ssl/2.2.22 OpenSSL/1.0.1e mod_perl/2.0.7 Perl/v5.14.2
X-Powered-By: PHP/5.4.41-0+deb7u1
Set-Cookie: XXX; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
Set-Cookie: XXX; path=/; secure; HttpOnly
X-Sabre-Version: 2.1.6
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Content-Length: 326
Connection: close
Content-Type: application/xml; charset=utf-8

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.6</s:sabredav-version>
  <s:exception>Sabre\VObject\ParseException</s:exception>
  <s:message>Invalid Mimedir file. Line starting at 132 did not follow iCalendar/vCard conventions</s:message>
</d:error>


Trace:

#0 /var/www/XXX/calendar/index.php(58): SimpleCalDAVClient->getCustomReport('

```

**Comment by wvrzel** [comment]
Hi,

As you can see in the Debug output, the server is responsing with the
error code 500 (Internal Server Error). This means that there is either
a configuration issue or a bug in your CalDAV server. This is also seems
likely, since this error occoured after a server update.
The request that SimpleCalDAV sent looks absalutly valid to me. I also
have never encountered such a mimedir-error.

So I guess I can't help you. Sorry for that and good luck.

Regards,
Michael Palm


Am 25.08.2015 um 21:41 schrieb Matthias Jung:

**Comment by gvde** [comment]
You have to post the logs from the owncloud server. The client logs don't really help here. Please use template from [contributing guidelines](https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md)

**Comment by myzinsky** [comment]
### Server configuration
**Operating system**:
Debian 7.8
**Web server:**
Apache/2.2.22
**Database:**
mysql 5.5.44-0+deb7u1
**PHP version:**
PHP 5.4.41-0+deb7u1
**ownCloud version:** 
ownCloud 8.1.1 (stable)
**Updated from an older ownCloud or fresh install:**
updated from latest stable
**List of activated apps:**
- Activity  2.0.1
- Deleted files  0.6.3
- External storage support  0.2.3
- PDF Viewer  0.7
- Pictures  0.6.0
- Share Files  0.6.2
- Text Editor  0.4
- Updater  0.6
- Versions  1.0.6
- Video Viewer  0.1.3
- Calendar  0.7.3
- Contacts  0.4.0.0
- Notes  1.0.0
- Tasks  0.7.1

Config: (some things removed)
```php
<?php
$CONFIG = array (
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'installed' => true,
  'instanceid' => '50ced736ea7c8',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'maintenance' => false,
  'forcessl' => true,
  'theme' => '',
  'trusted_domains' =>
  array (
    0 => 'owncloud.XXX',
  ),
  'mail_smtpmode' => 'php',
  'mail_domain' => 'XXX',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'mail_from_address' => 'owncloud',
  'appstore.experimental.enabled' => false,
  'loglevel' => 0,
);
```

Server Log:
```
{"reqId":"BPLANxjgP51WcvpzB\/bB","remoteAddr":"62.75.171.132","app":"caldav","message":"Exception: {\"Message\":\"Invalid Mimedir file. Line starting at 132 did not follow iCalendar\\\/vCard conventions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(189): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty(' ')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(172): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine(' ')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('3', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(635): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#10 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/myzin...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":385}","level":4,"time":"2015-08-28T12:01:47+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/myzinsky\/arbeit\/"}
```

**Comment by wvrzel** [comment]
Hi,

Could you please take me out of this list, since I am not related to the
error and I cannot help you?

Regards,
Michael


Am 28.08.2015 um 14:17 schrieb Matthias Jung:

**Comment by gvde** [comment]
You seem to have one event in your calendar which has a single space in one line...

@wvrzel It's no list. You have subscribed by commenting and you have to unsubscribe using the button at the right column of this issue...

**Comment by myzinsky** [comment]
@gvde: how to solve this? how can I find this specific ics?

**Comment by gvde** [comment]
Try to download your calendar from the web interface and check the content...

**Comment by myzinsky** [comment]
If I try to download the ics from the Webinterface I get an internal server error html file...

Here is the server Log:
```
{"reqId":"zqo3pqZuOqY7QTaXaJwI","remoteAddr":"2.245.206.172","app":"index","message":"Exception: {\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Message\":\"Invalid Mimedir file. Line starting at 132 did not follow iCalendar\\\/vCard conventions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(189): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty(' ')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(172): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine(' ')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/export.php(68): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/export.php(43): OC_Calendar_Export::generateEvent(Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/export.php(28): OC_Calendar_Export::calendar('3')\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/export.php(20): OC_Calendar_Export::export('3', 'calendar')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/route.php(154) : runtime-created function(1): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 [internal function]: __lambda_func(Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/route\\\/router.php(274): call_user_func('\\\\x00lambda_922', Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(873): OC\\\\Route\\\\Router->match('\\\/apps\\\/calendar\\\/...')\\n#13 \\\/var\\\/www\\\/owncloud\\\/index.php(40): OC::handleRequest()\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":385}","level":4,"time":"2015-08-28T13:39:00+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/export.php?calid=3"}
```

**Comment by sokai** [comment]
JFYI: I have exactly (500 error and not possible to download ICS) the same problems ATM :-/
It's not precise since the 8.1. upgrad but after that.

Maybe it can be related to the birthdays of the contacts … In my owncloud.log I found some mysterious lines like
```
{"reqId":"lZu2LriBXypH+vY6YO7F","remoteAddr":"XXX.XXX.XXX.XXX","app":"calendar","message":"OC_Calendar_App::generateEventOutput Object contains not event: Array\n(\n    [id] => 0\n    [vevent] => Sabre\\VObject\\Component\\VCalendar Object\n        (\n            [name] => VCALENDAR\n            [children] => Array\n                (\n                    [0] => Sabre\\VObject\\Property\\FlatText Object\n                        (\n                            [delimiter] => ,\n                            [structuredValues:protected] => Array\n                                (\n                                    [0] => N\n                                    [1] => ADR\n                                    [2] => ORG\n                                    [3] => GENDER\n                                    [4] => REQUEST-STATUS\n                                )\n\n                            [minimumPropertyValues:protected] => Array\n                                (\n                                    [N] => 5\n                                    [ADR] => 7\n                                )\n\n                            [name] => VERSION\n                            [group] => \n                            [parameters] => Array\n                                (\n                                )\n\n                            [value:protected] => 2.0\n                            [parent] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n                            [iterator:protected] => \n                            [root:protected] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n                        )\n\n                    [1] => Sabre\\VObject\\Property\\FlatText Object\n                        (\n                            [delimiter] => ,\n                            [structuredValues:protected] => Array\n                                (\n                                    [0] => N\n                                    [1] => ADR\n                                    [2] => ORG\n                                    [3] => GENDER\n                                    [4] => REQUEST-STATUS\n                                )\n\n                            [minimumPropertyValues:protected] => Array\n                                (\n                                    [N] => 5\n                                    [ADR] => 7\n                                )\n\n                            [name] => PRODID\n                            [group] => \n                            [parameters] => Array\n                                (\n                                )\n\n                            [value:protected] => -\/\/ownCloud\/\/NONSGML Contacts 0.4.0.0\/\/EN\n                            [parent] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n                            [iterator:protected] => \n                            [root:protected] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n                        )\n\n                    [2] => Sabre\\VObject\\Property\\FlatText Object\n                        (\n                            [delimiter] => ,\n                            [structuredValues:protected] => Array\n                                (\n                                    [0] => N\n                                    [1] => ADR\n                                    [2] => ORG\n                                    [3] => GENDER\n                                    [4] => REQUEST-STATUS\n                                )\n\n                            [minimumPropertyValues:protected] => Array\n                                (\n                                    [N] => 5\n                                    [ADR] => 7\n                                )\n\n                            [name] => CALSCALE\n                            [group] => \n                            [parameters] => Array\n                                (\n                                )\n\n                            [value:protected] => GREGORIAN\n                            [parent] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n                            [iterator:protected] => \n                            [root:protected] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n                        )\n\n                )\n\n            [parent] => \n            [iterator:protected] => \n            [root:protected] => Sabre\\VObject\\Component\\VCalendar Object\n *RECURSION*\n        )\n\n    [repeating] => 1\n    [summary] => \n    [calendardata] => BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-\/\/ownCloud\/\/NONSGML Contacts 0.4.0.0\/\/EN\r\nCALSCALE:GREGORIAN\r\nEND:VCALENDAR\r\n\n)\n","level":0,"time":"2015-08-28T13:38:01+00:00","method":"GET","url":"\/index.php\/apps\/calendar\/ajax\/events.php?calendar_id=birthday_local_1&start=1440367200&end=1440972000"}
```

**Comment by gvde** [comment]
It's probably easiest to check directly in the database. Log into the server and run
$ mysql -u root -p owncloud

then enter
mysql> select * from oc_clndr_objects where calendarid = 3;

This shows all events in the calendar with id 3.

**Comment by myzinsky** [comment]
With 

```
select * from oc_clndr_objects where calendarid = 3 and summary = "";
```

if found an event with an empty title and deleted it with my apple client.
However, this does not solve my issue :(

I dumped everything in a file with:

```
 select * from oc_clndr_objects where calendarid = 3 and INTO OUTFILE "/tmp/testfile.txt";
```

with wich grep parameters I can find the issue?

Here is the Serverlog again:
```
{"reqId":"Qgwip4rSJhewFrOT3ivp","remoteAddr":"62.75.171.132","app":"caldav","message":"Exception: {\"Message\":\"Invalid Mimedir file. Line starting at 132 did not follow iCalendar\\\/vCard conventions\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(189): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty(' ')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(172): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine(' ')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('3', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(635): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#10 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/myzin...')\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#13 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#16 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#18 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":385}","level":4,"time":"2015-08-28T14:24:14+00:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/myzinsky\/arbeit\/"}
```

**Comment by gvde** [comment]
It's probably easiest to log every line the parser reads. That way you can see what is at "line 132".

1. Enable debug logging by setting loglevel = 0 in your config.php.
2. Make a backup copy of 3rdparty/sabre/vobject/lib/Parser/MimeDir.php
3. Edit MimeDir.php:
after the line ```protected function parseLine($line) {```
insert 
```\OCP\Util::writeLog('sabre', __METHOD__ . ' line: ' . $line, \OCP\Util::DEBUG);```
This will log each line.
4. Make the simplecaldav call again to recreate the error.
5. Check the log to see the lines before the error. That will hopefully allow you to identify the event which causes the problem.
6. Don't forget to restore the backup copy!

**Comment by myzinsky** [comment]
Thank you so much! This helped me to identify the Event. It was re-occuring event created back in 2010, maybe from a client that was not following the ICAL specification.

**Comment by sokai** [comment]
Got it! – Thanks to @gvde! :+1: 

I debugged like explained. Then I found an corrupt event (from 2013) and deleted it. Now everithy syncs … :)

Maybe you should build in a possibility for checking events in the web frontend …!?

BTW: My hint regarding the birthdays of the contacts in my calendar was a different problem.

**Comment by FloFra** [comment]
How is this not a bug? Should the calendar not check received data for concistency before inserting it into the database?
