### ISSUE TITLE
CalDav Sync Throws 405 - Method Not Allowed

### ISSUE THREAD

**Issue by PattyCode** [owncloud/calendar#915]
### Steps to reproduce
1. Enable calendar app in the GUI, but only make them available to a certain group, which does not include the administrator.
2. Try to sync calendar with DAVdroid

### Expected behaviour
Calendar should be syncing.

### Actual behaviour
DAVdroid gets a 405 HTTP status code reply, when requesting a PROPFIND on "/owncloud/index.php" (see apache log). It is a sensible behaviour to issue a 405 for this request. The question is, why DAVdroid is requesting it. In the Android log it is evident it gets this address from a previous PROPFIND on a proper path like "/owncloud/remote.php/caldav/calendars/user1/pers%C3%B6nlich/" in the "Location" part. At least as far as I can tell.

Also note the calendar app is not in the enabled list of apps as output from "occ app:list". It is actually version 0.7.3.

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache 2.4.7

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Updated from 7.?

**List of activated apps:**
```
Enabled:
 - activity: 2.0.1
 - files: 1.1.10
 - files_external: 0.2.3
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - search_lucene: 0.6.0
 - templateeditor: 0.1
Disabled:
 - calendar
 - contacts
 - encryption
 - external
 - files_locking
 - provisioning_api
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**
```
$CONFIG = array (
  'instanceid' => 'ocfb22fd28d4',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => '123.123.123.123',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://123.123.123.123/owncloud',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 0,
);
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none
### Client configuration
**Browser:** DAVdroid 0.8.3

**Operating system:** Android 5.0

#### Web server error log
```
123.123.123.123 - user1 [30/Aug/2015:15:07:45 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/user1/pers%C3%B6nlich/ HTTP/1.1" 302 1029 "-" "DAVdroid/0.8.3"
123.123.123.123 - user1 [30/Aug/2015:15:07:45 +0200] "PROPFIND /owncloud/index.php HTTP/1.1" 405 886 "-" "DAVdroid/0.8.3"
```

#### ownCloud log (data/owncloud.log)
No related log messages

#### Browser log
```
I/davdroid.DavSyncAdapter(15415): Performing sync for authority com.android.calendar
D/davdroid.DavSyncAdapter(15415): Creating new DavHttpClient
I/davdroid.DavHttpClient(15415): Wire logging active, disabling HTTP compression
V/davdroid.URIUtils(15415): Normalized URI https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/persönlich/ -> https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/pers%C3%B6nlich/ assuming that it was an URI or path name
D/davdroid.WebDavResource(15415): Using preemptive authentication (not compatible with Digest auth)
V/davdroid.URIUtils(15415): Normalized URI https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/common_shared_by_user2/ -> https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/common_shared_by_user2/ assuming that it was an URI or path name
D/davdroid.WebDavResource(15415): Using preemptive authentication (not compatible with Digest auth)
V/davdroid.URIUtils(15415): Normalized URI https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/persönlich_shared_by_user2/ -> https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/pers%C3%B6nlich_shared_by_user2/ assuming that it was an URI or path name
D/davdroid.WebDavResource(15415): Using preemptive authentication (not compatible with Digest auth)
V/davdroid.URIUtils(15415): Normalized URI https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/contact_birthdays/ -> https://123.123.123.123/owncloud/remote.php/caldav/calendars/user1/contact_birthdays/ assuming that it was an URI or path name
D/davdroid.WebDavResource(15415): Using preemptive authentication (not compatible with Digest auth)
D/HttpClient(15415): CookieSpec selected: best-match
D/HttpClient(15415): Re-using cached 'basic' auth scheme for https://123.123.123.123:443
D/HttpClient(15415): Connection request: [route: HttpRoute[{s}->https://123.123.123.123:443]][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 3]
D/HttpClient(15415): Connection leased: [id: 9][route: HttpRoute[{s}->https://123.123.123.123:443]][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 3]
D/HttpClient(15415): Opening connection HttpRoute[{s}->https://123.123.123.123:443]
D/HttpClient(15415): Connecting to 123.123.123.123/123.123.123.123:443
D/HttpClient(15415): Connecting socket to 123.123.123.123/123.123.123.123:443 with timeout 20000
D/HttpClient(15415): Starting handshake
D/HttpClient(15415): Secure session established
D/HttpClient(15415):  negotiated protocol: TLSv1.2
D/HttpClient(15415):  negotiated cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
D/HttpClient(15415): Connection established 192.168.2.100:53794<->123.123.123.123:443
D/HttpClient(15415): Executing request PROPFIND /owncloud/remote.php/caldav/calendars/user1/pers%C3%B6nlich/ HTTP/1.1
D/HttpClient(15415): Target auth state: CHALLENGED
D/HttpClient(15415): Proxy auth state: UNCHALLENGED
D/Wire    (15415): http-outgoing-9 >> "PROPFIND /owncloud/remote.php/caldav/calendars/user1/pers%C3%B6nlich/ HTTP/1.1[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Content-Type: text/xml; charset=UTF-8[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Accept: text/xml[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Depth: 0[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Content-Length: 328[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Host: 123.123.123.123[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Connection: Keep-Alive[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "User-Agent: DAVdroid/0.8.3[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Authorization: xyz[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "<propfind xmlns="DAV:">[\n]"
D/Wire    (15415): http-outgoing-9 >> "   <prop>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <A:calendar-color xmlns:A="http://apple.com/ns/ical/"/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <displayname/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <CS:getctag xmlns:CS="http://calendarserver.org/ns/"/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <resourcetype/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <CD:supported-address-data class="java.util.LinkedList" xmlns:CD="urn:ietf:params:xml:ns:carddav"/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "   </prop>[\n]"
D/Wire    (15415): http-outgoing-9 >> "</propfind>"
D/Wire    (15415): http-outgoing-9 << "HTTP/1.1 302 Found[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Date: Sun, 30 Aug 2015 13:07:45 GMT[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Server: Apache/2.4.7 (Ubuntu)[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Strict-Transport-Security: max-age=15768000[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Powered-By: PHP/5.5.9-1ubuntu4.11[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Expires: Thu, 19 Nov 1981 08:52:00 GMT[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Pragma: no-cache[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Location: https://123.123.123.123/owncloud/index.php[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Content-Type-Options: nosniff[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-XSS-Protection: 1; mode=block[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Robots-Tag: none[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Content-Length: 0[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Keep-Alive: timeout=5, max=100[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Connection: Keep-Alive[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Content-Type: text/html; charset=UTF-8[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "[\r][\n]"
D/HttpClient(15415): Connection can be kept alive for 5000 MILLISECONDS
D/HttpClient(15415): Authentication succeeded
V/davdroid.URIUtils(15415): Normalized URI https://123.123.123.123/owncloud/index.php -> https://123.123.123.123/owncloud/index.php assuming that it was an URI or path name
I/davdroid.WebDavResource(15415): Redirection on PROPFIND; trying again at new content URL: https://123.123.123.123/owncloud/index.php
D/HttpClient(15415): Connection [id: 9][route: HttpRoute[{s}->https://123.123.123.123:443]] can be kept alive for 5.0 seconds
D/HttpClient(15415): Connection released: [id: 9][route: HttpRoute[{s}->https://123.123.123.123:443]][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 3]
D/HttpClient(15415): CookieSpec selected: best-match
D/HttpClient(15415): Connection request: [route: HttpRoute[{s}->https://123.123.123.123:443]][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 3]
D/HttpClient(15415): Connection leased: [id: 9][route: HttpRoute[{s}->https://123.123.123.123:443]][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 3]
D/HttpClient(15415): Executing request PROPFIND /owncloud/index.php HTTP/1.1
D/HttpClient(15415): Target auth state: SUCCESS
D/HttpClient(15415): Proxy auth state: UNCHALLENGED
D/Wire    (15415): http-outgoing-9 >> "PROPFIND /owncloud/index.php HTTP/1.1[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Content-Type: text/xml; charset=UTF-8[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Accept: text/xml[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Depth: 0[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Content-Length: 328[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Host: 123.123.123.123[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Connection: Keep-Alive[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "User-Agent: DAVdroid/0.8.3[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Cookie2: $Version=1[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "Authorization: xyz[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "[\r][\n]"
D/Wire    (15415): http-outgoing-9 >> "<propfind xmlns="DAV:">[\n]"
D/Wire    (15415): http-outgoing-9 >> "   <prop>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <A:calendar-color xmlns:A="http://apple.com/ns/ical/"/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <displayname/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <CS:getctag xmlns:CS="http://calendarserver.org/ns/"/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <resourcetype/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "      <CD:supported-address-data class="java.util.LinkedList" xmlns:CD="urn:ietf:params:xml:ns:carddav"/>[\n]"
D/Wire    (15415): http-outgoing-9 >> "   </prop>[\n]"
D/Wire    (15415): http-outgoing-9 >> "</propfind>"
D/Wire    (15415): http-outgoing-9 << "HTTP/1.1 405 Method Not Allowed[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Date: Sun, 30 Aug 2015 13:07:45 GMT[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Server: Apache/2.4.7 (Ubuntu)[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Strict-Transport-Security: max-age=15768000[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Powered-By: PHP/5.5.9-1ubuntu4.11[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Expires: Thu, 19 Nov 1981 08:52:00 GMT[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Pragma: no-cache[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Status: 405 Method Not Allowed[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Content-Type-Options: nosniff[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-XSS-Protection: 1; mode=block[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Robots-Tag: none[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Content-Length: 0[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Keep-Alive: timeout=5, max=99[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Connection: Keep-Alive[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "Content-Type: text/html; charset=UTF-8[\r][\n]"
D/Wire    (15415): http-outgoing-9 << "[\r][\n]"
D/HttpClient(15415): Connection can be kept alive for 5000 MILLISECONDS
D/HttpClient(15415): http-outgoing-9: Shutdown connection
D/HttpClient(15415): Connection discarded
D/HttpClient(15415): http-outgoing-9: Close connection
D/HttpClient(15415): Connection released: [id: 9][route: HttpRoute[{s}->https://123.123.123.123:443]][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 3]
E/davdroid.DavSyncAdapter(15415): Hard HTTP error 405
E/davdroid.DavSyncAdapter(15415): at.bitfire.davdroid.webdav.HttpException: 405 Method Not Allowed
E/davdroid.DavSyncAdapter(15415): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:357)
E/davdroid.DavSyncAdapter(15415): 	at at.bitfire.davdroid.webdav.WebDavResource.checkResponse(WebDavResource.java:327)
E/davdroid.DavSyncAdapter(15415): 	at at.bitfire.davdroid.webdav.WebDavResource.propfind(WebDavResource.java:207)
E/davdroid.DavSyncAdapter(15415): 	at at.bitfire.davdroid.resource.WebDavCollection.getProperties(WebDavCollection.java:64)
E/davdroid.DavSyncAdapter(15415): 	at at.bitfire.davdroid.syncadapter.SyncManager.synchronize(SyncManager.java:49)
E/davdroid.DavSyncAdapter(15415): 	at at.bitfire.davdroid.syncadapter.DavSyncAdapter.onPerformSync(DavSyncAdapter.java:137)
E/davdroid.DavSyncAdapter(15415): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
I/davdroid.DavSyncAdapter(15415): Sync complete for com.android.calendar
D/davdroid.DavSyncAdapter(15415): Closing httpClient
D/HttpClient(15415): Connection manager is shutting down
D/HttpClient(15415): Connection manager shut down
```

**Comment by RealRancor** [comment]
Hi,

you can't use CalDAV if the calendar App is disabled. Because of this you're probably get an 302 (redirect) to /owncloud/index.php

**Comment by PattyCode** [comment]
Hi,

yes user1 is in group calendar, which is allowed to use the calendar app.

I can confirm the dependency between contacts and calendar app as described in issue #489. And I can confirm the comment of acfbuerger, that this worked in a previous owncloud version for me (last stable release of main version 7).

But I guess I posted a duplicate. Sorry for that.

**Comment by PattyCode** [comment]
I remember I had the issue owncloud/core#18224 while updating. As described in the issue manual upgrade "solved" it. I don't know whether this could be related.

**Comment by RealRancor** [comment]
Hi,

if its an duplicate of #489 feel free to close here as #489 is still open.

Btw. i have raised https://github.com/owncloud/core/issues/18690 as the ./occ app:list shouldn't show the app as disabled if its only enabled for a specific group.

**Comment by PattyCode** [comment]
Duplicate of #489
