### ISSUE TITLE
CalDAV sync doesn't work since update to version 8.1.2

### ISSUE THREAD

**Issue by Pempam** [owncloud/calendar#927]
Since my clean upgrade from oc 8.0.4 to oc 8.1.2 (deleting everything in the diretory besides data and settings) I cannot sync oc calendar with my Android devices.

The log-file of my Android-App "CalDav" shows a lot of different entries:

- The requested method PROPFIND is not allowed for the URL
- DavPropFind 405 Method Not Allowed
- DavPropFind Status: 405
- DavPropFind Status: 404
- Dav could not locate current user principal at /SOGo/dav

I'm using SSL for connection.

I never had problems with this issue even since update to 8.1.2

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) .......

**Comment by RealRancor** [comment]
Additionally to the issue template it might be useful to state which URL you're using in the CalDAV app.

**Comment by Pempam** [comment]
The URL I was testing are

- https://mydomain.de1.cc/owncloud/remote.php/caldav
- https://mydomain.de1.cc/owncloud/remote.php/caldav/calendars/myusername

(mydomain without "www")

They are not working twice.

I never had problems with the mentioned URL since 8.0.4.

**Comment by RealRancor** [comment]
@Pempam Then please fill out the issue template as asked above.

**Comment by Pempam** [comment]
First, here is my config php. Maybe there is someting which I have forgotten or which was overwritten through the update? It seems to be very slim...!?

<?php
$CONFIG = array (
  'instanceid' => '12932fh64263',
  'passwordsalt' => 'wc5f898748hbj3h3zhj3d8da44e56',
  'datadirectory' => '/kunden/000000_00000/webseiten/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.2.1',
  'dbname' => 'db103336',
  'dbhost' => 'mysql5.example.de1.cc',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'db103336',
  'dbpassword' => 'JGHdgdf',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => 3,
  'maintenance' => false,
  'trashbin_retention_obligation' => 7,
  'defaultapp' => 'calendar',
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => 'example.de1.cc',
  ),
  'secret' => '9ssdsds55f50d7678d6dbd86sdhd7fj8g7fgh8fgh8hd6f8gh6g86hfba8a4afefe',
  'mail_smtpmode' => 'smtp',
);

**Comment by RealRancor** [comment]
@Pempam You just have posted your database user and password publicly.

**Comment by Pempam** [comment]
Thank you for your advice, RealRancor. I filled it with fake entries before. But I think it's quite better to leave those fields emtpy.

**Comment by gvde** [comment]
@pempam it would be so much easier if you actually used the template. If you did you wouldn't have posted those passwords and all the information necessary would be there in one place now...

**Comment by Pempam** [comment]
Ok, thank you. I try my best and I will post the issue template soon.

**Comment by Pempam** [comment]
Let me first give you some information concerning the log-file from my CalDav-Android-App:

Dav PropFind Status: 405

Dav could not locate current user principal at /owncloud/remote.php/caldav

Dav get principal /.well-known/caldav

Dav ProFind Status: 405

**Comment by RealRancor** [comment]
@Pempam 405 means "Method not allowed" so it seems your webserver is blocking the needed PROPFIND method. See this FAQ for some background info: https://forum.owncloud.org/viewtopic.php?f=17&t=7536

**Comment by Pempam** [comment]
Is "Propfind" something new with OC8.1? I never had Caldav problems with OC.

**Comment by gvde** [comment]
@pempam please use the template. Take the whole template. Fill in the blanks. Post the whole output. Collecting various pieces of information from various parts of this issue is cumbersome... With the template there is all the most important information at once in a single place...

**Comment by Pempam** [comment]
### Actual behaviour

Android Caldav-App does not sync with owncloud calendar 8.1.2

Using my owncloud data directory as netdrive on my Win7 System it is possible to have access.
It’s also possible to use webdav with the Android App ES Explorer (move/copy files etc. between owncloud data directory and Android Directory.)

### Server configuration

Operating system:

Web server: Apache/2.4.10

Database: MySQL

PHP version: 5.4.16

### ownCloud version: 8.1.2 (stable)

### Updated from an older ownCloud or fresh install: Update from 8.0.4 to 8.1.2

I was deleting everything on my owncloud directory except the ‚config‘ and ‚data‘ directories and my php.ini file.

List of activated apps:
Deleted Files
PDF Viewer
Pictures
Share Files
Text Editor
Updater
Calendar 0.7.3
Contacts
Files Move 0.8.1a
Tasks 0.8

### If you have access to your command line run e.g.:

No access to the command line.

### The content of config/config.php:**

<?php
 $CONFIG = array (
 'instanceid' => '....',
 'passwordsalt' =>
 'datadirectory' => '/.../web/owncloud/data',
 'dbtype' => 'mysql',
 'version' => '8.1.2.1',
 'dbname' => '....',
 'dbhost' => 'mysql5.',
 'dbtableprefix' => 'oc_',
 'dbuser' => '...',
 'dbpassword' =>
 'installed' => true,
 'forcessl' => true,
 'loglevel' => 3,
 'maintenance' => false,
 'trashbin_retention_obligation' => 7,
 'defaultapp' => 'calendar',
 'theme' => '',
 'trusted_domains' => 
 array (
 0 => '<>',
 ),
 'secret' =>
 'mail_smtpmode' => 'smtp',
 );

### Are you using external storage, if yes which one:** local/smb/sftp/...
No.

### Are you using encryption:** No.

###Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration

**Operating system:**
Android 2.3.4 / Android 4 (no difference, no calendar sync with caldav possible)

#### ownCloud log (data/owncloud.log)

Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
Error 	tasks 	Can not enable the Tasks app because the Calendar App is disabled.
....And much more of them....

Error	PHP	Array to string conversion at …/owncloud/lib/private/template/functions.php#36
…/owncloud/lib/private/template/functions.php#36
…/owncloud/lib/private/template/functions.php#36

Fatal Index

Exception: {"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[28000] [1045] Access denied for user 'db100000'@'127.0.0.3' (using password: YES)","Code":0,"Trace":"#0 \/…\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(429): OC\\DB\\Connection->connect()\n#1 \/…\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 \/…\/...\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 \/...\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 \/...\/owncloud\/lib\/private\/db\/connection.php(83): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 \/...\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#6 \/...\/owncloud\/lib\/private\/db\/connectionfactory.php(124): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#7 \/...\/owncloud\/lib\/private\/server.php(301): OC\\DB\\ConnectionFactory->getConnection('mysql', Array)\n#8 \/...\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#9 \/...\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('DatabaseConnect...')\n#10 \/...\/owncloud\/lib\/private\/server.php(696): OC\\AppFramework\\Utility\\SimpleContainer->query('DatabaseConnect...')\n#11 \/...\/owncloud\/lib\/private\/db.php(42): OC\\Server->getDatabaseConnection()\n#12 \/...\/owncloud\/lib\/private\/server.php(209): OC_DB::getConnection()\n#13 \/...\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#14 \/...\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('AppConfig')\n#15 \/...\/owncloud\/lib\/private\/server.php(642): OC\\AppFramework\\Utility\\SimpleContainer->query('AppConfig')\n#16 \/...\/owncloud\/lib\/private\/server.php(343): OC\\Server->getAppConfig()\n#17 \/...\/owncloud\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php(112): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#18 \/...\/owncloud\/lib\/private\/appframework\/utility\/simplecontainer.php(96): Pimple\\Container->offsetGet('AppManager')\n#19 \/...\/owncloud\/lib\/private\/server.php(862): OC\\AppFramework\\Utility\\SimpleContainer->query('AppManager')\n#20 \/...\/owncloud\/lib\/private\/app.php(238): OC\\Server->getAppManager()\n#21 \/...\/owncloud\/lib\/private\/app.php(93): OC_App::getEnabledApps()\n#22 \/...\/owncloud\/lib\/base.php(592): OC_App::loadApps(Array)\n#23 \/...\/owncloud\/lib\/base.php(1121): OC::init()\n#24 \/...\/owncloud\/index.php(38): require_once('\/...\/100000_...')\n#25 {main}","File":"\/...\/owncloud\/lib\/private\/db\/connection.php","Line":50}

**Comment by georgehrke** [comment]
Are you sure the calendar is enabled? __because the Calendar App is disabled.__ says different.

**Comment by georgehrke** [comment]
If it is enabled, is it enabled for all or only for selected groups?

**Comment by Pempam** [comment]
Calendar App is enabled and I can work with using www.

I installed the tasks App later.

Calendar is enabled for all, not for a special group.

**Comment by RealRancor** [comment]
@Pempam Then please clean your data/owncloud.log and try again to only have the relevant logentries for your problem. It doesn't make sense that anyone needs to guess which log entries are relevant if you're posting older entries.

**Comment by Pempam** [comment]
That is a clean oc log.

Only the 'Fatal Index' is a bit older.

**Comment by RealRancor** [comment]
Hi,

then your current logs are telling that you havn't enabled the calendar app. Maybe you have disabled the standard "calendar" app and just had enabled the "calendarplus" app?

Please post the output of:

```./occ app:list```

entered into your console.

**Comment by Pempam** [comment]
When I was activate some Apps, I got the message below:

Interner Serverfehler

Der Server hat einen internen Fehler und konnte Ihre Anfrage nicht vervollständigen.

Bitte wenden Sie sich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, geben Sie bitte die, unten stehenden, technischen Details in Ihrem Bericht mit an.

Weitere Details können im Serverprotokoll gefunden werden.

Technische Details
Entfernte Adresse: xx..xx.xxx
Anforderungskennung: UsSP.............

I got these message when I was upgrading oc. After I reload the page I was able to login.

**Comment by RealRancor** [comment]
Please answer the question above and post the output as asked instead of some random info.

**Comment by Pempam** [comment]
Unfortunately I have no options to use the console.

Now I did a new upgrade to version 8.1.1. I don't no why I got a version 8.1.2 (from https://owncloud.org/changelog/, Files are from 02.09.2015) which I upgraded to. The Version 8.1.2 isn't visible anymore on owncloud.org/changelog.

Sync works now with 8.1.1.

**Comment by Pempam** [comment]
Now I can reproduce why caldav is not working:

If I allow the apps calendar and contacts (and maybe also tasks) only for the specific group 'admin', caldav is not working anymore. No sync between owncloud and my Android Calendar. If I cancel the specifiy allowance, sync works well.

**Comment by RealRancor** [comment]
Yes, thats known and a dup of https://github.com/owncloud/calendar/issues/908

A possible fix is discussed in https://github.com/owncloud/calendar/pull/502
