### ISSUE TITLE
Syncs errors with All-day and same-time events

### ISSUE THREAD

**Issue by simongareste** [owncloud/calendar#931]
### Steps to reproduce
1. Paul and John use owncloud calendar
2. Paul adds a all-day event Event to his calendar
3. John is subscribed to Paul's calendar in iCal or Lightning (Thuderbird)
4. John opens iCal

### Expected behaviour
John should see the event as All-Day

### Actual behaviour
John sees the event as All-Day, but an error message appears:
`Access  to "Event" in "Paul's Calendar" in account "owncloud.somewhere.co" is not permitted. The server responded "403" to operation CalDAVWriteEntityQueueableOperation.`

### Server configuration
**Operating system**:Ubuntu 15.04

**Web server:**Apache2

**Database:**MariaDB

**PHP version:** PHP 5.6.4

**ownCloud version:** 8.1.1.3

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** calendar, contacts

**The content of config/config.php:**

```
<?php
define('DEBUG',true);
$CONFIG = array (
  'instanceid' => '51827c101e119',
  'passwordsalt' => 'XX',
  'datadirectory' => '/home/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => 'owncloud.somewhere.co',
  ),
  'secret' => 'XX',
  'share_folder' => '/Shared',
  'dbname' => 'owncloud',
  'dbhost' => '172.16.0.5',
  'dbuser' => 'XX',
  'dbpassword' => 'XX',
  'appcodechecker' => false,
  'memcache.local' => '\\OC\\Memcache\\APC',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'somewhere.co',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.somewhere.co',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'noreply@somewhere.co',
  'mail_smtppassword' => 'XX',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Mac OS X Yosemite

#### Web server error log
```
Insert your webserver log here
```[Wed Sep 09 17:30:29.112739 2015] [fastcgi:error] [pid 15795] [client our.ip:53333] FastCGI: comm with server "/usr/lib/cgi-bin/php5-fcgi" aborted: idle timeout (900 sec), referer: https://owncloud.somewhere.co/index.php/apps/calendar/
[Wed Sep 09 17:30:29.112769 2015] [fastcgi:error] [pid 15795] [client our.ip:53333] FastCGI: incomplete headers (0 bytes) received from server "/usr/lib/cgi-bin/php5-fcgi", referer: https://owncloud.somewhere.co/index.php/apps/calendar/
```

#### ownCloud log (data/owncloud.log)
```
{"reqId":"VfBWCCW7oOEAAEV6v9sAAAAF","remoteAddr":"our.ip","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Service unavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: {closure}(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\\n#2 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/home\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/owncloud\\\/remote.php(64): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/home\\\/owncloud\\\/remote.php(135): handleException(Object(RemoteException))\\n#6 {main}\",\"File\":\"\\\/home\\\/owncloud\\\/remote.php\",\"Line\":55}","level":4,"time":"2015-09-09T15:53:45+00:00"}
```

Owncloud 8.1.1, calendar 0.7.3
Using iCal and Lightning 3.3.3 (in Thunderbird 31.5) on Yosemite. 

When someone sets an event for the whole day, people subscribed to his calendar get an error

When someone has an event at the same time as another one he owns, people subscribed to his calendar get the error (same as previous). In the database, we have two entries with the same name, I'm not sure if that's an issue (see below). Timezones are set to the same values in iCal, Lightning and OwncloudCalendar. Any idea on how to debug?

```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20150907T093712Z
LAST-MODIFIED:20150907T100124Z
DTSTAMP:20150907T100124Z
UID:fec9b633-fbfa-4f0e-8930-06996baf6d22
SUMMARY:Presentation
ORGANIZER;RSVP=TRUE;PARTSTAT=ACCEPTED;ROLE=CHAIR:mailto:jean@somewhere.co
ATTENDEE;RSVP=TRUE;CN=Adrien;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PA
 RTICIPANT:adrien@somewhere.co
ATTENDEE;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:adrien@somewhere.co
DTSTART;TZID=Europe/Paris:20150907T160000
DTEND;TZID=Europe/Paris:20150907T170000
TRANSP:OPAQUE
X-MOZ-RECEIVED-SEQUENCE:0
X-MOZ-RECEIVED-DTSTAMP:20150907T093826Z
END:VEVENT
END:VCALENDAR
```

and
```
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Paris
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20150907T093712Z
LAST-MODIFIED:20150907T143907Z
DTSTAMP:20150907T143907Z
UID:fec9b633-fbfa-4f0e-8930-06996baf6d22
SUMMARY:Presentation
ORGANIZER;RSVP=TRUE;PARTSTAT=ACCEPTED;ROLE=CHAIR:mailto:jean@somewhere.co
ATTENDEE;RSVP=TRUE;CN=Adrien;PARTSTAT=NEEDS-ACTION;ROLE=REQ-PA
 RTICIPANT:adrien@somewhere.co
ATTENDEE;PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT;RECEIVED-SEQUENCE=0;RECEIV
 ED-DTSTAMP=20150907T100127Z:mailto:adrien@somewhere.co
X-MOZ-LASTACK:20150907T143907Z
DTSTART;TZID=Europe/Paris:20150907T160000
DTEND;TZID=Europe/Paris:20150907T170000
TRANSP:OPAQUE
X-MOZ-SEND-INVITATIONS:TRUE
X-MOZ-SEND-INVITATIONS-UNDISCLOSED:FALSE
X-MOZ-GENERATION:2
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT15M
DESCRIPTION:Description par défaut Mozilla
END:VALARM
END:VEVENT
END:VCALENDAR
```

**Comment by te-online** [comment]
@simongareste Did you try to set up the account again? Worked here https://github.com/owncloud/calendar/issues/340
