### ISSUE TITLE
OC 8.1.1 Lightning 4.0.2 CalDav Sync does not work

### ISSUE THREAD

**Issue by deichy** [owncloud/calendar#932]
### Steps to reproduce
1. Login into owncloud as nomal user
2. Create new Calendar "test"
3. Sync via CalDav Link and Lightning

### Expected behaviour
Calendar syncs and is visible on every device.

### Actual behaviour
Lightning refuses to sync and deactivates the Calendar. Android Client has no Problems.
Only one User is affected.
All Calendars of this user are affected.
Other Calendars from other users work as usual.

I tested on 2 different Devices (Win 7 and 10) with the same Thunderbird/Lightning Versions.
The Workaround from Issue #841 did not solve the Problem.
### Server configuration
**Operating system**:
Debian Squeeze Linux 2.6.18-prep-xenU-static-i686-he+12
(Hosteurope Managed vServer)
**Web server:**
Apache 2.0 (API: 20051115)
**Database:**
MySQL 5.5.44
**PHP version:**
5.5.28
**ownCloud version:** (see ownCloud admin page)
8.1.1
**Updated from an older ownCloud or fresh install:**
Updated from 8.0
First Installation was Owncloud 6
**List of activated apps:**
- Calendar
- Tasks
- Mail
- Files
- Deleted Files
- Default Encryption Module
- First Run Wizard
- PDF Viewer
- Pictures
- Share Files
- Text Editor
- Updater
- Verisions
- Video Viewer
- Contacts
- OwnBackup

**The content of config/config.php:**

  'instanceid' => '51e28cf810eae',
  'passwordsalt' => 'xx',
  'datadirectory' => '/is/htdocs/wp10602071_U08ROTJF2A/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.1.3',
  'dbname' => 'db10602071-owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xx',
  'dbpassword' => 'xx',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'trusted_domains' => 
  array (
    0 => 'nrwww.com',
  ),
  'secret' => '45fc693259c39e9efa594a48ffa62a5511d2d26fc36bf9da5699688cd1910edf560f984ebceb8c8ef744747de98f2b4c',
  'share_folder' => '/Shared',
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'nrwww.com',
  'loglevel' => 0,

);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
n/a
**Operating system:**
Windows 7
and
Windows 10
#### Web server error log
n/a

#### ownCloud log (data/owncloud.log)
Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"#0 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/remote.php(132): require_once('\/is\/htdocs\/wp10...')\n#9 {main}","File":"\/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70} 

and

Exception: {"Message":"HTTP\/1.1 404 Node with name 'test' could not be found","Code":0,"Trace":"#0 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/apps\/calendar\/lib\/sabre\/usercalendars.php(45): Sabre\\CalDAV\\CalendarHome->getChild('test')\n#1 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php(76): OC_Connector_Sabre_CalDAV_UserCalendars->getChild('test')\n#2 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(920): Sabre\\DAV\\Tree->getNodeForPath('calendars\/tribu...')\n#3 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\\DAV\\Server->getPropertiesForPath('calendars\/tribu...', Array, 0)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPropfind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#7 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/apps\/calendar\/appinfo\/remote.php(57): Sabre\\DAV\\Server->exec()\n#9 \/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/remote.php(132): require_once('\/is\/htdocs\/wp10...')\n#10 {main}","File":"\/is\/htdocs\/wp10602071_U08ROTJF2A\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarHome.php","Line":170}

**Comment by amandabee** [comment]
I was having this issue with all calendars and all users and the latest version in the repository resolved it for me: <https://github.com/owncloud/calendar/issues/928>

What version of the calendar app are you using?

**Comment by deichy** [comment]
I'm using 0.7.3 too.
I alreay reinstalled the App yesterday but the problem still exists.

**Comment by 2edff206** [comment]
I am having exactly the same problem with calendar 0.7.3 and lightning. But android sync works fine ! Could you please try to solve this? Thanks a lot

**Comment by amandabee** [comment]
@2edff206 It seems like @deichy is having problems that are lightning only. They specifically say that the Android sync works fine.  So it sounds to me like you're encountering a different problem.

**Comment by j-ed** [comment]
After upgrading my server to ownCloud to v8.1.3 I realized exactly the same exception with calendar app v0.7.3 and iOS v8.4.1.

**Comment by pf17** [comment]
Hi, I use 8.1.3 and 0.7.3 ownCloud Calendar
Unfortunately, Sync is not working.
When I copy the calendar link and paste in the browser I get this messige: 

<d:error><s:sabredav-version>2.1.6</s:sabredav-version><s:exception>Sabre\DAVACL\Exception\NeedPrivileges</s:exception>
<s:message>User did not have the required privileges ({DAV:}read) for path "calendars/XXX/persönlich"</s:message><d:need-privileges><d:resource><d:href>/remote.php/caldav/calendars/XXX/persönlich</d:href><d:privilege><d:read/></d:privilege></d:resource></d:need-privileges></d:error>

**Comment by smaug95** [comment]
Hi, I am getting this issue too, but exclusively on the Mac (tested under 10.11.1 and 10.10.x), iOS 9.1 is totally ok. My setup is a fresh installed Owncloud 8.2.0 on Raspbian Jessie using nginx installed in the web root on a custom port. The initial sync worked and sometimes later events got synced too but most of the time I get the following error in the Calendar App:
```
The URL https://kalender.mydomain.at:8443/remote.php/caldav/principals/myuser/ encountered HTTP error 404. Make sure the URL is correct.
```
In the meantime the owncloud logs get flooded by these messages:
```
{"reqId":"bWVvKwsp2ZX27LWpCdH7","remoteAddr":"1.2.3.4","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-12T21:01:15+00:00","method":"OPTIONS","url":"\/remote.php\/caldav\/principals\/myuser\/"} 

{"reqId":"iwZLvvDk3tFb3vy+Gsfm","remoteAddr":"1.2.3.4","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-12T21:01:17+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/myuser\/"} 

{"reqId":"0hT7YFIgdjmMYQcKns2U","remoteAddr":"1.2.3.4","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-12T21:03:47+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/principals\/myuser\/"} 

{"reqId":"jI4LIBrsOM7mZqmJofq3","remoteAddr":"1.2.3.4","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-12T21:03:49+00:00","method":"REPORT","url":"\/remote.php\/caldav\/principals\/"} 

{"reqId":"PAU3eXymdHiYvWWbRQW7","remoteAddr":"1.2.3.4","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(Sabre\\\\DAV\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-12T21:03:51+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/myuser\/"} 

{"reqId":"GeYCRW34ik1WAJuDUEt5","remoteAddr":"1.2.3.4","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Node with name 'inbox' could not be found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/sabre\\\/usercalendars.php(47): Sabre\\\\CalDAV\\\\CalendarHome->getChild('inbox')\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\Calendar\\\\Sabre\\\\UserCalendars->getChild('inbox')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(920): Sabre\\\\DAV\\\\Tree->getNodeForPath('calendars\\\/myuser...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(327): Sabre\\\\DAV\\\\Server->getPropertiesForPath('calendars\\\/myuser...', Array, 0)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropfind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarHome.php\",\"Line\":170}","level":0,"time":"2015-11-12T21:04:13+00:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/myuser\/inbox\/"} 
```
The nginx log of a failed sync looks like this:
```
1.2.3.4 - - [10/Nov/2015:17:46:59 +0100] "PROPFIND /remote.php/caldav/principals/myuser/ HTTP/1.1" 401 303 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:00 +0100] "PROPFIND /remote.php/caldav/principals/myuser/ HTTP/1.1" 207 1752 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:00 +0100] "OPTIONS /remote.php/caldav/principals/myuser/ HTTP/1.1" 200 0 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - - [10/Nov/2015:17:47:01 +0100] "REPORT /remote.php/caldav/principals/ HTTP/1.1" 401 303 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:02 +0100] "REPORT /remote.php/caldav/principals/ HTTP/1.1" 200 608 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - - [10/Nov/2015:17:47:02 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/ HTTP/1.1" 401 303 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:03 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/ HTTP/1.1" 207 7721 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:04 +0100] "PROPPATCH /remote.php/caldav/calendars/myuser/ HTTP/1.1" 207 407 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:04 +0100] "PROPPATCH /remote.php/caldav/calendars/myuser/ HTTP/1.1" 207 411 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:05 +0100] "PROPPATCH /remote.php/caldav/calendars/myuser/privat/ HTTP/1.1" 207 406 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:06 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/ HTTP/1.1" 207 399 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:07 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/privat/ HTTP/1.1" 207 502 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:08 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/privat/ HTTP/1.1" 207 1386 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:11 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/inbox/ HTTP/1.1" 404 294 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:12 +0100] "PROPFIND /remote.php/caldav/principals/myuser/ HTTP/1.1" 207 580 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - myuser [10/Nov/2015:17:47:13 +0100] "PROPFIND /remote.php/caldav/principals/ HTTP/1.1" 207 574 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - - [10/Nov/2015:17:47:13 +0100] "PROPFIND / HTTP/1.1" 405 172 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
1.2.3.4 - - [10/Nov/2015:17:47:13 +0100] "PROPFIND /principals/ HTTP/1.1" 404 27 "-" "Mac+OS+X/10.11.1 (15B42) CalendarAgent/361"
```
... whereas a successful sync from iOS produces these logs:
```
1.2.3.4 - - [10/Nov/2015:17:48:15 +0100] "PROPFIND /remote.php/caldav/principals/myuser/ HTTP/1.1" 401 303 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
1.2.3.4 - myuser [10/Nov/2015:17:48:16 +0100] "PROPFIND /remote.php/caldav/principals/myuser/ HTTP/1.1" 207 1752 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
1.2.3.4 - myuser [10/Nov/2015:17:48:16 +0100] "OPTIONS /remote.php/caldav/principals/myuser/ HTTP/1.1" 200 0 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
1.2.3.4 - - [10/Nov/2015:17:48:16 +0100] "REPORT /remote.php/caldav/principals/ HTTP/1.1" 401 303 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
1.2.3.4 - myuser [10/Nov/2015:17:48:17 +0100] "REPORT /remote.php/caldav/principals/ HTTP/1.1" 200 608 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
1.2.3.4 - - [10/Nov/2015:17:48:17 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/ HTTP/1.1" 401 303 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
1.2.3.4 - myuser [10/Nov/2015:17:48:17 +0100] "PROPFIND /remote.php/caldav/calendars/myuser/ HTTP/1.1" 207 7684 "-" "iOS/9.1 (13B143) dataaccessd/1.0"
```

I believe this is the same issue and would really need a patch because caldav sync on the Mac is important to me. Has anyone a solution for this?
