### ISSUE TITLE
Error 500 when doing calendar-multiget for nonexistent hrefs

### ISSUE THREAD

**Issue by untitaker** [owncloud/calendar#935]
*ownCloud 8.1.3, possibly since 8.1.1*

    $ cat | http --auth asdf:asdf report http://127.0.0.1:8080/remote.php/caldav/calendars/asdf/test/
    <?xml version="1.0" encoding="utf-8" ?>
            <C:calendar-multiget xmlns:D="DAV:"
                xmlns:C="urn:ietf:params:xml:ns:caldav">
                <D:prop>
                    <D:getetag/>
                    <C:calendar-data/>
                </D:prop>
                <D:href>/remote.php/caldav/calendars/asdf/test/0.8003376417345851.ics</D:href>
            </C:calendar-multiget>
    HTTP/1.1 500 Internal Server Error
    Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
    Connection: close
    Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:;
    media-src *; connect-src *
    Content-Type: application/xml; charset=utf-8
    Expires: Thu, 19 Nov 1981 08:52:00 GMT
    Host: 127.0.0.1:8080
    Pragma: no-cache
    Set-Cookie: oc6vzxemf45u=99731cfec4ad2e18dda8e7dccfffc0e1; path=/; HttpOnly
    X-Content-Type-Options: nosniff
    X-Frame-Options: Sameorigin
    X-Powered-By: PHP/5.6.13
    X-Robots-Tag: none
    X-Sabre-Version: 2.1.6
    X-XSS-Protection: 1; mode=block

    <?xml version="1.0" encoding="utf-8"?>
    <ns0:error xmlns:ns0="DAV:" xmlns:ns1="http://sabredav.org/ns">
        <ns1:sabredav-version>2.1.6</ns1:sabredav-version>
        <ns1:exception>InvalidArgumentException</ns1:exception>
        <ns1:message>The objectData argument must contain an 'uri' property</ns1:message>
    </ns0:error>

I expect the server to return a multistatus object with a 404 error for this particular href.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md)

**Comment by georgehrke** [comment]
if the server throws an 500, there is most likely something in the server error log that would tremendously help us ....

**Comment by untitaker** [comment]
Edited to fit the template.

You're right, I forgot. This is in the PHP server log:

    {"reqId":"iwOTGvitlOt68LHPyRDN","remoteAddr":"127.0.0.1","app":"caldav","message":"Exception: {\"Message\":\"The objectData argument must contain an 'uri' property\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/apps\\\/calendar\\\/lib\\\/sabre\\\/calendar.php(144): Sabre\\\\CalDAV\\\\CalendarObject->__construct(Object(OC_Connector_Sabre_CalDAV), Array, false)\\n#1 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(270): OC_Connector_Sabre_CalDAV_Calendar->getMultipleChildren(Array)\\n#2 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(977): Sabre\\\\DAV\\\\Tree->getMultipleNodes(Array)\\n#3 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(464): Sabre\\\\DAV\\\\Server->getPropertiesForMultiplePaths(Array, Array)\\n#4 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(228): Sabre\\\\CalDAV\\\\Plugin->calendarMultiGetReport(Object(DOMDocument))\\n#5 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/asdf\\\/...')\\n#6 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server. php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#11 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/remote.php(132): require_once('\\\/home\\\/untitaker...')\\n#14 {main}\",\"File\":\"\\\/home\\\/untitaker\\\/projects\\\/owncloud-testserver\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarObject.php\",\"Line\":58}","level":4,"time":"2015-09-17T09:51:43+00:00"}

**Comment by untitaker** [comment]
I don't have such an issue with carddav, so I guess it's not a regression in core like https://github.com/owncloud/core/issues/18409

**Comment by gvde** [comment]
There should be another error message in the log:

> {"reqId":"B12ZwxBI1yQBXH8FDeUZ","remoteAddr":"x.x.x.x","app":"PHP","message":"Argument 3 passed to Sabre\\CalDAV\\CalendarObject::__construct() must be of the type array, boolean given, called in \/var\/www\/owncloud\/apps\/calendar\/lib\/sabre\/calendar.php on line 147 and defined at \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CalDAV\/CalendarObject.php#53","level":3,"time":"2015-09-17T11:39:37+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/caldav\/calendars\/gvde\/personal\/"}

I think this is in its core a sabre caldav problem. The getMultipleChildren() function overwrites the original to get the custom ACLs in. It's basically identical to what the original sabredav function does. In other words: even a plain sabredav server should show the same problem. It calls getCalendarObject which returns null or false if not found. The getMultipleChildren could check whether $obj is in deed an array (and contains a 'uri' value). But so should the sabredav original then. So it may be worth checking the sabredav server and possibly open an issue with them...

But maybe I have missed an essential difference between the sabredav and oc calendars backend which causes the false or null return to be handled differently somewhere else I haven't looked, yet...

**Comment by untitaker** [comment]
This bug hasn't happened with ownCloud 8.0, so it must have been introduced as part of a SabreDAV upgrade.

I'll roll back some versions and see which version first had this issue.

**Comment by untitaker** [comment]
The issue has been introduced somewhere between 8.0.4 and 8.1.1. Unfortunately I skipped a few updates there.

**Comment by gvde** [comment]
That makes sense. oc 8.0.4 to 8.1.1 upgraded sabredav from 1.8 to 2.1. And if I am not mistaken the support for getMultipleChildren was introduced with 2.1...

**Comment by untitaker** [comment]
The really weird thing though is that CardDAV doesn't seem to be affected at all. Neither a PROPFIND nor a `addressbook-multiget` fails the same way, while the default implementation for `getMultipleChildren` seems to be the same.

**Comment by gvde** [comment]
Well, the constructor for the Card class doesn't check anything while the constructor for CalendarObject checks for 'uri' in the cardData parameter. So I guess, CardDAV isn't yet "affected" but of course it wouldn't be bad to check whether the constructor really gets an array passed if it expects an array to be passed...

**Comment by gvde** [comment]
Wrote it and then just saw this which contains the error for the Card constructor: contacts#1050
So it does happen there, too...

**Comment by untitaker** [comment]
Weird, I couldn't reproduce this by modifying the above test script.

On 17 September 2015 15:09:38 CEST, Gerald Vogt <notifications@github.com> wrote:
>Wrote it and then just saw this which contains the error for the Card
>constructor: contacts#1050
>So it does happen there, too...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/935#issuecomment-141077830

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment]
This seems to be a different issue. The error message is the same, but the actual bug there is that items with curly braces in their UID aren't found. So returning false is the actual bug there, as opposed to not handling false correctly.

On 17 September 2015 15:09:38 CEST, Gerald Vogt <notifications@github.com> wrote:
>Wrote it and then just saw this which contains the error for the Card
>constructor: contacts#1050
>So it does happen there, too...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/calendar/issues/935#issuecomment-141077830

-- 
Sent from my phone. Please excuse my brevity.

**Comment by gvde** [comment]
Well, yes and no. Of course, it's a different issues with those curly braces. On the other hand, it's shows a systematic problem with sabredav: it doesn't find any matching card or calendarobject, still calls the constructor with a boolean instead of a array as the third parameter. The Card and CalendarObject classes both require it's an array which is passed.

CalendarObject throws an exception because of the missing 'uri' index which causes the 500 error.

Card doesn't check it any further and does not throw an exception. But of course, the created object is flawed in many ways and side-effects could create various other problems. Just look into sabres Card.php file (3rdparty/sabre/dav/lib/CardDAV/Card.php) at all the places where cardData is used and check what happens if there is a boolean and no error in cardData...

From the design it is now I suspect the way to go would be to prevent creating those objects if nothing has been found as assertions in those classes wouldn't help much and the PHP type checks show those errors anyway.

So I suppose the best approach would be to make sure those objects are only created when it's actually something there to do, i.e. there is cardData or objectData.

But again: I think that would also affect the sabredav original code. I guess I need to find a way to verify the problem with a plain simple sabredav server to rule out it's not the owncloud calendar app's backend which messes something up...

**Comment by untitaker** [comment]
Hey @evert is there something we're missing or could this really be an issue in SabreDAV? I'd be glad to author a patch.

**Comment by evert** [comment]
I agree that this is a sabre/dav bug. `Sabre\CalDAV\Calendar::getMultipleChildren()` needs to check the result for each iteration of `getCalendarObject` and don't do anything when that method returns null.

**Comment by gvde** [comment]
> I agree that this is a sabre/dav bug. Sabre\CalDAV\Calendar::getMultipleChildren() needs to check the result for each iteration of getCalendarObject and don't do anything when that method returns null.

getMultipleCalendarObjects() puts in "false" for objects it doesn't find. I have tried to check (put a "if ($obj)" before creating OC_Connector_Sabre_CalDAV_CalendarObject at the bottom of calendar.php) but the problem with that seems to be that sabre won't add anything into the multiget response. That of course will break it because a multi-get report must contain a result for all objects requested...

**Comment by untitaker** [comment]
I think both parties are at fault, I don't see why it's valid for `getCalendarObject` to return `false` instead of `null`: https://github.com/fruux/sabre-dav/blob/b7a702f/lib/CalDAV/Backend/PDO.php#L381-L383

**Comment by gvde** [comment]
But it doesn't matter whether it returns false or null: either way the CalendarObject assumes an array as third parameter but gets that false or null value passed instead. Of course, that's easily checked and would comply to the current description "If any children are not found, you do not have to return them.".

But that isn't all. Doing so will not create a multi-get response for the objects requested which, however, is required even if it's a not found response. Thus, I think the sabre function handling the multi-get request using the getMultipleChildren() function to find the objects would have to add those missing responses which it doesn't seem to do at the moment...

**Comment by schiesbn** [comment]
I also can't sync my calendar since I updated to oC8.1.4 and at the same time did a git pull on the calendar repository.

This is in my apache error.log:

````
88.67.48.176 - schiesbn [07/Oct/2015:14:40:01 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5533 "-" "Mozilla/5.0 (Linux) mirall/2.0.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:01 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/shared_calendar/ HTTP/1.1" 207 33574 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:05 +0200] "PROPFIND /remote.php/caldav/calendars/schiesbn/calendar1/ HTTP/1.1" 207 1738 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:05 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/calendar1/ HTTP/1.1" 207 10382 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:06 +0200] "PROPFIND /remote.php/caldav/calendars/schiesbn/calendar2/ HTTP/1.1" 207 1738 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:07 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/calendar2/ HTTP/1.1" 207 19815 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:09 +0200] "PROPFIND /remote.php/caldav/calendars/schiesbn/defaultcalendar/ HTTP/1.1" 207 1738 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:10 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/defaultcalendar/ HTTP/1.1" 500 1098 "-" "DAVdroid/0.8.4.1"
````

and this can be found in my ownCloud log:

````
{"reqId":"CHJNlE+Roha7wGTGvHkS","remoteAddr":"88.67.48.176","app":"caldav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(168): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('1', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(635): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/schie...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/appsSelected\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-10-07T12:42:07+00:00"}
````

Not the same error message as posted by other but still looks like the same, or at least a similiar, issue.

**Comment by rbarlow** [comment]
I believe I have been seeing this error with Thunderbird's Lightning plugin when accepting event invitations from others. At least, I see the "The objectData argument must contain an 'uri' property" error message when I client "Accept" in Lightning.

**Comment by untitaker** [comment]
needsinfo should be removed from this issue IMO

**Comment by untitaker** [comment]
FWIW this is no longer a problem with the new calendar app in ownCloud 9, but I'm leaving this open anyway.
