### ISSUE TITLE
sync failed but only for one specific calendar

### ISSUE THREAD

**Issue by schiesbn** [owncloud/calendar#947]
I have multiple local calendars and shared calendars. Since about a week the "defaultcalendar" stopped syncing. I don't know exactly when it happened, but I assume that it is broken since I updated to oC8.1.4 and did a git pull on the calendar stable8.1 branch. This are my logs if my mobile phone tries to sync the calendars.

apache error.log:

````
88.67.48.176 - schiesbn [07/Oct/2015:14:40:01 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 5533 "-" "Mozilla/5.0 (Linux) mirall/2.0.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:01 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/shared_calendar/ HTTP/1.1" 207 33574 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:05 +0200] "PROPFIND /remote.php/caldav/calendars/schiesbn/calendar1/ HTTP/1.1" 207 1738 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:05 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/calendar1/ HTTP/1.1" 207 10382 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:06 +0200] "PROPFIND /remote.php/caldav/calendars/schiesbn/calendar2/ HTTP/1.1" 207 1738 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:07 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/calendar2/ HTTP/1.1" 207 19815 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:09 +0200] "PROPFIND /remote.php/caldav/calendars/schiesbn/defaultcalendar/ HTTP/1.1" 207 1738 "-" "DAVdroid/0.8.4.1"
88.67.48.176 - schiesbn [07/Oct/2015:14:40:10 +0200] "REPORT /remote.php/caldav/calendars/schiesbn/defaultcalendar/ HTTP/1.1" 500 1098 "-" "DAVdroid/0.8.4.1"
````

ownCloud log:

````
{"reqId":"CHJNlE+Roha7wGTGvHkS","remoteAddr":"88.67.48.176","app":"caldav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(168): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(115): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(427): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->calendarQuery('1', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(635): Sabre\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/schie...')\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#12 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#14 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#15 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/var\\\/www\\\/owncloud\\\/appsSelected\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#17 \\\/var\\\/www\\\/owncloud\\\/remote.php(132): require_once('\\\/var\\\/www\\\/ownclo...')\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-10-07T12:42:07+00:00"}
````

Any idea what's wrong here?

**Comment by gvde** [comment]
Search before posting... #680 #861 #878  all on the identical error message...

**Comment by schiesbn** [comment]
I think not all of them identical. E.g. I didn't had a Authorization issue. But this solved it for me: https://github.com/owncloud/calendar/issues/861#issuecomment-135710442
