### ISSUE TITLE
HTTP error 500 and End of document reached prematurely\

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/calendar#955]
Using CalDAV from MAC OSX 10.9.5, it gives 500 for REPORT requests. Here is the oC log:

{"reqId":"FqdQw577+\/xqL7H0ggER","remoteAddr":"192.168.0.50","app":"caldav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(168): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(137): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('BEGIN:VEVENT')\\n#2 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#3 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#4 \\\/var\\\/www\\\/oc/\\\/apps3\\\/calendar\\\/lib\\\/sabre\\\/backend.php(368): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#5 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(54): OC_Connector_Sabre_CalDAV->getCalendarObject('7272', '12F33821-C3C2-4...')\\n#6 [internal function]: Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->Sabre\\\\CalDAV\\\\Backend\\\\{closure}('12F33821-C3C2-4...')\\n#7 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(55): array_map(Object(Closure), Array)\\n#8 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(145): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->getMultipleCalendarObjects('7272', Array)\\n#9 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(270): Sabre\\\\CalDAV\\\\Calendar->getMultipleChildren(Array)\\n#10 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(977): Sabre\\\\DAV\\\\Tree->getMultipleNodes(Array)\\n#11 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(464): Sabre\\\\DAV\\\\Server->getPropertiesForMultiplePaths(Array, Array)\\n#12 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(228): Sabre\\\\CalDAV\\\\Plugin->calendarMultiGetReport(Object(DOMDocument))\\n#13 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/gwenb...')\\n#14 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(705): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#16 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#17 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#18 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#19 \\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#20 \\\/var\\\/www\\\/oc/\\\/apps3\\\/calendar\\\/appinfo\\\/remote.php(57): Sabre\\\\DAV\\\\Server->exec()\\n#21 \\\/var\\\/www\\\/oc/\\\/remote.php(132): require_once('\\\/var\\\/www\\\/vhosts...')\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/oc/\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-10-15T09:26:39+00:00"}

oC version 8.1.1.

@georgehrke

**Comment by georgehrke** [comment]
is it so hard to use the issue template? 
........

**Comment by fossxplorer** [comment]
### Steps to reproduce
Sync calendar from MAC OSX? to calendar on  oC8.1.1 


### Expected behaviour
Able to sync calendars


### Actual behaviour
Unable to sync calendars

### Server configuration
**Operating system**:
CentOS 6.7

**Web server:**
Nginx reverse proxy and Apache 2.2

**Database:**
MariaDB 10

**PHP version:**
5.4.41

**ownCloud version:** (see ownCloud admin page)
 8.1.1

**Updated from an older ownCloud or fresh install:**

**List of activated apps:**
Enabled:
  - activity: 2.1.2
  - calendar: 0.7.3
  - contacts: 0.4.0.0
  - documents: 0.10.1
  - files: 1.1.11
  - files_external: 0.2.3
  - files_pdfviewer: 0.7
  - files_sharing: 0.6.3
  - files_texteditor: 0.4
  - files_versions: 1.0.6
  - firstrunwizard: 1.1
  - notes: 1.1.0




**The content of config/config.php:**



**Are you using external storage, if yes which one:** local/smb/sftp/...
~~Google Drive~~
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No


### Client configuration
**Browser:**
Firefox, Chrome

**Operating system:**
CentOS 6.7

**Comment by gvde** [comment]
> Sync calendar from MAC OSX? to calendar on oC8.1.1
>...
> Server configuration
> Operating system:
> CentOS 6.7
>...
> Client configuration
> Browser:
> Firefox, Chrome
> 
> Operating system:
> CentOS 6.7

So your server is Cent OS 6.7, you use Firefox and Chrome on CentOS 6.7 as client. Where do you use CalDAV and what does that have to do with OS X?

Did you check existing issues, e.g. #811?

**Comment by fossxplorer** [comment]
Updated. The client is Calendar on OSX.
