### ISSUE TITLE
Mac OS X Calendar.app reports error after upgrade to OC 8.2

### ISSUE THREAD

**Issue by ilpssun** [owncloud/calendar#965]
### Steps to reproduce
1. Upgrade working CalDav setup (Mac OS 10.10.5, OC 8.1) to OC 8.2
2. Open Mac OS Calendar.app and sync calendars with OC server

### Expected behaviour
It should work as before (syncing all calendar events) without the error message.

### Actual behaviour
Calendar.app display error message and does not sync correctly:
“Server reports an error:
The URL https://my-domain.de/owncloud/remote.php/caldav/principals/username/ caused the following HTTP error: 404. Please make sure the URL is correct.”

I tried applying the redirect rules for the `.well-known`-URLs but this did not remove the error.  I believe it's related to the Calendar.app making a request to `PROPFIND /` which is forbidden (see apache log below).  IMO this seems to be related to issue https://github.com/owncloud/contacts/issues/1058 where a similar problem for CardDav + Mac OS 10.10 is discussed.  Possibly a Mac OS bug, not OC, but – as I said – it worked before ... 

### Server configuration
**Operating system:** Ubuntu 14.04.3 LTS

**Web server:** 2.4.7-1ubuntu4.8

**Database:** 5.5.44-0ubuntu0.14.04.1

**PHP version:** 5.5.9+dfsg-1ubuntu4.13

**ownCloud version:** 8.2.0

**Updated from an older ownCloud or fresh install:** Update using repository

**List of activated apps:**
```
Enabled:
  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - files: 1.2.0
  - files_locking:
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - firstrunwizard: 1.1
  - gallery: 14.2.0
  - provisioning_api: 0.3.0
  - templateeditor: 0.1
Disabled:
  - encryption
  - external
  - files_external
  - notifications
  - updater
  - user_external
  - user_ldap
```

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "ocaif6cv6l9l",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my-domain.de"
        ],
        "datadirectory": "\/var\/owncloud-data",
        "overwrite.cli.url": "https:\/\/my-domain.de\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "owncloud",
        "mail_domain": "my-domain.de",
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto"
    }
}
```

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** irrelevant

**Operating system:** Mac OS 10.10.5

#### Web server error log
```
188.109.yy.xx - till [23/Oct/2015:09:57:10 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/till/ HTTP/1.1" 207 1818 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - till [23/Oct/2015:09:57:10 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/till/contact_birthdays/ HTTP/1.1" 207 1946 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - till [23/Oct/2015:09:57:10 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/till/contact_birthdays/ HTTP/1.1" 207 1850 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - till [23/Oct/2015:09:57:11 +0200] "PROPFIND /owncloud/remote.php/caldav/calendars/till/inbox/ HTTP/1.1" 404 1530 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - till [23/Oct/2015:09:57:11 +0200] "PROPFIND /owncloud/remote.php/caldav/principals/till/ HTTP/1.1" 207 2026 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - till [23/Oct/2015:09:57:11 +0200] "PROPFIND /owncloud/remote.php/caldav/principals/ HTTP/1.1" 207 2010 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - - [23/Oct/2015:09:57:11 +0200] "PROPFIND / HTTP/1.1" 405 714 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - - [23/Oct/2015:09:57:11 +0200] "PROPFIND /principals/ HTTP/1.1" 405 714 "-" "Mac+OS+X/10.10.5 (14F1021) CalendarAgent/316.1"
188.109.yy.xx - till [23/Oct/2015:09:57:11 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 19607 "-" "Mozilla/5.0 (Macintosh) mirall/2.0.1"
188.109.yy.xx - till [23/Oct/2015:09:57:21 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1331 "-" "Mozilla/5.0 (Macintosh) mirall/2.0.1"
188.109.yy.xx - till [23/Oct/2015:09:57:41 +0200] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 19607 "-" "Mozilla/5.0 (Macintosh) mirall/2.0.1"
```

#### ownCloud log (data/owncloud.log)
The only possibly relevant entry I could find:
```
{"reqId":"xIK6XZhdv\/TPgTsuVdtB","remoteAddr":"188.109.yy.xx","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no handler found for this \\\"GET\\\" method\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotImplemented\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/ownclo...')\\n#3 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":472}","level":4,"time":"2015-10-21T16:02:58+00:00"}
```
I believe this is an error that was due to me not having activated the OC calendar app after the upgrade to OC 8.2.
When generating the error message in Calendar.app, no entries in `owncloud.log` are generated.

#### Browser log
irrelevant

**Comment by gvde** [comment]
Dup of #962?

**Comment by georgehrke** [comment]
> Dup of #962?

possible, not sure though

**Comment by gvde** [comment]
The 404 is for /inbox/

Did you try the workaround from #962?

**Comment by ilpssun** [comment]
It's indeed a duplicate. I was misled by the 405 error and did not catch the 404 on `inbox`. Sorry :-)

The workaround from #962 works for me, too.

**Comment by joernhees** [comment]
found this after updating to owncloud 8.2.0 and having exactly the same problems... could you maybe release this soon?
