### ISSUE TITLE
Colors set by iCal get overwritten by OC

### ISSUE THREAD

**Issue by thetrial** [owncloud/calendar#977]
Once, I remember, I could set a calender color in iCal. Now this does not work anymore. I set »red«, it becomes something different, default blue. And in OC I can choose another »red« that is not the same. Very strange.

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/owncloud/core/master/issue_template.md) as described in our [contributing guidelines](https://github.com/owncloud/core/blob/master/CONTRIBUTING.md) ...

Seriously, bug reports like this are completely useless. You didn't even mention a version number ... :disappointed:

**Comment by thetrial** [comment]
That’s because of my anger! :-( Wait, follows …

**Comment by jospoortvliet** [comment]
Anger leads to the dark side, @thetrial - careful ;-)

@georgehrke you seem angry, too... Be sweet, we're all friends!

**Comment by thetrial** [comment]
### Steps to reproduce
1. Update OC from 8.1 to 8.2
2. Create a new calendar in iCal 5.0.3 under OSX 10.7.5
3. Assign a dark red color

### Expected behaviour
The new calendar should have this assigned color. This was the behaviour before. And, the calendar should show in all other devices with this assigned color.

### Actual behaviour
In iCal itself the color gets »forgotten« and defaults to blue. If I then set a color via OC, this color remains and is spread to all devices via caldav. But – I have to use the light red, I cannot use a dark red, for instance.

### Server configuration
**Operating system**: Raspbian 8

**Web server:** Apache 2.4

**Database:** sqlite

**PHP version:** 5.6

**ownCloud version:** 8.2

**Updated from an older ownCloud or fresh install:** Update from 8.1

**List of activated apps:**

  - activity: 2.1.3
  - calendar: 0.8.0
  - contacts: 0.5.0.0
  - encryption: 1.1.0
  - files: 1.2.0
  - files_locking:
  - files_trashbin: 0.7.0
  - updater: 0.6

**The content of config/config.php:**

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

Ehm …   »[RuntimeException]
  The "--public" option does not exist.«

or 

$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'datadirectory' => '/var/anotherplace/data',
  'dbtype' => 'sqlite3',
  'version' => '8.2.0.12',
  'installed' => true,
  'default_language' => 'de',
  'forcessl' => true,
  'maxZipInputSize' => 0,
  'allowZipDownload' => true,
  'theme' => '',
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'loglevel' => 2,
  'trusted_domains' =>
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'overwrite.cli.url' => 'xxx',
  'overwritewebroot' => 'xxx',
  'check_for_working_htaccess' => true,
   'logtimezone' => 'Europe/Berlin',
  'mail_from_address' => 'xxx',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxx',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => 'xxx',
  'mail_smtpport' => 'xxx',
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'secret' => 'xxx
  'singleuser' => false,
);

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** iCab 5, but in this case: iCal 5.0.3

**Operating system:** OSX 10.7.5

### Logs
#### Web server error log
Nothing interesting there

#### ownCloud log (data/owncloud.log)

That’s too big. The last lines:

{"reqId":"+R55IcdysWWP1UcsJEPZ","remoteAddr":"192.168.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Syncfolder\\\/Somethingtosync\\\/TheFileThatShouldBeSynced\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #26)\\n#1 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('Syncfolder\\\/XYZ...', Resource id #26, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/xyz\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/xyz\\\/remote.php(137): require_once('\\\/var\\\/www\\\/xyz\\\/...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/xyz\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":164}","level":4,"time":"2015-11-04T17:50:57+01:00"}
{"reqId":"LPYLAefvKmNLklfSwdzj","remoteAddr":"192.168.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Syncfolder\\\/MTSync\\\/TheFileThatShouldBeSynced\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #26)\\n#1 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('Syncfolder\\\/MTSync', Resource id #26, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/xyz\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/xyz\\\/remote.php(137): require_once('\\\/var\\\/www\\\/xyz\\\/...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/xyz\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":164}","level":4,"time":"2015-11-04T17:51:08+01:00"}
{"reqId":"eMG4WgO5zhAi1ydoDbY8","remoteAddr":"192.168.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Syncfolder\\\/MTSync\\\/TheFileThatShouldBeSynced\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #26)\\n#1 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('Syncfolder\\\/MTSync', Resource id #26, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/xyz\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/xyz\\\/remote.php(137): require_once('\\\/var\\\/www\\\/xyz\\\/...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/xyz\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":164}","level":4,"time":"2015-11-04T17:51:22+01:00"}
{"reqId":"PK\/eSzVQDYqBxlUxG4\/6","remoteAddr":"192.168.XXX.XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Syncfolder\\\/MTSync\\\/TheFileThatShouldBeSynced\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #26)\\n#1 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('Syncfolder\\\/MTSync', Resource id #26, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/xyz\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6  \\\/var\\\/www\\\/xyz\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/xyz\\\/remote.php(137): require_once('\\\/var\\\/www\\\/xyz\\\/...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/xyz\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":164}","level":4,"time":"2015-11-04T17:51:49+01:00"}
{"reqId":"u\/6P+PgR\/u7qaAg+UvLn","remoteAddr":"192.168.XXX.XXX","app":"PHP","message":"Array to string conversion at \/var\/www\/xyz\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-11-04T18:50:33+01:00"}

#### Browser log

No browser issue.

**Comment by hylkepylke** [comment]
I can confirm this issue, running OC 8.2.0 with calendar plugin 0.8.0, syncing on Mac OS X 10.10.1.

**Comment by TheKoon** [comment]
+1 !!!
