### ISSUE TITLE
Disable “Contact birthdays” calender in CardDAV

### ISSUE THREAD

**Issue by nicokaiser** [owncloud/calendar#986]
### Steps to reproduce
1. Add some contacts with birthdays
2. Add CardDAV URL to OS X Calendar.app
3. Move or change one of the automatic birthday entries in the calendar

### Expected behaviour
First, there should be a configuration option to disable the "Contact birthdays" calendar in CardDAV. And, when an entry in this – read only – calendar is changed, ownCloud should accept this change and silently ignore/revert it, in order to prevent sync conflicts.

If you additionally subscribe the ownCloud contacts via CardDAV, OS X already shows their birthdays in the Calendar, so you already see them twice (one from Contacts.app and the other from the automatic “Contact birthdays” calendar.

### Actual behaviour
If you accidentally move or change one of the entries in “Contact birthdays”, the change cannot be synced to the server and you get sync errors. In some cases you can “Revert to server”, but in some I had to remove and re-add the account.

### Server configuration
**Operating system**: Linux

**Web server:** nginx

**Database:** MySQL

**PHP version:** 5.5

**ownCloud version:** (see ownCloud admin page) 8.2

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:**

```
  - activity: 2.1.3
  - bookmarks: 0.4
  - calendar: 0.8.1
  - contacts: 0.5.0.0
  - files: 1.1.10
  - files_sharing: 0.6.2
  - files_texteditor: 2.0
  - files_trashbin: 0.6.3
  - files_versions: 1.0.6
  - firstrunwizard: 1.1
  - gallery: 0.6.0
  - news: 6.1.0
  - tasks: 0.8
  - updater: 0.6
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "8.2.0.12",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appcodechecker": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.mandrillapp.com",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "enable_previews": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** any

**Operating system:** OS X

#### ownCloud log (data/owncloud.log)
```
{"reqId":"0URrJ1lDVi+YRu5LnW73","remoteAddr":"80.190.141.50","app":"caldav","message":"Exception: {\"Message\":\"Error reading from input stream\",\"Exception\":\"Sabre\\\\VObject\\\\ParseException\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(102): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse(NULL, 0)\\n#3 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/apps\\\/calendar\\\/lib\\\/object.php(249): Sabre\\\\VObject\\\\Reader::read(NULL)\\n#4 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/apps\\\/calendar\\\/lib\\\/sabre\\\/backend.php(410): OC_Calendar_Object::editFromDAVData('contact_birthda...', 'local::3::72.ic...', 'BEGIN:VCALENDAR...')\\n#5 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarObject.php(104): OCA\\\\Calendar\\\\Sabre\\\\Backend->updateCalendarObject('contact_birthda...', 'local::3::72.ic...', 'BEGIN:VCALENDAR...')\\n#6 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1087): Sabre\\\\CalDAV\\\\CalendarObject->put('BEGIN:VCALENDAR...')\\n#7 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(501): Sabre\\\\DAV\\\\Server->updateFile('calendars\\\/nico\\\/...', Resource id #30, NULL)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#11 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/srv\\\/www\\\/cloud.____\\\/public\\\/remote.php(137): require_once('\\\/srv\\\/www\\\/cloud....')\\n#14 {main}\",\"File\":\"\\\/srv\\\/www\\\/cloud.____\\\/public\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":253}","level":4,"time":"2015-11-13T08:06:43+00:00"}
```

**Comment by RealRancor** [comment]
@nicokaiser Please see https://github.com/owncloud/calendar/blob/master/CONTRIBUTING.md#faq

There you can see an existing issue to disable the birthday calendar: https://github.com/owncloud/calendar/issues/21
