### ISSUE TITLE
"End of document reached prematurely" accessing new and empty calendar

### ISSUE THREAD

**Issue by floecksche** [owncloud/calendar#997]
### Steps to reproduce
1. Create a new calendar, which will be empty by default
2. Using the Python caldav module, execute a script like this to query the calendar app (note that 0 is the id of newly created calendar):

import caldav
import datetime

calDAVurl = "https://user:password@tld/owncloud/remote.php/caldav/"
client = caldav.DAVClient(calDAVurl)
calendar = client.principal().calendars()[0]
startDate = datetime.datetime(2015, 12, 14, 0, 0, 0)
endDate = datetime.datetime(2015, 12, 14, 23, 59, 59)
events = calendar.date_search(startDate, endDate)

### Expected behaviour
I would expect a valid answer from the server, but I get the error message below instead.

### Actual behaviour
This is the server response:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>2.1.7</s:sabredav-version>
  <s:exception>Sabre\VObject\EofException</s:exception>
  <s:message>End of document reached prematurely</s:message>
</d:error>

### Server configuration
CentOS release 6.7

**Web server:**
Apache/2.2.15 (CentOS)

**Database:**
MySQL 5.1.73

**PHP version:**
PHP 5.5.9

**ownCloud version:** (see ownCloud admin page)
ownCloud 8.2.1 (stable) 

**Updated from an older ownCloud or fresh install:**
Updated

**List of activated apps:**
Default encryption module 1.1.0
Deleted files 0.7.0
External Sites 1.2
External storage support 0.3.0
First Run Wizard 1.1
Gallery 14.2.0
Mail Template Editor 0.1
PDF Viewer 0.7
Share Files 0.7.0
Text Editor 2.0
Updater 0.6
Video Viewer 0.1.3
Bookmarks 0.6
Calendar 0.8.1
Contacts 0.5.0.0

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'xyz',
  'passwordsalt' => 'xyz',
  'trusted_domains' => 
  array (
    0 => 'tld1',
    1 => 'tld2',
  ),
  'datadirectory' => '/home/xyz/owncloudData',
  'dbtype' => 'mysql',
  'version' => '8.2.1.4',
  'dbname' => 'xyz',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xyz',
  'dbpassword' => 'xyz',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'tld',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'maintenance' => false,
  'loglevel' => 3,
  'theme' => '',
  'secret' => 'xyz',
  'trashbin_retention_obligation' => 'auto',
);

**Are you using encryption:** yes/no
yes

### Client configuration
Executing Python script mentioned above

#### Web server error log

[Thu Dec 03 05:11:36 2015] [error] [client 176.114.189.49] File does not exist: /var/www/virtual/xyz/html/administrator
[Thu Dec 03 05:11:36 2015] [error] [client 176.114.189.49] File does not exist: /var/www/virtual/xyz/html/administrator
[Thu Dec 03 05:13:51 2015] [error] [client 95.83.190.227] File does not exist: /var/www/virtual/xyz/html/administrator
[Thu Dec 03 05:13:52 2015] [error] [client 95.83.190.227] File does not exist: /var/www/virtual/xyz/html/administrator
[Thu Dec 03 05:17:05 2015] [error] [client 176.114.189.49] File does not exist: /var/www/virtual/xyz/html/wp-login.php
[Thu Dec 03 05:17:05 2015] [error] [client 176.114.189.49] File does not exist: /var/www/virtual/xyz/html/wp-admin
[Thu Dec 03 05:17:35 2015] [error] [client 176.114.189.49] File does not exist: /var/www/virtual/xyz/html/admin.php
[Thu Dec 03 05:17:59 2015] [error] [client 95.83.190.227] File does not exist: /var/www/virtual/xyz/html/wp-login.php
[Thu Dec 03 05:18:00 2015] [error] [client 95.83.190.227] File does not exist: /var/www/virtual/xyz/html/wp-admin
[Thu Dec 03 05:18:27 2015] [error] [client 95.83.190.227] File does not exist: /var/www/virtual/xyz/html/admin.php
[Thu Dec 03 09:59:02 2015] [error] [client 212.60.253.106] File does not exist: /var/www/virtual/xyz/html/favicon.ico
[Thu Dec 03 10:01:26 2015] [error] [client 212.60.253.106] File does not exist: /var/www/virtual/xyz/html/favicon.ico
[Thu Dec 03 10:28:10 2015] [error] [client 212.60.253.106] File does not exist: /var/www/virtual/xyz/html/favicon.ico
[Thu Dec 03 10:28:10 2015] [error] [client 212.60.253.106] File does not exist: /var/www/virtual/xyz/html/favicon.ico
[Thu Dec 03 10:30:57 2015] [error] [client 212.60.253.106] File does not exist: /var/www/virtual/xyz/html/favicon.ico
[Thu Dec 03 10:30:57 2015] [error] [client 212.60.253.106] File does not exist: /var/www/virtual/xyz/html/favicon.ico
[Thu Dec 03 10:44:13 2015] [error] [client 2001:1a50:11:0:5f:8f:acb2:18a] File does not exist: /var/www/virtual/xyz/html/owncloud/data
[Thu Dec 03 10:46:06 2015] [error] [client 2001:1a50:11:0:5f:8f:acb2:18a] File does not exist: /var/www/virtual/xyz/html/owncloud/data
[Thu Dec 03 11:45:29 2015] [error] [client 23.95.43.107] Directory index forbidden by Options directive: /var/www/virtual/xyz/html/
[Thu Dec 03 13:11:07 2015] [error] [client 2001:1a50:11:0:5f:8f:acb2:18a] File does not exist: /var/www/virtual/xyz/html/owncloud/data

#### ownCloud log (data/owncloud.log)
{"reqId":"aAQfWBl6Sut9QIWW9VHe","remoteAddr":"2.240.69.165","app":"caldav","message":"Exception: {\"Message\":\"End of document reached prematurely\",\"Exception\":\"Sabre\\\\VObject\\\\EofException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(102): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readLine()\\n#1 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(63): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#2 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(44): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('', 0)\\n#3 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(548): Sabre\\\\VObject\\\\Reader::read('')\\n#4 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(232): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(DOMDocument))\\n#5 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(DOMDocument), 'calendars\\\/homem...')\\n#6 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(710): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#8 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#10 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#11 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/apps\\\/calendar\\\/appinfo\\\/remote.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/virtua...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/virtual\\\/xyz\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php\",\"Line\":250}","level":4,"time":"2015-12-03T11:52:20+00:00"}
{"reqId":"SY\/5rF6FXsIuDq65soM4","remoteAddr":"212.60.253.106","app":"PHP","message":"Array to string conversion at \/var\/www\/virtual\/xyz\/html\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2015-12-03T12:11:03+00:00"}

**Comment by floecksche** [comment]
Already tried to execute SELECT * FROM oc_clndr_objects WHERE calendardata NOT LIKE '%END:VCALENDAR%'; to find out if there's any broke event, which is not the case. I then even tried it with an empty calendar, same result.
